export var listing={
    city:[
        `city`,`village`,`elector`,`circleCapital`,`capital`,`militaryCapital`,`electorCapital`,`fortified`,
    ],team:[
        `lillebonne`,`mirabel`,`unterwalden`,`valais`,`geneva`,
        `genevois`,`orange`,`gruyeres`,`hohenzollern`,`montfaucon`,
        `luzern`,`junior habsburg`,`zahringen`,`sabran`,`arduinici`,
        `grandson`,`savoy`,`andechs`,`rouergue`,`albon`,
        `ecclesiastical2`,`barcelona`,`free company`,`arles`,`player`,
    ],unit:[
        `0`,`1`,`2`,`3`,`4`,`display`,
    ]
}
export var types={
    city:[],
    team:[],
    cityType:[
        {name:`Base`,term:[0,-1],value:1},//0
        {name:`Village`,term:[1,-1],value:1},
        {name:`Electorate`,term:[0,2],value:2},
        {name:`Circle Capital`,term:[3,-1],value:1.5},
        {name:`Administrative Capital`,term:[4,-1],value:1.25},
        {name:`Military Capital`,term:[5,-1],value:1.5},
        {name:`Symbolic Electorate`,term:[4,6],value:2.5},
    ],map:[
        {
            name:[`Kingdom of Arles`,`Base`],
            term:`écorcheur`,
            city:[
                [
                    {name:`Basel`,type:5,loc:[2465,1022],rule:`League of Cities`},
                    {name:`Gray`,type:2,loc:[1396,1266],rule:`Andechs`},
                    {name:`Besançon`,type:2,loc:[1657,1375],rule:`Ecclesiastical`},
                    {name:`Bern`,type:2,loc:[2465,1514],rule:`League of Cities`},
                    {name:`Lausanne`,type:3,loc:[2047,1913],rule:`Ecclesiastical`},
                    {name:`Geneva`,type:4,loc:[1821,2199],rule:`Geneva`},
                    {name:`Chambéry`,type:3,loc:[1751,2719],rule:`Elder Savoy`},
                    {name:`Feurs`,type:5,loc:[805,2726],rule:`Albon`},
                    {name:`Vienne`,type:2,loc:[1163,2822],rule:`Ecclesiastical`},
                    {name:`Grenoble`,type:2,loc:[1667,3002],rule:`Albon`},
                    {name:`Nyons`,type:3,loc:[1397,3732],rule:`Rouergue`},
                    {name:`Nice`,type:5,loc:[2689,4115],rule:`Elder Savoy`},
                    {name:`Arles`,type:6,loc:[1192,4316],rule:`Ecclesiastical`},
                    {name:`Aix`,type:2,loc:[1667,4376],rule:`Barcelona`},
                    //guaranteed cities
                ],[
                    {name:`Vesoul`,type:0,loc:[1655,1081],rule:`Andechs`},
                    {name:`Montbéliard`,type:0,loc:[2052,1106],rule:`Montfaucon`},
                    {name:`Aarau`,type:0,loc:[2730,1121],rule:`Habsburg`},
                    {name:`Porrentruy`,type:0,loc:[2204,1172],rule:`Ecclesiastical`},
                    {name:`Baume-les-Dames`,type:0,loc:[1820,1279],rule:`Ecclesiastical`},
                    {name:`Solothurn`,type:0,loc:[2470,1294],rule:`League of Cities`},
                    {name:`Willisau`,type:0,loc:[2724,1345],rule:`Habsburg`},
                    {name:`Lucerne`,type:0,loc:[2900,1373],rule:`League of Cities`},
                    {name:`Bienne`,type:0,loc:[2315,1378],rule:`Montfaucon`},
                    {name:`Ornans`,type:0,loc:[1788,1448],rule:`Andechs`},
                    {name:`Sarnen`,type:0,loc:[2891,1502],rule:`Unterwalden`},
                    {name:`Neuchâtel`,type:0,loc:[2172,1515],rule:`Hohenzollern`},
                    {name:`Dole`,type:0,loc:[1345,1574],rule:`Ecclesiastical`},
                    {name:`Pontarlier`,type:0,loc:[1864,1595],rule:`Andechs`},
                    {name:`Salins`,type:0,loc:[1630,1616],rule:`Gruyères`},
                    {name:`Meiringen`,type:0,loc:[2865,1640],rule:`Zähringen`},
                    {name:`Seurre`,type:0,loc:[1187,1641],rule:`Arduinici`},
                    {name:`Fribourg`,type:0,loc:[2322,1646],rule:`League of Cities`},
                    {name:`Thun`,type:0,loc:[2576,1658],rule:`Zähringen`},
                    {name:`Yverdon`,type:0,loc:[2035,1709],rule:`Junior Savoy`},
                    {name:`Gruyères`,type:0,loc:[2288,1841],rule:`Gruyères`},
                    {name:`Lons`,type:0,loc:[1458,1862],rule:`Andechs`},
                    {name:`Visp`,type:0,loc:[2749,2013],rule:`Valais`},
                    {name:`Nyon`,type:0,loc:[1840,2042],rule:`Junior Savoy`},
                    {name:`Aigle`,type:0,loc:[2253,2062],rule:`Junior Savoy`},
                    {name:`Thonon`,type:0,loc:[1961,2065],rule:`Junior Savoy`},
                    {name:`St. Claude`,type:0,loc:[1624,2092],rule:`Andechs`},
                    {name:`Sion`,type:0,loc:[2476,2093],rule:`Valais`},
                    {name:`Martigny`,type:0,loc:[2331,2219],rule:`Ecclesiastical`},
                    {name:`Bourg`,type:0,loc:[1310,2243],rule:`Arduinici`},
                    {name:`Bonneville`,type:0,loc:[1970,2290],rule:`Junior Savoy`},
                    {name:`Beaujeu`,type:0,loc:[977,2334],rule:`Albon`},
                    {name:`Varey`,type:0,loc:[1447,2386],rule:`Arduinici`},
                    {name:`Chamonix`,type:0,loc:[2234,2392],rule:`Junior Savoy`},
                    {name:`Annecy`,type:0,loc:[1788,2464],rule:`Thoire`},
                    {name:`Roanne`,type:0,loc:[702,2485],rule:`Albon`},
                    {name:`Ugine`,type:0,loc:[2013,2552],rule:`Thoire`},
                    {name:`Belley`,type:0,loc:[1558,2569],rule:`Elder Savoy`},
                    {name:`Lyon`,type:0,loc:[1137,2616],rule:`Ecclesiastical`},
                    {name:`Moûtiers`,type:0,loc:[2071,2753],rule:`Ecclesiastical`},
                    {name:`La Tour-du-Pin`,type:0,loc:[1484,2761],rule:`Arduinici`},
                    {name:`St. Jean`,type:0,loc:[2001,2936],rule:`Elder Savoy`},
                    {name:`Beaurepaire`,type:0,loc:[1266,2946],rule:`Ecclesiastical`},
                    {name:`St. Étienne`,type:0,loc:[986,2960],rule:`Albon`},
                    {name:`Vinay`,type:0,loc:[1483,2998],rule:`Ecclesiastical`},
                    {name:`Albon`,type:0,loc:[1216,3072],rule:`Albon`},
                    {name:`Tournon`,type:0,loc:[1160,3154],rule:`Albon`},
                    {name:`Briançon`,type:0,loc:[2196,3214],rule:`Elder Savoy`},
                    {name:`La Mure`,type:0,loc:[1762,3235],rule:`Albon`},
                    {name:`Valence`,type:0,loc:[1211,3271],rule:`Rouergue`},
                    {name:`Die`,type:0,loc:[1502,3384],rule:`Rouergue`},
                    {name:`St. Bonet`,type:0,loc:[1912,3391],rule:`Albon`},
                    {name:`Embrun`,type:0,loc:[2156,3436],rule:`Ecclesiastical`},
                    {name:`Privas`,type:0,loc:[1062,3447],rule:`Ecclesiastical`},
                    {name:`Luc`,type:0,loc:[1569,3500],rule:`Rouergue`},
                    {name:`Gap`,type:0,loc:[1926,3517],rule:`Sabran`},
                    {name:`Aubenas`,type:0,loc:[951,3559],rule:`Ecclesiastical`},
                    {name:`Montélimar`,type:0,loc:[1162,3573],rule:`Rouergue`},
                    {name:`Barcelonette`,type:0,loc:[2277,3638],rule:`Elder Savoy`},
                    {name:`Viviers`,type:0,loc:[1133,3643],rule:`Ecclesiastical`},
                    {name:`St. Paul Tricastin`,type:0,loc:[1211,3761],rule:`Rouergue`},
                    {name:`Montauban`,type:0,loc:[1635,3781],rule:`Rouergue`},
                    {name:`Sisteron`,type:0,loc:[1885,3812],rule:`Sabran`},
                    {name:`Beuil`,type:0,loc:[2479,3823],rule:`Elder Savoy`},
                    {name:`Digne`,type:0,loc:[2060,3891],rule:`Barcelona`},
                    {name:`Orange`,type:0,loc:[1249,3923],rule:`Orange`},
                    {name:`Glandèves`,type:0,loc:[2376,3969],rule:`Barcelona`},
                    {name:`Carpentras`,type:0,loc:[1394,3997],rule:`Rouergue`},
                    {name:`Forcalquier`,type:0,loc:[1826,4019],rule:`Sabran`},
                    {name:`Castellane`,type:0,loc:[2242,4056],rule:`Barcelona`},
                    {name:`Vence`,type:0,loc:[2589,4068],rule:`Barcelona`},
                    {name:`Avignon`,type:0,loc:[1254,4078],rule:`Ecclesiastical`},
                    {name:`Riez`,type:0,loc:[2011,4096],rule:`Barcelona`},
                    {name:`Apt`,type:0,loc:[1596,4102],rule:`Sabran`},
                    {name:`Pertuis`,type:0,loc:[1689,4242],rule:`Ecclesiastical`},
                    {name:`Cannes`,type:0,loc:[2548,4250],rule:`Barcelona`},
                    {name:`Salon`,type:0,loc:[1464,4311],rule:`Barcelona`},
                    {name:`Draguignan`,type:0,loc:[2244,4306],rule:`Barcelona`},
                    {name:`Fréjus`,type:0,loc:[2409,4360],rule:`Barcelona`},
                    {name:`Istres`,type:0,loc:[1404,4424],rule:`Barcelona`},
                    {name:`Brignoles`,type:0,loc:[2039,4435],rule:`Barcelona`},
                    {name:`Fraxinetum`,type:0,loc:[2311,4476],rule:`Barcelona`},
                    {name:`Martigues`,type:0,loc:[1453,4508],rule:`Barcelona`},
                    {name:`Marseille`,type:0,loc:[1647,4566],rule:`Barcelona`},
                    {name:`Toulon`,type:0,loc:[1983,4641],rule:`Barcelona`},
                    {name:`Hyères`,type:0,loc:[2110,4675],rule:`Barcelona`},
                    //chance cities
                ],[
                    {name:`Satigny`,type:1,loc:[1750,2188],rule:`Lillebonne`},
                    //guaranteed villages
                ],[
                    {name:`Luxeuil`,type:1,loc:[1783,915],rule:`Ecclesiastical`},
                    {name:`Rheinfelden`,type:1,loc:[2584,1012],rule:`League of Cities`},
                    {name:`Lure`,type:1,loc:[1858,1026],rule:`Ecclesiastical`},
                    {name:`Port`,type:1,loc:[1602,1036],rule:`Andechs`},
                    {name:`Héricourt`,type:1,loc:[1987,1051],rule:`Montfaucon`},
                    {name:`Habsburg`,type:1,loc:[2808,1051],rule:`Habsburg`},
                    {name:`Liestal`,type:1,loc:[2552,1071],rule:`Zähringen`},
                    {name:`Bremgarten`,type:1,loc:[2902,1130],rule:`League of Cities`},
                    {name:`Champlitte`,type:1,loc:[1342,1149],rule:`Andechs`},
                    {name:`Olten`,type:1,loc:[2647,1163],rule:`Zähringen`},
                    {name:`Delémont`,type:1,loc:[2354,1186],rule:`Ecclesiastical`},
                    {name:`Rioz`,type:1,loc:[1645,1236],rule:`Andechs`},
                    {name:`Sursee`,type:1,loc:[2792,1290],rule:`Habsburg`},
                    {name:`Thunstetten`,type:1,loc:[2591,1299],rule:`Zähringen`},
                    {name:`Burgdorf`,type:1,loc:[2536,1420],rule:`Zähringen`},
                    {name:`St. Vit`,type:1,loc:[1535,1443],rule:`Ecclesiastical`},
                    {name:`La Neuvevile`,type:1,loc:[2251,1443],rule:`Montfaucon`},
                    {name:`Entlebuch`,type:1,loc:[2773,1445],rule:`Habsburg`},
                    {name:`Stans`,type:1,loc:[2943,1451],rule:`Unterwalden`},
                    {name:`Ranflüh`,type:1,loc:[2606,1469],rule:`Zähringen`},
                    {name:`Morteau`,type:1,loc:[1990,1472],rule:`Andechs`},
                    {name:`Auxonne`,type:1,loc:[1296,1499],rule:`Arduinici`},
                    {name:`Engelberg`,type:1,loc:[2979,1560],rule:`Ecclesiastical`},
                    {name:`Laupen`,type:1,loc:[2349,1562],rule:`Zähringen`},
                    {name:`Payerne`,type:1,loc:[2191,1649],rule:`Junior Savoy`},
                    {name:`Arbois`,type:1,loc:[1545,1679],rule:`Andechs`},
                    {name:`Interlaken`,type:1,loc:[2701,1704],rule:`Zähringen`},
                    {name:`Nozeroy`,type:1,loc:[1721,1760],rule:`Gruyères`},
                    {name:`Échallens`,type:1,loc:[2042,1816],rule:`Ecclesiastical`},
                    {name:`Adelboden`,type:1,loc:[2583,1865],rule:`Zähringen`},
                    {name:`Saanen`,type:1,loc:[2379,1897],rule:`Gruyères`},
                    {name:`Ernen`,type:1,loc:[2895,1905],rule:`Valais`},
                    {name:`Morbier`,type:1,loc:[1718,1928],rule:`Andechs`},
                    {name:`Vevey`,type:1,loc:[2178,1952],rule:`Junior Savoy`},
                    {name:`Orgelet`,type:1,loc:[1514,1999],rule:`Andechs`},
                    {name:`Sierre`,type:1,loc:[2563,2033],rule:`Valais`},
                    {name:`Abondance`,type:1,loc:[2091,2064],rule:`Junior Savoy`},
                    {name:`Gex`,type:1,loc:[1737,2101],rule:`Junior Savoy`},
                    {name:`Coligny`,type:1,loc:[1311,2102],rule:`Arduinici`},
                    {name:`St. Maurice`,type:1,loc:[2279,2134],rule:`Ecclesiastical`},
                    {name:`Bâgé`,type:1,loc:[1119,2169],rule:`Arduinici`},
                    {name:`Nantua`,type:1,loc:[1513,2277],rule:`Arduinici`},
                    {name:`St. Julien`,type:1,loc:[1764,2296],rule:`Thoire`},
                    {name:`Sallanches`,type:1,loc:[2112,2385],rule:`Junior Savoy`},
                    {name:`Villars`,type:1,loc:[1220,2409],rule:`Thoire`},
                    {name:`Seyssel`,type:1,loc:[1633,2423],rule:`Elder Savoy`},
                    {name:`Villefranche`,type:1,loc:[1029,2443],rule:`Albon`},
                    {name:`Thônes`,type:1,loc:[1927,2458],rule:`Thoire`},
                    {name:`Tarare`,type:1,loc:[881,2523],rule:`Albon`},
                    {name:`L'Arbresle`,type:1,loc:[986,2575],rule:`Ecclesiastical`},
                    {name:`Albertville`,type:1,loc:[1981,2605],rule:`Thoire`},
                    {name:`Crémieu`,type:1,loc:[1354,2625],rule:`Arduinici`},
                    {name:`Aix-les-Bains`,type:1,loc:[1713,2629],rule:`Elder Savoy`},
                    {name:`Bourg-St. Maurice`,type:1,loc:[2229,2632],rule:`Ecclesiastical`},
                    {name:`Vénissieux`,type:1,loc:[1146,2681],rule:`Ecclesiastical`},
                    {name:`St. Pierre`,type:1,loc:[1914,2703],rule:`Elder Savoy`},
                    {name:`Bourgoin-Jallieu`,type:1,loc:[1373,2722],rule:`Arduinici`},
                    {name:`Mornant`,type:1,loc:[1057,2737],rule:`Ecclesiastical`},
                    {name:`Chazelles`,type:1,loc:[958,2802],rule:`Albon`},
                    {name:`Montbrison`,type:1,loc:[758,2839],rule:`Albon`},
                    {name:`Clermont`,type:1,loc:[1531,2883],rule:`Ecclesiastical`},
                    {name:`Carthause`,type:1,loc:[1708,2884],rule:`Albon`},
                    {name:`Modane`,type:1,loc:[2191,2982],rule:`Elder Savoy`},
                    {name:`Annonay`,type:1,loc:[1070,3061],rule:`Albon`},
                    {name:`St. Marcellin`,type:1,loc:[1432,3069],rule:`Ecclesiastical`},
                    {name:`Bourg d'Oisans`,type:1,loc:[1890,3076],rule:`Albon`},
                    {name:`Vif`,type:1,loc:[1649,3130],rule:`Albon`},
                    {name:`Romans`,type:1,loc:[1296,3166],rule:`Albon`},
                    {name:`Vassieux`,type:1,loc:[1497,3275],rule:`Rouergue`},
                    {name:`Aiguilles`,type:1,loc:[2322,3288],rule:`Elder Savoy`},
                    {name:`Le Cheylard`,type:1,loc:[944,3325],rule:`Ecclesiastical`},
                    {name:`Chalançon`,type:1,loc:[1060,3339],rule:`Ecclesiastical`},
                    {name:`Guillestre`,type:1,loc:[2209,3394],rule:`Ecclesiastical`},
                    {name:`Crest`,type:1,loc:[1285,3436],rule:`Rouergue`},
                    {name:`Veynes`,type:1,loc:[1799,3543],rule:`Sabran`},
                    {name:`Serres`,type:1,loc:[1750,3632],rule:`Sabran`},
                    {name:`Largentière`,type:1,loc:[920,3634],rule:`Ecclesiastical`},
                    {name:`Barcillonnette`,type:1,loc:[1854,3645],rule:`Sabran`},
                    {name:`Rémuzat`,type:1,loc:[1536,3707],rule:`Rouergue`},
                    {name:`Pierrelatte`,type:1,loc:[1150,3747],rule:`Rouergue`},
                    {name:`Allos`,type:1,loc:[2277,3749],rule:`Barcelona`},
                    {name:`Vaison`,type:1,loc:[1396,3832],rule:`Rouergue`},
                    {name:`Séderon`,type:1,loc:[1669,3848],rule:`Rouergue`},
                    {name:`Roquebillière`,type:1,loc:[2690,3878],rule:`Elder Savoy`},
                    {name:`Sault`,type:1,loc:[1616,3978],rule:`Sabran`},
                    {name:`Roquesteron`,type:1,loc:[2529,3996],rule:`Elder Savoy`},
                    {name:`Senez`,type:1,loc:[2182,4000],rule:`Barcelona`},
                    {name:`Roquemaure`,type:1,loc:[1225,4033],rule:`Rouergue`},
                    {name:`Manosque`,type:1,loc:[1840,4119],rule:`Sabran`},
                    {name:`Cavaillon`,type:1,loc:[1400,4150],rule:`Rouergue`},
                    {name:`Grasse`,type:1,loc:[2502,4177],rule:`Barcelona`},
                    {name:`Beaucaire`,type:1,loc:[1162,4193],rule:`Rouergue`},
                    {name:`Antibes`,type:1,loc:[2621,4225],rule:`Barcelona`},
                    {name:`Salernes`,type:1,loc:[2117,4289],rule:`Barcelona`},
                    {name:`Miramas`,type:1,loc:[1408,4358],rule:`Barcelona`},
                    {name:`St. Maximin`,type:1,loc:[1899,4399],rule:`Barcelona`},
                    {name:`Marignane`,type:1,loc:[1522,4476],rule:`Barcelona`},
                    {name:`St. Maries`,type:1,loc:[1086,4494],rule:`Ecclesiastical`},
                    {name:`Aubagne`,type:1,loc:[1764,4550],rule:`Barcelona`},
                    {name:`Cavalaire`,type:1,loc:[2310,4600],rule:`Barcelona`},
                    //60% villages
                ],[
                    {name:`Miribel`,type:1,loc:[1200,2514],rule:`Mirabel`},
                    {name:`Miribel-les-Échelles`,type:1,loc:[1644,2822],rule:`Mirabel`},
                    {name:`Miribel-Valherbasse`,type:1,loc:[1306,3057],rule:`Mirabel`},
                    {name:`Miribel-Lanchâtre`,type:1,loc:[1630,3192],rule:`Mirabel`},
                    {name:`Mirabel-et-Blacons`,type:1,loc:[1366,3406],rule:`Mirabel`},
                    {name:`Mirabel`,type:1,loc:[1017,3550],rule:`Mirabel`},
                    {name:`Mirabel-aux-Baronnies`,type:1,loc:[1381,3780],rule:`Mirabel`},
                    {name:`Mirabelle`,type:1,loc:[1693,4533],rule:`Mirabel`},
                    //50% villages
                ],
            ],team:[
                {name:`Lillebonne`,term:`lillebonne`,quality:1.1},
                {name:`Mirabel`,term:`mirabel`,quality:1.1},
                {name:`Unterwalden`,term:`unterwalden`,quality:1.1},
                {name:`Valais`,term:`valais`,quality:1},
                {name:`Geneva`,term:`geneva`,quality:1},
                {name:`Thoire`,term:`genevois`,quality:1},
                {name:`Orange`,term:`orange`,quality:1},
                {name:`Gruyères`,term:`gruyeres`,quality:1},
                {name:`Hohenzollern`,term:`hohenzollern`,quality:1},
                {name:`Montfaucon`,term:`montfaucon`,quality:1},
                {name:`League of Cities`,term:`luzern`,quality:0.95},
                {name:`Habsburg`,term:`junior habsburg`,quality:1},
                {name:`Zähringen`,term:`zahringen`,quality:1},
                {name:`Sabran`,term:`sabran`,quality:1},
                {name:`Arduinici`,term:`arduinici`,quality:1},
                {name:`Junior Savoy`,term:`grandson`,quality:1},
                {name:`Elder Savoy`,term:`savoy`,quality:1},
                {name:`Andechs`,term:`andechs`,quality:1},
                {name:`Rouergue`,term:`rouergue`,quality:1},
                {name:`Albon`,term:`albon`,quality:1},
                {name:`Ecclesiastical`,term:`ecclesiastical2`,quality:0.95},
                {name:`Barcelona`,term:`barcelona`,quality:1},
                {name:`Free Company`,term:`free company`,quality:1.4},
                {name:`Royal Army`,term:`arles`,quality:1},
                {name:`Player`,term:`player`,quality:1.5},
            ],
        },
    ],
}
export var dev={}
export var options={strength:1,unitSize:1,scale:1,hq:false}
export var graphics={main:0,load:{map:[],city:[],team:[],unit:[]}}
export var constants={trig:[[],[]],int:false}
export var inputs={mouse:{base:{x:0,y:0},rel:{x:0,y:0},previous:{base:{x:0,y:0},rel:{x:0,y:0}}}}