import {types,dev,graphics,options} from './variables.mjs'
import {smoothAnim,moveTowardVecDynamic,floor,random,round,findName} from './functions.mjs'
export class unit{
    constructor(city,team,type,value){
        this.city=city
        this.team=team
        this.type=type
        this.value=value
        this.fade={main:0,trigger:true}
        this.reveal={main:1,trigger:true}
        this.edit={num:0,trigger:false}
        this.tempVisible=false
        this.position={x:0,y:0}
        this.goal={position:{x:0,y:0}}
        this.remove=false
        this.removeMark=false
        this.combining=false
        this.turns=0
        this.target=[floor(random(0,this.city.operation.cities.length)),floor(random(0,this.city.operation.cities.length)),floor(random(0,this.city.operation.cities.length))]
        if(this.city==undefined){
            throw new Error(`Undefined City Fail`)
        }
    }
    save(){
        let composite={
            team:types.team[this.team].name,
            type:this.type,
            value:this.value,
            fade:this.fade,
            reveal:this.reveal,
            edit:this.edit,
            tempVisible:this.tempVisible,
            position:this.position,
            goal:this.goal,
            remove:this.remove,
            removeMark:this.removeMark,
            turns:this.turns,
        }
        return composite
    }
    load(composite){
        this.team=findName(typeof(composite.team)==`number`?convert[0][composite.team]:composite.team,types.team)
        this.type=composite.type
        this.value=composite.value
        this.fade=composite.fade
        this.reveal=composite.reveal
        this.edit=composite.edit
        this.tempVisible=composite.tempVisible
        this.position=composite.position
        this.goal=composite.goal
        this.remove=composite.remove
        this.removeMark=composite.removeMark
        this.turns=composite.turns
    }
    newTurn(){
        if(this.value>2500&&this.turns>=50&&this.type==0&&floor(random(0,10))==0){
            let diff=round(this.value*random(0,0.04)/100)*100
            if(diff>0){
                this.value-=diff
                this.city.operation.teams[this.team].deserters+=diff
            }
        }
        if(this.value%100!=0&&options.strength==1){
            print(this.value)
            throw new Error(`Rounding Fail`)
        }
        this.turns++
    }
    nameSelf(){
        return `${types.team[this.team].name} ${[`Army`,`Garrison`][this.type]} of ${this.value}`
    }
    display(layer){
        if(this.fade.main>0){
            if(this.position.x!=0||this.position.y!=0){
                layer.push()
                layer.translate(this.position.x,this.position.y)
            }
            let img=[graphics.load.team[types.team[this.team].loadIndex],graphics.load.unit[this.type]]
            layer.image(img[0],0,0,img[1].width*this.fade.main*options.unitSize-0.5,img[1].height*this.fade.main*options.unitSize-0.5)
            layer.image(img[1],0,0,img[1].width*this.fade.main*options.unitSize,img[1].height*this.fade.main*options.unitSize)
            layer.noStroke()
            layer.fill(0,this.reveal.main*this.fade.main)
            layer.textSize(15)
            layer.text(this.value,0,(29-this.type*9)*options.unitSize+3)
            layer.fill(0,(1-this.reveal.main)*this.fade.main)
            layer.text(`?`,0,(29-this.type*9)*options.unitSize+3)
            if(this.position.x!=0||this.position.y!=0){
                layer.pop()
            }
        }
    }
    update(visibility){
        if(dev.close){
            this.fade.trigger=visibility>=1||this.tempVisible
            this.reveal.trigger=visibility>=2||this.tempVisible
            this.fade.main=this.fade.trigger?1:0
            this.reveal.main=this.reveal.trigger?1:0
            if(this.removeMark){
                this.remove=true
            }
        }else{
            this.fade.trigger=visibility>=1||this.tempVisible
            this.reveal.trigger=visibility>=2||this.tempVisible
            this.fade.main=smoothAnim(this.fade.main,this.fade.trigger&&!this.remove,0,1,15)
            this.reveal.main=smoothAnim(this.reveal.main,this.reveal.trigger,0,1,15)
            this.position=dev.instant?{x:this.goal.position.x,y:this.goal.position.y}:moveTowardVecDynamic(this,this.goal,1,0.125)
            if(this.removeMark&&(this.fade.main>=1||!this.fade.trigger)){
                this.remove=true
            }
        }
    }
}