class unit{
    constructor(city,team,type,value){
        this.city=city
        this.team=team
        this.type=type
        this.value=value
        this.fade={main:0,trigger:true}
        this.reveal={main:1,trigger:true}
        this.edit={num:0,trigger:false}
        this.tempVisible=false
        this.position={x:0,y:0}
        this.goal={position:{x:0,y:0}}
        this.remove=false
        this.removeMark=false
        this.turns=0
    }
    save(){
        let composite={
            team:this.team,
            type:this.type,
            value:this.value,
            fade:this.fade,
            reveal:this.reveal,
            edit:this.edit,
            tempVisible:this.tempVisible,
            position:this.position,
            goal:this.goal,
            remove:this.remove,
            removeMark:this.removeMark,
            turns:this.turns,
        }
        return composite
    }
    load(composite){
        this.team=composite.team
        this.type=composite.type
        this.value=composite.value
        this.fade=composite.fade
        this.reveal=composite.reveal
        this.edit=composite.edit
        this.tempVisible=composite.tempVisible
        this.position=composite.position
        this.goal=composite.goal
        this.remove=composite.remove
        this.removeMark=composite.removeMark
        this.turns=composite.turns
    }
    newTurn(){
        if(this.value>=2000&&this.turns>=50){
            this.value-=round((this.value-1000)*random(0,0.05)/100)*100
        }
        this.turns++
    }
    display(layer){
        if(this.fade.main>0){
            if(this.position.x!=0||this.position.y!=0){
                layer.push()
                layer.translate(this.position.x,this.position.y)
            }
            layer.image(graphics.load.unit[this.team][this.type],0,0,graphics.load.unit[this.team][this.type].width*this.fade.main,graphics.load.unit[this.team][this.type].height*this.fade.main)
            layer.noStroke()
            layer.fill(0,(this.reveal.main)*this.fade.main)
            layer.textSize(15)
            layer.text(this.value,0,31.5-this.type*9)
            layer.fill(0,(1-this.reveal.main)*this.fade.main)
            layer.text(`?`,0,31.5-this.type*9)
            if(this.position.x!=0||this.position.y!=0){
                layer.pop()
            }
        }
    }
    update(visibility){
        this.fade.trigger=visibility>=1||this.tempVisible
        this.fade.trigger=visibility>=1||this.tempVisible
        this.reveal.trigger=visibility>=2||this.tempVisible
        this.fade.main=smoothAnim(this.fade.main,this.fade.trigger&&!this.remove,0,1,15)
        this.reveal.main=smoothAnim(this.reveal.main,this.reveal.trigger,0,1,15)
        this.position=moveTowardVecDynamic(this,this.goal,0.5,0.125)
        if(this.removeMark&&(this.fade.main>=1||!this.fade.trigger)){
            this.remove=true
        }
    }
}