export var listing={
    city:[
        `cityPNG`,`electorPNG`,`circleCapitalPNG`,`majorCityPNG`
    ],team:[
        `albon`,`andechs`,`arduinici`,`arenberg`,`ascania`,`avesnes`,`baden`,`barcelona`,`bibra`,`dampierre`,
        `ecclesiastical`,`ecclesiastical2`,`ecclesiastical3`,`elder habsburg`,`elder wittelsbach`,`friesland`,`geneva`,`genevois`,`harcourt`,`hesse`,
        `hohenzollern`,`isenberg`,`junior habsburg`,`junior wittelsbach`,`kyburg`,`league of cities`,`league of cities2`,`league of cities3`,`leuven`,`lillebonne`,
        `lorraine`,`luxemburg`,`marck`,`nassau`,`niklot`,`premyslid`,`rouergue`,`sabran`,`savoy`,`schwyz`,
        `toggenburg`,`two leagues`,`unterwalden`,`valais`,`vermandois`,`wassenberg`,`welf`,`wettin`,`wiemken`,`wurttemberg`,
        `zahringen`,
    ],unit:[
        `large`,`garrison`,`display`
    ]
}
export var types={
    city:[],
    team:[],
    cityType:[
        {name:`Base`,term:0,value:1},
        {name:`Electorate`,term:1,value:2},
        {name:`Circle Capital`,term:2,value:1.5},
        {name:`Administrative Capital`,term:3,value:1.25},
        {name:`Symbolic Capital`,term:3,value:1.25},
    ],teamType:[
        {name:`Rural`,affinity:[6,6,2,1,2,0]},
        {name:`Urban`,affinity:[6,8,4,2,2,0]},
        {name:`Minor Nobility`,affinity:[2,4,4,4,3,1]},
        {name:`Middle Nobility`,affinity:[1,2,4,2,2,0]},
        {name:`Major Nobility`,affinity:[2,2,3,2,1,0]},
        {name:`Massive Nobility`,affinity:[0,0,1,0,0,0]},
    ],map:[
        {
            name:[`Tiny`],
            term:`minim`,
            stack:false,
            teamSet:2,
            constants:{spawn:{base:2500,spend:1000,regen:30,garrison:500}},
            city:[
                {name:`Frankfurt`,type:2,loc:[1216,24],rule:`Isenberg`,connect:[{name:`Würzburg`,type:1},{name:`Heidelberg`,type:0},{name:`Oppenheim`,type:1}]},
                {name:`Simmern`,type:0,loc:[887,83],rule:`Wittelsbach`,connect:[{name:`Trier`,type:0},{name:`Oppenheim`,type:0}]},
                {name:`Oppenheim`,type:0,loc:[1099,152],rule:`Wittelsbach`,connect:[{name:`Speyer`,type:0},{name:`Heidelberg`,type:1},{name:`Frankfurt`,type:1},{name:`Simmern`,type:0},{name:`Pirmasens`,type:0}]},
                {name:`Würzburg`,type:1,loc:[1580,191],rule:`Bibra`,connect:[{name:`Hall`,type:0},{name:`Frankfurt`,type:1}]},
                {name:`Trier`,type:1,loc:[609,192],rule:`Ecclesiastical`,connect:[{name:`Simmern`,type:0},{name:`Metz`,type:0},{name:`Luxemburg`,type:1}]},
                {name:`Luxemburg`,type:0,loc:[448,251],rule:`Habsburg`,connect:[{name:`Trier`,type:1},{name:`Metz`,type:0}]},
                {name:`Heidelberg`,type:1,loc:[1202,378],rule:`Wittelsbach`,connect:[{name:`Frankfurt`,type:0},{name:`Stuttgart`,type:0},{name:`Speyer`,type:0},{name:`Oppenheim`,type:1}]},
                {name:`Speyer`,type:0,loc:[1123,414],rule:`Zähringen`,connect:[{name:`Pirmasens`,type:1},{name:`Heidelberg`,type:0},{name:`Oppenheim`,type:0},{name:`Stuttgart`,type:0},{name:`Straßburg`,type:0}]},
                {name:`Metz`,type:0,loc:[448,482],rule:`Lorraine`,connect:[{name:`Trier`,type:0},{name:`Pirmasens`,type:0},{name:`Bar`,type:1},{name:`Nanzig`,type:0},{name:`Luxemburg`,type:0}]},
                {name:`Pirmasens`,type:0,loc:[825,489],rule:`League of Cities`,connect:[{name:`Oppenheim`,type:0},{name:`Metz`,type:0},{name:`Speyer`,type:1},{name:`Straßburg`,type:0}]},
                {name:`Hall`,type:0,loc:[1510,522],rule:`League of Cities`,connect:[{name:`Würzburg`,type:0},{name:`Stuttgart`,type:0},{name:`Ulm`,type:0}]},
                {name:`Bar`,type:0,loc:[129,640],rule:`Lillebonne`,connect:[{name:`Metz`,type:1},{name:`Nanzig`,type:1}]},
                {name:`Stuttgart`,type:0,loc:[1336,683],rule:`Württemberg`,connect:[{name:`Heidelberg`,type:0},{name:`Speyer`,type:0},{name:`Hall`,type:0},{name:`Ulm`,type:0}]},
                {name:`Nanzig`,type:2,loc:[441,688],rule:`Lorraine`,connect:[{name:`Metz`,type:0},{name:`Bar`,type:1},{name:`Straßburg`,type:0}]},
                {name:`Straßburg`,type:0,loc:[916,764],rule:`League of Cities`,connect:[{name:`Nanzig`,type:0},{name:`Pirmasens`,type:0},{name:`Speyer`,type:0}]},
                {name:`Ulm`,type:3,loc:[1586,865],rule:`League of Cities`,connect:[{name:`Hall`,type:0},{name:`Stuttgart`,type:0}]},
            ],team:[
                {name:`Isenberg`,term:`isenberg`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Zähringen`,term:`baden`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Lillebonne`,term:`lillebonne`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Württemberg`,term:`wurttemberg`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Bibra`,term:`bibra`,type:`Middle Nobility`,allies:[],quality:1,chance:1},
                {name:`Ecclesiastical`,term:`ecclesiastical`,type:`Major Nobility`,allies:[],quality:0.9,chance:1},
                {name:`Habsburg`,term:`elder habsburg`,type:`Major Nobility`,allies:[],quality:1,chance:1},
                {name:`Lorraine`,term:`lorraine`,type:`Middle Nobility`,allies:[],quality:1,chance:1},
                {name:`League of Cities`,term:`league of cities`,type:`Urban`,allies:[],quality:0.9,chance:1.5},
                {name:`Wittelsbach`,term:`elder wittelsbach`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
            ],
        },{
            name:[`HRE`,`Base`],
            term:`hre`,
            stack:false,
            teamSet:3,
            constants:{spawn:{base:2500,spend:1000,regen:10,garrison:500}},
            city:[
                {name:`Rostock`,type:0,loc:[2399,437],rule:`Niklot`,connect:[{name:`Schwerin`,type:0},{name:`Lübeck`,type:2},{name:`Waren`,type:0}]},
                {name:`Lübeck`,type:0,loc:[2024,539],rule:`Ascania`,connect:[{name:`Schwerin`,type:0},{name:`Lüneburg`,type:1},{name:`Glückstadt`,type:0},{name:`Rostock`,type:2}]},
                {name:`Glückstadt`,type:2,loc:[1690,597],rule:`Hohenzollern`,connect:[{name:`Lübeck`,type:0},{name:`Lüneburg`,type:1},{name:`Bremen`,type:0},{name:`Jever`,type:2}]},
                {name:`Schwerin`,type:1,loc:[2196,640],rule:`Niklot`,connect:[{name:`Rostock`,type:0},{name:`Lübeck`,type:0},{name:`Lüneburg`,type:1},{name:`Waren`,type:0}]},
                {name:`Jever`,type:0,loc:[1251,675],rule:`Wiemken`,connect:[{name:`Oldenburg`,type:0},{name:`Meppen`,type:0},{name:`Glückstadt`,type:2},{name:`Emden`,type:0}]},
                {name:`Waren`,type:0,loc:[2558,704],rule:`Niklot`,connect:[{name:`Schwerin`,type:0},{name:`Rostock`,type:0}]},
                {name:`Emden`,type:0,loc:[1067,761],rule:`Arenberg`,connect:[{name:`Oldenburg`,type:0},{name:`Jever`,type:0},{name:`Meppen`,type:0}]},
                {name:`Lüneburg`,type:0,loc:[1929,847],rule:`Welf`,connect:[{name:`Lübeck`,type:1},{name:`Schwerin`,type:1},{name:`Bremen`,type:0},{name:`Celle`,type:0},{name:`Braunschweig`,type:1},{name:`Glückstadt`,type:1}]},
                {name:`Oldenburg`,type:0,loc:[1328,892],rule:`Arenberg`,connect:[{name:`Jever`,type:0},{name:`Meppen`,type:0},{name:`Bremen`,type:0},{name:`Minden`,type:0},{name:`Emden`,type:0}]},
                {name:`Bremen`,type:0,loc:[1493,926],rule:`Ecclesiastical`,connect:[{name:`Oldenburg`,type:0},{name:`Lüneburg`,type:0},{name:`Celle`,type:0},{name:`Glückstadt`,type:0}]},
                {name:`Meppen`,type:1,loc:[1067,1094],rule:`Arenberg`,connect:[{name:`Oldenburg`,type:0},{name:`Jever`,type:0},{name:`Minden`,type:0},{name:`Emden`,type:0}]},
                {name:`Celle`,type:0,loc:[1837,1151],rule:`Welf`,connect:[{name:`Bremen`,type:0},{name:`Minden`,type:0},{name:`Hannover`,type:0},{name:`Braunschweig`,type:0},{name:`Lüneburg`,type:0}]},
                {name:`Hannover`,type:0,loc:[1749,1279],rule:`Welf`,connect:[{name:`Celle`,type:0},{name:`Braunschweig`,type:0},{name:`Goslar`,type:0},{name:`Minden`,type:0},{name:`Paderborn`,type:1}]},
                {name:`Minden`,type:0,loc:[1524,1304],rule:`Ecclesiastical`,connect:[{name:`Meppen`,type:0},{name:`Oldenburg`,type:0},{name:`Hannover`,type:0},{name:`Paderborn`,type:0},{name:`Celle`,type:0}]},
                {name:`Braunschweig`,type:2,loc:[1972,1327],rule:`Welf`,connect:[{name:`Lüneburg`,type:1},{name:`Hannover`,type:0},{name:`Goslar`,type:0},{name:`Celle`,type:0}]},
                {name:`Goslar`,type:0,loc:[1948,1491],rule:`Avesnes`,connect:[{name:`Braunschweig`,type:0},{name:`Hannover`,type:0},{name:`Kassel`,type:1},{name:`Erfurt`,type:0}]},
                {name:`Paderborn`,type:2,loc:[1472,1579],rule:`Ecclesiastical`,connect:[{name:`Minden`,type:0},{name:`Hannover`,type:1},{name:`Kassel`,type:0},{name:`Fredeburg`,type:1}]},
                {name:`Kassel`,type:0,loc:[1673,1771],rule:`Hesse`,connect:[{name:`Goslar`,type:1},{name:`Paderborn`,type:0},{name:`Fredeburg`,type:0},{name:`Gießen`,type:0},{name:`Fulda`,type:0},{name:`Erfurt`,type:1}]},
                {name:`Düsseldorf`,type:0,loc:[911,1806],rule:`Junior Wittelsbach`,connect:[{name:`Köln`,type:1},{name:`Altena`,type:0},{name:`Siegen`,type:0}]},
                {name:`Altena`,type:0,loc:[1166,1814],rule:`Hohenzollern`,connect:[{name:`Fredeburg`,type:0},{name:`Düsseldorf`,type:0}]},
                {name:`Fredeburg`,type:0,loc:[1333,1850],rule:`Ecclesiastical`,connect:[{name:`Kassel`,type:0},{name:`Paderborn`,type:1},{name:`Siegen`,type:0},{name:`Altena`,type:0}]},
                {name:`Erfurt`,type:2,loc:[2127,1950],rule:`Wettin`,connect:[{name:`Goslar`,type:0},{name:`Kassel`,type:1},{name:`Fulda`,type:1},{name:`Coburg`,type:0},{name:`Gera`,type:0}]},
                {name:`Köln`,type:2,loc:[946,1952],rule:`Junior Wittelsbach`,connect:[{name:`Koblenz`,type:0},{name:`Düsseldorf`,type:1},{name:`Lüttich`,type:1}]},
                {name:`Gera`,type:0,loc:[2431,1983],rule:`Wettin`,connect:[{name:`Erfurt`,type:0},{name:`Plauen`,type:0},{name:`Coburg`,type:0}]},
                {name:`Siegen`,type:0,loc:[1267,1989],rule:`Nassau`,connect:[{name:`Düsseldorf`,type:0},{name:`Fredeburg`,type:0},{name:`Gießen`,type:0},{name:`Koblenz`,type:0}]},
                {name:`Lüttich`,type:0,loc:[536,2083],rule:`Ecclesiastical`,connect:[{name:`Köln`,type:0},{name:`Rochefort`,type:0},{name:`Luxemburg`,type:0}]},
                {name:`Gießen`,type:0,loc:[1445,2110],rule:`Hesse`,connect:[{name:`Kassel`,type:0},{name:`Fulda`,type:0},{name:`Siegen`,type:0},{name:`Frankfurt`,type:0}]},
                {name:`Fulda`,type:0,loc:[1736,2148],rule:`Ecclesiastical`,connect:[{name:`Kassel`,type:0},{name:`Erfurt`,type:1},{name:`Coburg`,type:1},{name:`Gießen`,type:0},{name:`Schweinfurt`,type:0}]},
                {name:`Plauen`,type:0,loc:[2445,2173],rule:`Hohenzollern`,connect:[{name:`Bamberg`,type:0},{name:`Amberg`,type:0},{name:`Gera`,type:0},{name:`Nürnberg`,type:0}]},
                {name:`Koblenz`,type:0,loc:[1119,2239],rule:`Ecclesiastical`,connect:[{name:`Köln`,type:0},{name:`Siegen`,type:0},{name:`Simmern`,type:0},{name:`Trier`,type:1},{name:`Frankfurt`,type:0}]},
                {name:`Rochefort`,type:0,loc:[461,2277],rule:`Avesnes`,connect:[{name:`Luxemburg`,type:0},{name:`Lüttich`,type:0}]},
                {name:`Coburg`,type:0,loc:[2108,2294],rule:`Wettin`,connect:[{name:`Erfurt`,type:0},{name:`Gera`,type:0},{name:`Fulda`,type:1},{name:`Bamberg`,type:0},{name:`Schweinfurt`,type:0}]},
                {name:`Frankfurt`,type:2,loc:[1448,2359],rule:`Isenberg`,connect:[{name:`Gießen`,type:0},{name:`Würzburg`,type:1},{name:`Heidelberg`,type:0},{name:`Oppenheim`,type:1},{name:`Koblenz`,type:0}]},
                {name:`Schweinfurt`,type:0,loc:[1894,2396],rule:`Bibra`,connect:[{name:`Bamberg`,type:0},{name:`Fulda`,type:0},{name:`Coburg`,type:0},{name:`Würzburg`,type:0}]},
                {name:`Simmern`,type:0,loc:[1119,2418],rule:`Elder Wittelsbach`,connect:[{name:`Koblenz`,type:0},{name:`Trier`,type:0},{name:`Oppenheim`,type:0}]},
                {name:`Bamberg`,type:0,loc:[2077,2486],rule:`Bibra`,connect:[{name:`Würzburg`,type:1},{name:`Schweinfurt`,type:0},{name:`Coburg`,type:0},{name:`Plauen`,type:0},{name:`Nürnberg`,type:0}]},
                {name:`Oppenheim`,type:0,loc:[1331,2487],rule:`Elder Wittelsbach`,connect:[{name:`Speyer`,type:0},{name:`Heidelberg`,type:1},{name:`Frankfurt`,type:1},{name:`Simmern`,type:0},{name:`Pirmasens`,type:0}]},
                {name:`Würzburg`,type:1,loc:[1812,2526],rule:`Bibra`,connect:[{name:`Bamberg`,type:1},{name:`Hall`,type:0},{name:`Frankfurt`,type:1},{name:`Nürnberg`,type:1},{name:`Schweinfurt`,type:0}]},
                {name:`Trier`,type:1,loc:[841,2527],rule:`Ecclesiastical`,connect:[{name:`Koblenz`,type:1},{name:`Simmern`,type:0},{name:`Metz`,type:0},{name:`Luxemburg`,type:1}]},
                {name:`Luxemburg`,type:0,loc:[680,2586],rule:`Elder Habsburg`,connect:[{name:`Trier`,type:1},{name:`Metz`,type:0},{name:`Rochefort`,type:0},{name:`Lüttich`,type:0}]},
                {name:`Nürnberg`,type:2,loc:[2149,2693],rule:`Hohenzollern`,connect:[{name:`Ingolstadt`,type:0},{name:`Amberg`,type:0},{name:`Hall`,type:1},{name:`Würzburg`,type:1},{name:`Bamberg`,type:0},{name:`Plauen`,type:0}]},
                {name:`Amberg`,type:0,loc:[2396,2705],rule:`Elder Wittelsbach`,connect:[{name:`Regensburg`,type:0},{name:`Ingolstadt`,type:0},{name:`Plauen`,type:0},{name:`Nürnberg`,type:0},{name:`Straubing`,type:0}]},
                {name:`Heidelberg`,type:1,loc:[1434,2713],rule:`Elder Wittelsbach`,connect:[{name:`Frankfurt`,type:0},{name:`Stuttgart`,type:0},{name:`Speyer`,type:0},{name:`Oppenheim`,type:1}]},
                {name:`Speyer`,type:0,loc:[1355,2749],rule:`Zähringen`,connect:[{name:`Pirmasens`,type:1},{name:`Heidelberg`,type:0},{name:`Oppenheim`,type:0},{name:`Stuttgart`,type:0},{name:`Freiburg`,type:0}]},
                {name:`Metz`,type:0,loc:[680,2817],rule:`Lorraine`,connect:[{name:`Trier`,type:0},{name:`Pirmasens`,type:0},{name:`Bar`,type:1},{name:`Nanzig`,type:0},{name:`Luxemburg`,type:0}]},
                {name:`Pirmasens`,type:0,loc:[1057,2824],rule:`League of Cities`,connect:[{name:`Oppenheim`,type:0},{name:`Metz`,type:0},{name:`Speyer`,type:1},{name:`Straßburg`,type:0}]},
                {name:`Hall`,type:0,loc:[1742,2857],rule:`League of Cities`,connect:[{name:`Nürnberg`,type:1},{name:`Würzburg`,type:0},{name:`Stuttgart`,type:0},{name:`Ulm`,type:0}]},
                {name:`Regensburg`,type:1,loc:[2456,2894],rule:`Ecclesiastical`,connect:[{name:`Amberg`,type:0},{name:`Ingolstadt`,type:0},{name:`Straubing`,type:0}]},
                {name:`Straubing`,type:0,loc:[2601,2956],rule:`Ecclesiastical`,connect:[{name:`Amberg`,type:0},{name:`Regensburg`,type:0}]},
                {name:`Bar`,type:0,loc:[361,2975],rule:`Lillebonne`,connect:[{name:`Metz`,type:1},{name:`Spinneln`,type:1}]},
                {name:`Stuttgart`,type:0,loc:[1568,3018],rule:`Württemberg`,connect:[{name:`Heidelberg`,type:0},{name:`Speyer`,type:0},{name:`Hall`,type:0},{name:`Ulm`,type:0},{name:`Freiburg`,type:0}]},
                {name:`Nanzig`,type:2,loc:[673,3023],rule:`Lorraine`,connect:[{name:`Metz`,type:0},{name:`Spinneln`,type:0},{name:`Straßburg`,type:0}]},
                {name:`Ingolstadt`,type:0,loc:[2246,3025],rule:`Junior Wittelsbach`,connect:[{name:`Ulm`,type:0},{name:`Regensburg`,type:0},{name:`Amberg`,type:0},{name:`Nürnberg`,type:0}]},
                {name:`Straßburg`,type:0,loc:[1148,3099],rule:`League of Cities`,connect:[{name:`Nanzig`,type:0},{name:`Pirmasens`,type:0},{name:`Freiburg`,type:1},{name:`Vesoul`,type:0},{name:`Spinneln`,type:1}]},
                {name:`Ulm`,type:3,loc:[1818,3200],rule:`League of Cities`,connect:[{name:`Hall`,type:0},{name:`Stuttgart`,type:0},{name:`Ingolstadt`,type:0},{name:`Bregenz`,type:0}]},
                {name:`Spinneln`,type:0,loc:[750,3284],rule:`Lorraine`,connect:[{name:`Vesoul`,type:0},{name:`Bar`,type:1},{name:`Straßburg`,type:1},{name:`Nanzig`,type:0}]},
                {name:`Freiburg`,type:0,loc:[1176,3389],rule:`Junior Habsburg`,connect:[{name:`Speyer`,type:0},{name:`Straßburg`,type:1},{name:`Stuttgart`,type:0},{name:`Konstanz`,type:0},{name:`Solothurn`,type:1}]},
                {name:`Vesoul`,type:0,loc:[632,3550],rule:`Elder Habsburg`,connect:[{name:`Spinneln`,type:0},{name:`Straßburg`,type:0},{name:`Bisanz`,type:0}]},
                {name:`Konstanz`,type:2,loc:[1562,3554],rule:`Junior Habsburg`,connect:[{name:`Freiburg`,type:0},{name:`Bregenz`,type:0},{name:`Herisau`,type:0}]},
                {name:`Bregenz`,type:0,loc:[1756,3640],rule:`Junior Habsburg`,connect:[{name:`Ulm`,type:0},{name:`Konstanz`,type:0},{name:`Herisau`,type:1},{name:`Davos`,type:0}]},
                {name:`Herisau`,type:0,loc:[1589,3710],rule:`Schwyz`,connect:[{name:`Bregenz`,type:1},{name:`Konstanz`,type:0},{name:`Davos`,type:1},{name:`Solothurn`,type:1}]},
                {name:`Bisanz`,type:2,loc:[588,3728],rule:`Elder Habsburg`,connect:[{name:`Vesoul`,type:0},{name:`Solothurn`,type:1}]},
                {name:`Solothurn`,type:0,loc:[1068,3774],rule:`Junior Habsburg`,connect:[{name:`Bisanz`,type:1},{name:`Herisau`,type:1},{name:`Freiburg`,type:1}]},
                {name:`Davos`,type:0,loc:[1749,3978],rule:`Two Leagues`,connect:[{name:`Bregenz`,type:0},{name:`Herisau`,type:1}]},
            ],team:[
                {name:`Wiemken`,term:`wiemken`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Isenberg`,term:`isenberg`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Nassau`,term:`nassau`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Zähringen`,term:`baden`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Ascania`,term:`ascania`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Schwyz`,term:`schwyz`,type:`Rural`,allies:[`Two Leagues`],quality:1.1,chance:0.5},
                {name:`Two Leagues`,term:`two leagues`,type:`Rural`,allies:[`Schwyz`],quality:1,chance:0.5},
                {name:`Lillebonne`,term:`lillebonne`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Württemberg`,term:`wurttemberg`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Avesnes`,term:`avesnes`,type:`Minor Nobility`,allies:[],quality:1,chance:1},
                {name:`Hesse`,term:`hesse`,type:`Middle Nobility`,allies:[],quality:1,chance:1},
                {name:`Arenberg`,term:`arenberg`,type:`Middle Nobility`,allies:[],quality:1,chance:1},
                {name:`Niklot`,term:`niklot`,type:`Middle Nobility`,allies:[],quality:1,chance:1},
                {name:`Bibra`,term:`bibra`,type:`Middle Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Hohenzollern`,term:`hohenzollern`,type:`Middle Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Ecclesiastical`,term:`ecclesiastical`,type:`Major Nobility`,allies:[],quality:0.9,chance:1.5},
                {name:`League of Cities`,term:`league of cities`,type:`Urban`,allies:[],quality:0.9,chance:1.5},
                {name:`Lorraine`,term:`lorraine`,type:`Middle Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Welf`,term:`welf`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Wettin`,term:`wettin`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Elder Habsburg`,term:`elder habsburg`,type:`Major Nobility`,allies:[`Junior Habsburg`],quality:1,chance:1.5},
                {name:`Junior Habsburg`,term:`junior habsburg`,type:`Major Nobility`,allies:[`Elder Habsburg`],quality:1,chance:1.5},
                {name:`Elder Wittelsbach`,term:`elder wittelsbach`,type:`Major Nobility`,allies:[`Junior Wittelsbach`],quality:1,chance:1.5},
                {name:`Junior Wittelsbach`,term:`junior wittelsbach`,type:`Major Nobility`,allies:[`Elder Wittelsbach`],quality:1,chance:1.5},
            ],
        },{
            name:[`HRE`,`+ Bohemia`],
            term:`hre+bohemia`,
            stack:true,
            teamSet:3,
            constants:{spawn:{base:2500,spend:1000,regen:10,garrison:500}},
            city:[
                {name:`Rostock`,type:0,loc:[2399,437],rule:`Niklot`,connect:[{name:`Schwerin`,type:0},{name:`Lübeck`,type:2},{name:`Waren`,type:0}]},
                {name:`Lübeck`,type:0,loc:[2024,539],rule:`Ascania`,connect:[{name:`Schwerin`,type:0},{name:`Lüneburg`,type:1},{name:`Glückstadt`,type:0},{name:`Rostock`,type:2}]},
                {name:`Glückstadt`,type:2,loc:[1690,597],rule:`Hohenzollern`,connect:[{name:`Lübeck`,type:0},{name:`Lüneburg`,type:1},{name:`Bremen`,type:0},{name:`Jever`,type:2}]},
                {name:`Schwerin`,type:1,loc:[2196,640],rule:`Niklot`,connect:[{name:`Rostock`,type:0},{name:`Lübeck`,type:0},{name:`Lüneburg`,type:1},{name:`Waren`,type:0}]},
                {name:`Jever`,type:0,loc:[1251,675],rule:`Wiemken`,connect:[{name:`Oldenburg`,type:0},{name:`Meppen`,type:0},{name:`Glückstadt`,type:2},{name:`Emden`,type:0}]},
                {name:`Waren`,type:0,loc:[2558,704],rule:`Niklot`,connect:[{name:`Schwerin`,type:0},{name:`Rostock`,type:0}]},
                {name:`Emden`,type:0,loc:[1067,761],rule:`Arenberg`,connect:[{name:`Oldenburg`,type:0},{name:`Jever`,type:0},{name:`Meppen`,type:0}]},
                {name:`Lüneburg`,type:0,loc:[1929,847],rule:`Welf`,connect:[{name:`Lübeck`,type:1},{name:`Schwerin`,type:1},{name:`Bremen`,type:0},{name:`Celle`,type:0},{name:`Braunschweig`,type:1},{name:`Glückstadt`,type:1}]},
                {name:`Oldenburg`,type:0,loc:[1328,892],rule:`Arenberg`,connect:[{name:`Jever`,type:0},{name:`Meppen`,type:0},{name:`Bremen`,type:0},{name:`Minden`,type:0},{name:`Emden`,type:0}]},
                {name:`Bremen`,type:0,loc:[1493,926],rule:`Ecclesiastical`,connect:[{name:`Oldenburg`,type:0},{name:`Lüneburg`,type:0},{name:`Celle`,type:0},{name:`Glückstadt`,type:0}]},
                {name:`Meppen`,type:1,loc:[1067,1094],rule:`Arenberg`,connect:[{name:`Oldenburg`,type:0},{name:`Jever`,type:0},{name:`Minden`,type:0},{name:`Emden`,type:0}]},
                {name:`Celle`,type:0,loc:[1837,1151],rule:`Welf`,connect:[{name:`Bremen`,type:0},{name:`Minden`,type:0},{name:`Hannover`,type:0},{name:`Braunschweig`,type:0},{name:`Lüneburg`,type:0}]},
                {name:`Hannover`,type:0,loc:[1749,1279],rule:`Welf`,connect:[{name:`Celle`,type:0},{name:`Braunschweig`,type:0},{name:`Goslar`,type:0},{name:`Minden`,type:0},{name:`Paderborn`,type:1}]},
                {name:`Minden`,type:0,loc:[1524,1304],rule:`Ecclesiastical`,connect:[{name:`Meppen`,type:0},{name:`Oldenburg`,type:0},{name:`Hannover`,type:0},{name:`Paderborn`,type:0},{name:`Celle`,type:0}]},
                {name:`Braunschweig`,type:2,loc:[1972,1327],rule:`Welf`,connect:[{name:`Lüneburg`,type:1},{name:`Hannover`,type:0},{name:`Goslar`,type:0},{name:`Celle`,type:0}]},
                {name:`Goslar`,type:0,loc:[1948,1491],rule:`Avesnes`,connect:[{name:`Braunschweig`,type:0},{name:`Hannover`,type:0},{name:`Kassel`,type:1},{name:`Erfurt`,type:0}]},
                {name:`Paderborn`,type:2,loc:[1472,1579],rule:`Ecclesiastical`,connect:[{name:`Minden`,type:0},{name:`Hannover`,type:1},{name:`Kassel`,type:0},{name:`Fredeburg`,type:1}]},
                {name:`Kassel`,type:0,loc:[1673,1771],rule:`Hesse`,connect:[{name:`Goslar`,type:1},{name:`Paderborn`,type:0},{name:`Fredeburg`,type:0},{name:`Gießen`,type:0},{name:`Fulda`,type:0},{name:`Erfurt`,type:1}]},
                {name:`Düsseldorf`,type:0,loc:[911,1806],rule:`Junior Wittelsbach`,connect:[{name:`Köln`,type:1},{name:`Altena`,type:0},{name:`Siegen`,type:0}]},
                {name:`Altena`,type:0,loc:[1166,1814],rule:`Hohenzollern`,connect:[{name:`Fredeburg`,type:0},{name:`Düsseldorf`,type:0}]},
                {name:`Fredeburg`,type:0,loc:[1333,1850],rule:`Ecclesiastical`,connect:[{name:`Kassel`,type:0},{name:`Paderborn`,type:1},{name:`Siegen`,type:0},{name:`Altena`,type:0}]},
                {name:`Erfurt`,type:2,loc:[2127,1950],rule:`Wettin`,connect:[{name:`Goslar`,type:0},{name:`Kassel`,type:1},{name:`Fulda`,type:1},{name:`Coburg`,type:0},{name:`Gera`,type:0}]},
                {name:`Köln`,type:2,loc:[946,1952],rule:`Junior Wittelsbach`,connect:[{name:`Koblenz`,type:0},{name:`Düsseldorf`,type:1},{name:`Lüttich`,type:1}]},
                {name:`Gera`,type:0,loc:[2431,1983],rule:`Wettin`,connect:[{name:`Erfurt`,type:0},{name:`Plauen`,type:0},{name:`Coburg`,type:0}]},
                {name:`Siegen`,type:0,loc:[1267,1989],rule:`Nassau`,connect:[{name:`Düsseldorf`,type:0},{name:`Fredeburg`,type:0},{name:`Gießen`,type:0},{name:`Koblenz`,type:0}]},
                {name:`Lüttich`,type:0,loc:[536,2083],rule:`Ecclesiastical`,connect:[{name:`Köln`,type:0},{name:`Rochefort`,type:0},{name:`Luxemburg`,type:0}]},
                {name:`Gießen`,type:0,loc:[1445,2110],rule:`Hesse`,connect:[{name:`Kassel`,type:0},{name:`Fulda`,type:0},{name:`Siegen`,type:0},{name:`Frankfurt`,type:0}]},
                {name:`Fulda`,type:0,loc:[1736,2148],rule:`Ecclesiastical`,connect:[{name:`Kassel`,type:0},{name:`Erfurt`,type:1},{name:`Coburg`,type:1},{name:`Gießen`,type:0},{name:`Schweinfurt`,type:0}]},
                {name:`Plauen`,type:0,loc:[2445,2173],rule:`Hohenzollern`,connect:[{name:`Bamberg`,type:0},{name:`Amberg`,type:0},{name:`Gera`,type:0},{name:`Nürnberg`,type:0},{name:`Eger`,type:0}]},
                {name:`Koblenz`,type:0,loc:[1119,2239],rule:`Ecclesiastical`,connect:[{name:`Köln`,type:0},{name:`Siegen`,type:0},{name:`Simmern`,type:0},{name:`Trier`,type:1},{name:`Frankfurt`,type:0}]},
                {name:`Rochefort`,type:0,loc:[461,2277],rule:`Avesnes`,connect:[{name:`Luxemburg`,type:0},{name:`Lüttich`,type:0}]},
                {name:`Coburg`,type:0,loc:[2108,2294],rule:`Wettin`,connect:[{name:`Erfurt`,type:0},{name:`Gera`,type:0},{name:`Fulda`,type:1},{name:`Bamberg`,type:0},{name:`Schweinfurt`,type:0}]},
                {name:`Frankfurt`,type:2,loc:[1448,2359],rule:`Isenberg`,connect:[{name:`Gießen`,type:0},{name:`Würzburg`,type:1},{name:`Heidelberg`,type:0},{name:`Oppenheim`,type:1},{name:`Koblenz`,type:0}]},
                {name:`Schweinfurt`,type:0,loc:[1894,2396],rule:`Bibra`,connect:[{name:`Bamberg`,type:0},{name:`Fulda`,type:0},{name:`Coburg`,type:0},{name:`Würzburg`,type:0}]},
                {name:`Simmern`,type:0,loc:[1119,2418],rule:`Elder Wittelsbach`,connect:[{name:`Koblenz`,type:0},{name:`Trier`,type:0},{name:`Oppenheim`,type:0}]},
                {name:`Bamberg`,type:0,loc:[2077,2486],rule:`Bibra`,connect:[{name:`Würzburg`,type:1},{name:`Schweinfurt`,type:0},{name:`Coburg`,type:0},{name:`Plauen`,type:0},{name:`Nürnberg`,type:0}]},
                {name:`Oppenheim`,type:0,loc:[1331,2487],rule:`Elder Wittelsbach`,connect:[{name:`Speyer`,type:0},{name:`Heidelberg`,type:1},{name:`Frankfurt`,type:1},{name:`Simmern`,type:0},{name:`Pirmasens`,type:0}]},
                {name:`Würzburg`,type:1,loc:[1812,2526],rule:`Bibra`,connect:[{name:`Bamberg`,type:1},{name:`Hall`,type:0},{name:`Frankfurt`,type:1},{name:`Nürnberg`,type:1},{name:`Schweinfurt`,type:0}]},
                {name:`Trier`,type:1,loc:[841,2527],rule:`Ecclesiastical`,connect:[{name:`Koblenz`,type:1},{name:`Simmern`,type:0},{name:`Metz`,type:0},{name:`Luxemburg`,type:1}]},
                {name:`Luxemburg`,type:0,loc:[680,2586],rule:`Elder Habsburg`,connect:[{name:`Trier`,type:1},{name:`Metz`,type:0},{name:`Rochefort`,type:0},{name:`Lüttich`,type:0}]},
                {name:`Nürnberg`,type:2,loc:[2149,2693],rule:`Hohenzollern`,connect:[{name:`Ingolstadt`,type:0},{name:`Amberg`,type:0},{name:`Hall`,type:1},{name:`Würzburg`,type:1},{name:`Bamberg`,type:0},{name:`Plauen`,type:0}]},
                {name:`Amberg`,type:0,loc:[2396,2705],rule:`Elder Wittelsbach`,connect:[{name:`Regensburg`,type:0},{name:`Ingolstadt`,type:0},{name:`Plauen`,type:0},{name:`Nürnberg`,type:0},{name:`Straubing`,type:0},{name:`Eger`,type:0}]},
                {name:`Heidelberg`,type:1,loc:[1434,2713],rule:`Elder Wittelsbach`,connect:[{name:`Frankfurt`,type:0},{name:`Stuttgart`,type:0},{name:`Speyer`,type:0},{name:`Oppenheim`,type:1}]},
                {name:`Speyer`,type:0,loc:[1355,2749],rule:`Zähringen`,connect:[{name:`Pirmasens`,type:1},{name:`Heidelberg`,type:0},{name:`Oppenheim`,type:0},{name:`Stuttgart`,type:0},{name:`Freiburg`,type:0}]},
                {name:`Metz`,type:0,loc:[680,2817],rule:`Lorraine`,connect:[{name:`Trier`,type:0},{name:`Pirmasens`,type:0},{name:`Bar`,type:1},{name:`Nanzig`,type:0},{name:`Luxemburg`,type:0}]},
                {name:`Pirmasens`,type:0,loc:[1057,2824],rule:`League of Cities`,connect:[{name:`Oppenheim`,type:0},{name:`Metz`,type:0},{name:`Speyer`,type:1},{name:`Straßburg`,type:0}]},
                {name:`Hall`,type:0,loc:[1742,2857],rule:`League of Cities`,connect:[{name:`Nürnberg`,type:1},{name:`Würzburg`,type:0},{name:`Stuttgart`,type:0},{name:`Ulm`,type:0}]},
                {name:`Regensburg`,type:1,loc:[2456,2894],rule:`Ecclesiastical`,connect:[{name:`Amberg`,type:0},{name:`Ingolstadt`,type:0},{name:`Straubing`,type:0}]},
                {name:`Straubing`,type:0,loc:[2601,2956],rule:`Ecclesiastical`,connect:[{name:`Amberg`,type:0},{name:`Regensburg`,type:0},{name:`Klattau`,type:1}]},
                {name:`Bar`,type:0,loc:[361,2975],rule:`Lillebonne`,connect:[{name:`Metz`,type:1},{name:`Spinneln`,type:1}]},
                {name:`Stuttgart`,type:0,loc:[1568,3018],rule:`Württemberg`,connect:[{name:`Heidelberg`,type:0},{name:`Speyer`,type:0},{name:`Hall`,type:0},{name:`Ulm`,type:0},{name:`Freiburg`,type:0}]},
                {name:`Nanzig`,type:2,loc:[673,3023],rule:`Lorraine`,connect:[{name:`Metz`,type:0},{name:`Spinneln`,type:0},{name:`Straßburg`,type:0}]},
                {name:`Ingolstadt`,type:0,loc:[2246,3025],rule:`Junior Wittelsbach`,connect:[{name:`Ulm`,type:0},{name:`Regensburg`,type:0},{name:`Amberg`,type:0},{name:`Nürnberg`,type:0}]},
                {name:`Straßburg`,type:0,loc:[1148,3099],rule:`League of Cities`,connect:[{name:`Nanzig`,type:0},{name:`Pirmasens`,type:0},{name:`Freiburg`,type:1},{name:`Vesoul`,type:0},{name:`Spinneln`,type:1}]},
                {name:`Ulm`,type:3,loc:[1818,3200],rule:`League of Cities`,connect:[{name:`Hall`,type:0},{name:`Stuttgart`,type:0},{name:`Ingolstadt`,type:0},{name:`Bregenz`,type:0}]},
                {name:`Spinneln`,type:0,loc:[750,3284],rule:`Lorraine`,connect:[{name:`Vesoul`,type:0},{name:`Bar`,type:1},{name:`Straßburg`,type:1},{name:`Nanzig`,type:0}]},
                {name:`Freiburg`,type:0,loc:[1176,3389],rule:`Junior Habsburg`,connect:[{name:`Speyer`,type:0},{name:`Straßburg`,type:1},{name:`Stuttgart`,type:0},{name:`Konstanz`,type:0},{name:`Solothurn`,type:1}]},
                {name:`Vesoul`,type:0,loc:[632,3550],rule:`Elder Habsburg`,connect:[{name:`Spinneln`,type:0},{name:`Straßburg`,type:0},{name:`Bisanz`,type:0}]},
                {name:`Konstanz`,type:2,loc:[1562,3554],rule:`Junior Habsburg`,connect:[{name:`Freiburg`,type:0},{name:`Bregenz`,type:0},{name:`Herisau`,type:0}]},
                {name:`Bregenz`,type:0,loc:[1756,3640],rule:`Junior Habsburg`,connect:[{name:`Ulm`,type:0},{name:`Konstanz`,type:0},{name:`Herisau`,type:1},{name:`Davos`,type:0}]},
                {name:`Herisau`,type:0,loc:[1589,3710],rule:`Schwyz`,connect:[{name:`Bregenz`,type:1},{name:`Konstanz`,type:0},{name:`Davos`,type:1},{name:`Solothurn`,type:1}]},
                {name:`Bisanz`,type:2,loc:[588,3728],rule:`Elder Habsburg`,connect:[{name:`Vesoul`,type:0},{name:`Solothurn`,type:1}]},
                {name:`Solothurn`,type:0,loc:[1068,3774],rule:`Junior Habsburg`,connect:[{name:`Bisanz`,type:1},{name:`Herisau`,type:1},{name:`Freiburg`,type:1}]},
                {name:`Davos`,type:0,loc:[1749,3978],rule:`Two Leagues`,connect:[{name:`Bregenz`,type:0},{name:`Herisau`,type:1}]},
                {name:`Reichenberg`,type:0,loc:[3290,2024],rule:`Přemyslid`,connect:[{name:`Leitmeritz`,type:0},{name:`Jitschin`,type:0},{name:`Prag`,type:1}]},
                {name:`Leitmeritz`,type:0,loc:[3014,2151],rule:`Přemyslid`,connect:[{name:`Prag`,type:0},{name:`Reichenberg`,type:0},{name:`Saaz`,type:0}]},
                {name:`Jitschin`,type:0,loc:[3392,2178],rule:`Přemyslid`,connect:[{name:`Kuttenberg`,type:1},{name:`Reichenberg`,type:0},{name:`Königgrätz`,type:0}]},
                {name:`Saaz`,type:0,loc:[2868,2255],rule:`Přemyslid`,connect:[{name:`Pilsen`,type:0},{name:`Eger`,type:0},{name:`Leitmeritz`,type:0}]},
                {name:`Königgrätz`,type:0,loc:[3542,2276],rule:`Přemyslid`,connect:[{name:`Jitschin`,type:0},{name:`Kuttenberg`,type:0}]},
                {name:`Prag`,type:1,loc:[3134,2370],rule:`Přemyslid`,connect:[{name:`Leitmeritz`,type:0},{name:`Reichenberg`,type:1},{name:`Kuttenberg`,type:0},{name:`Tabor`,type:0},{name:`Pilsen`,type:1}]},
                {name:`Eger`,type:0,loc:[2522,2380],rule:`Přemyslid`,connect:[{name:`Saaz`,type:0},{name:`Pilsen`,type:0},{name:`Amberg`,type:0},{name:`Plauen`,type:0}]},
                {name:`Kuttenberg`,type:0,loc:[3381,2412],rule:`Přemyslid`,connect:[{name:`Königgrätz`,type:0},{name:`Tabor`,type:0},{name:`Prag`,type:0},{name:`Jitschin`,type:1}]},
                {name:`Pilsen`,type:0,loc:[2820,2528],rule:`Přemyslid`,connect:[{name:`Saaz`,type:0},{name:`Eger`,type:0},{name:`Klattau`,type:1},{name:`Prag`,type:1}]},
                {name:`Tabor`,type:2,loc:[3225,2675],rule:`Přemyslid`,connect:[{name:`Kuttenberg`,type:0},{name:`Prag`,type:0},{name:`Budweis`,type:0}]},
                {name:`Klattau`,type:0,loc:[2813,2708],rule:`Přemyslid`,connect:[{name:`Pilsen`,type:1},{name:`Budweis`,type:0},{name:`Straubing`,type:0}]},
                {name:`Budweis`,type:0,loc:[3181,2891],rule:`Přemyslid`,connect:[{name:`Tabor`,type:0},{name:`Klattau`,type:0}]},
            ],team:[
                {name:`Wiemken`,term:`wiemken`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Isenberg`,term:`isenberg`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Nassau`,term:`nassau`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Zähringen`,term:`baden`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Ascania`,term:`ascania`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Schwyz`,term:`schwyz`,type:`Rural`,allies:[`Two Leagues`],quality:1.1,chance:0.5},
                {name:`Two Leagues`,term:`two leagues`,type:`Rural`,allies:[`Schwyz`],quality:1,chance:0.5},
                {name:`Lillebonne`,term:`lillebonne`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Württemberg`,term:`wurttemberg`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Avesnes`,term:`avesnes`,type:`Minor Nobility`,allies:[],quality:1,chance:1},
                {name:`Hesse`,term:`hesse`,type:`Middle Nobility`,allies:[],quality:1,chance:1},
                {name:`Arenberg`,term:`arenberg`,type:`Middle Nobility`,allies:[],quality:1,chance:1},
                {name:`Niklot`,term:`niklot`,type:`Middle Nobility`,allies:[],quality:1,chance:1},
                {name:`Bibra`,term:`bibra`,type:`Middle Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Hohenzollern`,term:`hohenzollern`,type:`Middle Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Ecclesiastical`,term:`ecclesiastical`,type:`Major Nobility`,allies:[],quality:0.9,chance:1.5},
                {name:`League of Cities`,term:`league of cities`,type:`Urban`,allies:[],quality:0.9,chance:1.5},
                {name:`Lorraine`,term:`lorraine`,type:`Middle Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Welf`,term:`welf`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Wettin`,term:`wettin`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Elder Habsburg`,term:`elder habsburg`,type:`Major Nobility`,allies:[`Junior Habsburg`],quality:1,chance:1.5},
                {name:`Junior Habsburg`,term:`junior habsburg`,type:`Major Nobility`,allies:[`Elder Habsburg`],quality:1,chance:1.5},
                {name:`Elder Wittelsbach`,term:`elder wittelsbach`,type:`Major Nobility`,allies:[`Junior Wittelsbach`],quality:1,chance:1.5},
                {name:`Junior Wittelsbach`,term:`junior wittelsbach`,type:`Major Nobility`,allies:[`Elder Wittelsbach`],quality:1,chance:1.5},
                {name:`Přemyslid`,term:`premyslid`,type:`Massive Nobility`,allies:[],quality:1,chance:5},
            ],
        },{
            name:[`Kingdom of Arles`,`Base`],
            term:`arelat`,
            stack:false,
            teamSet:3,
            constants:{spawn:{base:2500,spend:1000,regen:15,garrison:500}},
            city:[
                {name:`Basel`,type:0,loc:[1651,791],rule:`Ecclesiastical`,connect:[{name:`Aarau`,type:0},{name:`Montbéliard`,type:0},{name:`Bern`,type:0},{name:`Neuchâtel`,type:0}]},
                {name:`Vesoul`,type:0,loc:[1137,804],rule:`Andechs`,connect:[{name:`Montbéliard`,type:0},{name:`Dole`,type:0},{name:`Besançon`,type:0}]},
                {name:`Montbéliard`,type:0,loc:[1379,833],rule:`Württemberg`,connect:[{name:`Vesoul`,type:0},{name:`Basel`,type:0}]},
                {name:`Aarau`,type:0,loc:[1823,861],rule:`Habsburg`,connect:[{name:`Bern`,type:0},{name:`Basel`,type:0},{name:`Stans`,type:0}]},
                {name:`Besançon`,type:1,loc:[1117,1018],rule:`Ecclesiastical`,connect:[{name:`Neuchâtel`,type:1},{name:`Lons`,type:0},{name:`Dole`,type:0},{name:`Vesoul`,type:0}]},
                {name:`Stans`,type:0,loc:[1960,1086],rule:`Unterwalden`,connect:[{name:`Aarau`,type:0},{name:`Thun`,type:0}]},
                {name:`Dole`,type:1,loc:[925,1106],rule:`Andechs`,connect:[{name:`Vesoul`,type:0},{name:`Lons`,type:0},{name:`Besançon`,type:0}]},
                {name:`Neuchâtel`,type:0,loc:[1442,1108],rule:`Hohenzollern`,connect:[{name:`Besançon`,type:1},{name:`Basel`,type:0},{name:`Lausanne`,type:0},{name:`Bern`,type:0}]},
                {name:`Bern`,type:2,loc:[1647,1127],rule:`Zähringen`,connect:[{name:`Basel`,type:0},{name:`Aarau`,type:0},{name:`Thun`,type:0},{name:`Neuchâtel`,type:0}]},
                {name:`Thun`,type:0,loc:[1707,1222],rule:`Zähringen`,connect:[{name:`Stans`,type:0},{name:`Bern`,type:0},{name:`Lausanne`,type:0},{name:`Sion`,type:0}]},
                {name:`Lons`,type:0,loc:[998,1338],rule:`Andechs`,connect:[{name:`Dole`,type:0},{name:`Besançon`,type:0},{name:`Lausanne`,type:0},{name:`Bourg`,type:0},{name:`Geneva`,type:0}]},
                {name:`Lausanne`,type:0,loc:[1362,1382],rule:`Savoy`,connect:[{name:`Lons`,type:0},{name:`Thun`,type:0},{name:`Neuchâtel`,type:0},{name:`Geneva`,type:0},{name:`Sion`,type:0}]},
                {name:`Sion`,type:0,loc:[1647,1517],rule:`Valais`,connect:[{name:`Thun`,type:0},{name:`Lausanne`,type:0},{name:`Geneva`,type:1},{name:`Chamonix`,type:0}]},
                {name:`Bourg`,type:0,loc:[875,1562],rule:`Arduinici`,connect:[{name:`Lons`,type:0},{name:`Geneva`,type:1},{name:`Colombier`,type:1},{name:`Lyon`,type:0}]},
                {name:`Geneva`,type:3,loc:[1210,1585],rule:`Geneva`,connect:[{name:`Bourg`,type:1},{name:`Lons`,type:0},{name:`Lausanne`,type:0},{name:`Sion`,type:1},{name:`Chambéry`,type:0}]},
                {name:`Chamonix`,type:0,loc:[1474,1700],rule:`Savoy`,connect:[{name:`Sion`,type:0},{name:`Moustier`,type:0}]},
                {name:`Lyon`,type:2,loc:[759,1810],rule:`Ecclesiastical`,connect:[{name:`Feurs`,type:0},{name:`Vienne`,type:0},{name:`Colombier`,type:0},{name:`Bourg`,type:0}]},
                {name:`Colombier`,type:0,loc:[883,1854],rule:`Arduinici`,connect:[{name:`Bourg`,type:1},{name:`Lyon`,type:0},{name:`Chambéry`,type:0},{name:`Vienne`,type:0},{name:`Grenoble`,type:0}]},
                {name:`Feurs`,type:0,loc:[551,1866],rule:`Albon`,connect:[{name:`Lyon`,type:0},{name:`Vienne`,type:0}]},
                {name:`Chambéry`,type:0,loc:[1169,1880],rule:`Savoy`,connect:[{name:`Moustier`,type:1},{name:`Geneva`,type:0},{name:`Grenoble`,type:0},{name:`Colombier`,type:0}]},
                {name:`Moustier`,type:0,loc:[1381,1900],rule:`Ecclesiastical`,connect:[{name:`Chamonix`,type:0},{name:`Chambéry`,type:1},{name:`Briançon`,type:0}]},
                {name:`Vienne`,type:1,loc:[777,1947],rule:`Ecclesiastical`,connect:[{name:`Feurs`,type:0},{name:`Albon`,type:0},{name:`Lyon`,type:0},{name:`Colombier`,type:0}]},
                {name:`Grenoble`,type:1,loc:[1111,2066],rule:`Albon`,connect:[{name:`Colombier`,type:0},{name:`Chambéry`,type:0},{name:`Gap`,type:0},{name:`Die`,type:0},{name:`Albon`,type:1}]},
                {name:`Albon`,type:0,loc:[811,2114],rule:`Albon`,connect:[{name:`Vienne`,type:0},{name:`Grenoble`,type:1},{name:`Valence`,type:1}]},
                {name:`Briançon`,type:0,loc:[1465,2209],rule:`Savoy`,connect:[{name:`Moustier`,type:0},{name:`Gap`,type:0},{name:`Barcelonette`,type:0}]},
                {name:`Valence`,type:0,loc:[808,2246],rule:`Rouergue`,connect:[{name:`Viviers`,type:0},{name:`Die`,type:0},{name:`Albon`,type:1}]},
                {name:`Die`,type:0,loc:[1002,2321],rule:`Rouergue`,connect:[{name:`Grenoble`,type:0},{name:`Gap`,type:0},{name:`Nyons`,type:0},{name:`Valence`,type:0}]},
                {name:`Gap`,type:0,loc:[1287,2411],rule:`Sabran`,connect:[{name:`Briançon`,type:0},{name:`Barcelonette`,type:1},{name:`Forcalquier`,type:0},{name:`Die`,type:0},{name:`Grenoble`,type:0}]},
                {name:`Barcelonette`,type:2,loc:[1483,2468],rule:`Savoy`,connect:[{name:`Briançon`,type:0},{name:`Gap`,type:1},{name:`Glandèves`,type:0},{name:`Nice`,type:0}]},
                {name:`Viviers`,type:0,loc:[754,2495],rule:`Ecclesiastical`,connect:[{name:`Nyons`,type:0},{name:`Valence`,type:0},{name:`Avignon`,type:1}]},
                {name:`Nyons`,type:0,loc:[931,2555],rule:`Rouergue`,connect:[{name:`Die`,type:0},{name:`Viviers`,type:0},{name:`Avignon`,type:0},{name:`Forcalquier`,type:0}]},
                {name:`Glandèves`,type:0,loc:[1585,2708],rule:`Barcelona`,connect:[{name:`Draguignan`,type:0},{name:`Nice`,type:0},{name:`Barcelonette`,type:0}]},
                {name:`Forcalquier`,type:0,loc:[1212,2749],rule:`Sabran`,connect:[{name:`Gap`,type:0},{name:`Nyons`,type:0},{name:`Aix`,type:1},{name:`Draguignan`,type:1}]},
                {name:`Avignon`,type:0,loc:[842,2785],rule:`Rouergue`,connect:[{name:`Viviers`,type:1},{name:`Nyons`,type:0},{name:`Arles`,type:0},{name:`Aix`,type:1}]},
                {name:`Nice`,type:0,loc:[1794,2806],rule:`Savoy`,connect:[{name:`Fréjus`,type:0},{name:`Barcelonette`,type:0},{name:`Glandèves`,type:0}]},
                {name:`Draguignan`,type:0,loc:[1504,2921],rule:`Barcelona`,connect:[{name:`Fréjus`,type:0},{name:`Toulon`,type:1},{name:`Glandèves`,type:0},{name:`Forcalquier`,type:1}]},
                {name:`Arles`,type:4,loc:[796,2930],rule:`Ecclesiastical`,connect:[{name:`Avignon`,type:0},{name:`Aix`,type:0}]},
                {name:`Fréjus`,type:0,loc:[1611,2974],rule:`Barcelona`,connect:[{name:`Toulon`,type:0},{name:`Nice`,type:0},{name:`Draguignan`,type:0}]},
                {name:`Aix`,type:1,loc:[1116,2993],rule:`Barcelona`,connect:[{name:`Arles`,type:0},{name:`Avignon`,type:1},{name:`Toulon`,type:0},{name:`Forcalquier`,type:1}]},
                {name:`Toulon`,type:0,loc:[1327,3157],rule:`Barcelona`,connect:[{name:`Fréjus`,type:0},{name:`Draguignan`,type:1},{name:`Aix`,type:0}]},
            ],team:[
                {name:`Unterwalden`,term:`unterwalden`,type:`Rural`,allies:[`Valais`],quality:1.1,chance:0.5},
                {name:`Valais`,term:`valais`,type:`Rural`,allies:[`Unterwalden`],quality:1,chance:0.5},
                {name:`Geneva`,term:`geneva`,type:`Urban`,allies:[],quality:1,chance:0.5},
                {name:`Hohenzollern`,term:`hohenzollern`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Württemberg`,term:`wurttemberg`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Sabran`,term:`sabran`,type:`Minor Nobility`,allies:[],quality:1,chance:1},
                {name:`Habsburg`,term:`junior habsburg`,type:`Middle Nobility`,allies:[`Zähringen`],quality:1,chance:0.5},
                {name:`Zähringen`,term:`zahringen`,type:`Middle Nobility`,allies:[`Habsburg`],quality:1,chance:1},
                {name:`Arduinici`,term:`arduinici`,type:`Minor Nobility`,allies:[],quality:1,chance:1},
                {name:`Albon`,term:`albon`,type:`Middle Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Andechs`,term:`andechs`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Ecclesiastical`,term:`ecclesiastical2`,type:`Major Nobility`,allies:[],quality:0.9,chance:1.5},
                {name:`Rouergue`,term:`rouergue`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Barcelona`,term:`barcelona`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Savoy`,term:`savoy`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
            ],
        },{
            name:[`Kingdom of Arles`,`+ Vosges`],
            term:`arelat+-`,
            stack:true,
            teamSet:3,
            constants:{spawn:{base:2500,spend:1000,regen:12,garrison:500}},
            city:[
                {name:`Toul`,type:0,loc:[1002,639],rule:`Lillebonne`,connect:[{name:`Épinal`,type:0},{name:`Lamarche`,type:0},{name:`Lunéville`,type:1}]},
                {name:`Lunéville`,type:0,loc:[1210,661],rule:`Lorraine`,connect:[{name:`Épinal`,type:0},{name:`Toul`,type:1}]},
                {name:`Épinal`,type:0,loc:[1226,891],rule:`Lorraine`,connect:[{name:`Toul`,type:0},{name:`Colmar`,type:1},{name:`Vesoul`,type:0},{name:`Belfort`,type:0},{name:`Lunéville`,type:0}]},
                {name:`Colmar`,type:0,loc:[1530,902],rule:`League of Cities`,connect:[{name:`Épinal`,type:1},{name:`Belfort`,type:0}]},
                {name:`Lamarche`,type:0,loc:[943,961],rule:`Lorraine`,connect:[{name:`Toul`,type:0},{name:`Vesoul`,type:1}]},
                {name:`Belfort`,type:0,loc:[1394,1147],rule:`Habsburg`,connect:[{name:`Épinal`,type:0},{name:`Colmar`,type:0},{name:`Basel`,type:0},{name:`Vesoul`,type:0}]},
                {name:`Basel`,type:0,loc:[1651,1191],rule:`Ecclesiastical`,connect:[{name:`Aarau`,type:0},{name:`Belfort`,type:0},{name:`Bern`,type:0},{name:`Neuchâtel`,type:0}]},
                {name:`Vesoul`,type:0,loc:[1137,1204],rule:`Andechs`,connect:[{name:`Épinal`,type:0},{name:`Belfort`,type:0},{name:`Dole`,type:0},{name:`Besançon`,type:0},{name:`Lamarche`,type:1},{name:`Pontarlier`,type:1}]},
                {name:`Aarau`,type:0,loc:[1823,1261],rule:`Habsburg`,connect:[{name:`Bern`,type:0},{name:`Basel`,type:0},{name:`Altdorf`,type:0}]},
                {name:`Besançon`,type:1,loc:[1117,1418],rule:`Ecclesiastical`,connect:[{name:`Pontarlier`,type:0},{name:`Lons`,type:0},{name:`Dole`,type:0},{name:`Vesoul`,type:0}]},
                {name:`Dole`,type:1,loc:[925,1506],rule:`Andechs`,connect:[{name:`Vesoul`,type:0},{name:`Lons`,type:0},{name:`Besançon`,type:0}]},
                {name:`Neuchâtel`,type:0,loc:[1442,1508],rule:`Hohenzollern`,connect:[{name:`Pontarlier`,type:0},{name:`Basel`,type:0},{name:`Lausanne`,type:0},{name:`Bern`,type:0}]},
                {name:`Altdorf`,type:0,loc:[2066,1512],rule:`Schwyz`,connect:[{name:`Aarau`,type:0},{name:`Thun`,type:0},{name:`Visp`,type:0}]},
                {name:`Bern`,type:1,loc:[1647,1527],rule:`Zähringen`,connect:[{name:`Basel`,type:0},{name:`Aarau`,type:0},{name:`Thun`,type:0},{name:`Neuchâtel`,type:0}]},
                {name:`Pontarlier`,type:0,loc:[1259,1558],rule:`Andechs`,connect:[{name:`Neuchâtel`,type:0},{name:`Besançon`,type:0},{name:`Vesoul`,type:1},{name:`Lons`,type:0}]},
                {name:`Thun`,type:0,loc:[1707,1622],rule:`Zähringen`,connect:[{name:`Altdorf`,type:0},{name:`Bern`,type:0},{name:`Lausanne`,type:0},{name:`Visp`,type:0}]},
                {name:`Lons`,type:0,loc:[998,1738],rule:`Andechs`,connect:[{name:`Dole`,type:0},{name:`Besançon`,type:0},{name:`Lausanne`,type:0},{name:`Bourg`,type:0},{name:`Geneva`,type:0},{name:`Pontarlier`,type:0}]},
                {name:`Lausanne`,type:0,loc:[1362,1782],rule:`Savoy`,connect:[{name:`Lons`,type:0},{name:`Thun`,type:0},{name:`Neuchâtel`,type:0},{name:`Geneva`,type:0},{name:`Sion`,type:0}]},
                {name:`Visp`,type:0,loc:[1837,1866],rule:`Valais`,connect:[{name:`Thun`,type:0},{name:`Altdorf`,type:0},{name:`Sion`,type:0}]},
                {name:`Sion`,type:0,loc:[1647,1917],rule:`Ecclesiastical`,connect:[{name:`Visp`,type:0},{name:`Lausanne`,type:0},{name:`Geneva`,type:1},{name:`Chamonix`,type:0}]},
                {name:`Bourg`,type:0,loc:[875,1962],rule:`Arduinici`,connect:[{name:`Lons`,type:0},{name:`Geneva`,type:1},{name:`Colombier`,type:1},{name:`Lyon`,type:0}]},
                {name:`Geneva`,type:3,loc:[1210,1985],rule:`Geneva`,connect:[{name:`Bourg`,type:1},{name:`Lons`,type:0},{name:`Lausanne`,type:0},{name:`Sion`,type:1},{name:`Annecy`,type:0}]},
                {name:`Annecy`,type:0,loc:[1226,2099],rule:`Thoire`,connect:[{name:`Geneva`,type:0},{name:`Moustier`,type:0},{name:`Chambéry`,type:0}]},
                {name:`Chamonix`,type:0,loc:[1474,2100],rule:`Savoy`,connect:[{name:`Sion`,type:0},{name:`Moustier`,type:0}]},
                {name:`Lyon`,type:2,loc:[759,2210],rule:`Ecclesiastical`,connect:[{name:`Feurs`,type:0},{name:`Vienne`,type:0},{name:`Colombier`,type:0},{name:`Bourg`,type:0}]},
                {name:`Colombier`,type:0,loc:[883,2254],rule:`Arduinici`,connect:[{name:`Bourg`,type:1},{name:`Lyon`,type:0},{name:`Chambéry`,type:0},{name:`Vienne`,type:0},{name:`Grenoble`,type:0}]},
                {name:`Feurs`,type:0,loc:[551,2266],rule:`Albon`,connect:[{name:`Lyon`,type:0},{name:`Vienne`,type:0}]},
                {name:`Chambéry`,type:0,loc:[1169,2280],rule:`Savoy`,connect:[{name:`Moustier`,type:1},{name:`Annecy`,type:0},{name:`Grenoble`,type:0},{name:`Colombier`,type:0}]},
                {name:`Moustier`,type:0,loc:[1381,2300],rule:`Ecclesiastical`,connect:[{name:`Chamonix`,type:0},{name:`Chambéry`,type:1},{name:`Briançon`,type:0},{name:`Annecy`,type:0}]},
                {name:`Vienne`,type:1,loc:[777,2347],rule:`Ecclesiastical`,connect:[{name:`Feurs`,type:0},{name:`Albon`,type:0},{name:`Lyon`,type:0},{name:`Colombier`,type:0}]},
                {name:`Grenoble`,type:1,loc:[1111,2466],rule:`Albon`,connect:[{name:`Colombier`,type:0},{name:`Chambéry`,type:0},{name:`St. Bonet`,type:0},{name:`Die`,type:0},{name:`Albon`,type:1}]},
                {name:`Albon`,type:0,loc:[811,2514],rule:`Albon`,connect:[{name:`Vienne`,type:0},{name:`Grenoble`,type:1},{name:`Valence`,type:1}]},
                {name:`Briançon`,type:0,loc:[1465,2609],rule:`Savoy`,connect:[{name:`Moustier`,type:0},{name:`St. Bonet`,type:0},{name:`Barcelonette`,type:0}]},
                {name:`Valence`,type:0,loc:[808,2646],rule:`Rouergue`,connect:[{name:`Viviers`,type:0},{name:`Die`,type:0},{name:`Albon`,type:1}]},
                {name:`St. Bonet`,type:0,loc:[1264,2686],rule:`Albon`,connect:[{name:`Briançon`,type:0},{name:`Gap`,type:0},{name:`Grenoble`,type:0}]},
                {name:`Die`,type:0,loc:[1002,2721],rule:`Rouergue`,connect:[{name:`Grenoble`,type:0},{name:`Gap`,type:0},{name:`Nyons`,type:0},{name:`Valence`,type:0}]},
                {name:`Gap`,type:0,loc:[1287,2811],rule:`Sabran`,connect:[{name:`Barcelonette`,type:1},{name:`Forcalquier`,type:0},{name:`Die`,type:0},{name:`St. Bonet`,type:0}]},
                {name:`Barcelonette`,type:2,loc:[1483,2868],rule:`Savoy`,connect:[{name:`Briançon`,type:0},{name:`Gap`,type:1},{name:`Glandèves`,type:0},{name:`Nice`,type:0}]},
                {name:`Viviers`,type:0,loc:[754,2895],rule:`Ecclesiastical`,connect:[{name:`Nyons`,type:0},{name:`Valence`,type:0},{name:`Avignon`,type:1}]},
                {name:`Nyons`,type:0,loc:[931,2955],rule:`Rouergue`,connect:[{name:`Die`,type:0},{name:`Viviers`,type:0},{name:`Avignon`,type:0},{name:`Forcalquier`,type:0}]},
                {name:`Glandèves`,type:0,loc:[1585,3108],rule:`Barcelona`,connect:[{name:`Draguignan`,type:0},{name:`Nice`,type:0},{name:`Barcelonette`,type:0}]},
                {name:`Forcalquier`,type:0,loc:[1212,3149],rule:`Sabran`,connect:[{name:`Gap`,type:0},{name:`Nyons`,type:0},{name:`Aix`,type:1},{name:`Draguignan`,type:1}]},
                {name:`Avignon`,type:0,loc:[842,3185],rule:`Rouergue`,connect:[{name:`Viviers`,type:1},{name:`Nyons`,type:0},{name:`Arles`,type:0},{name:`Aix`,type:1}]},
                {name:`Nice`,type:0,loc:[1794,3206],rule:`Savoy`,connect:[{name:`Fréjus`,type:0},{name:`Barcelonette`,type:0},{name:`Glandèves`,type:0},{name:`Marseille`,type:2}]},
                {name:`Draguignan`,type:0,loc:[1504,3321],rule:`Barcelona`,connect:[{name:`Fréjus`,type:0},{name:`Toulon`,type:1},{name:`Glandèves`,type:0},{name:`Forcalquier`,type:1}]},
                {name:`Arles`,type:1,loc:[796,3330],rule:`Ecclesiastical`,connect:[{name:`Avignon`,type:0},{name:`Aix`,type:0}]},
                {name:`Fréjus`,type:0,loc:[1611,3374],rule:`Barcelona`,connect:[{name:`Toulon`,type:0},{name:`Nice`,type:0},{name:`Draguignan`,type:0}]},
                {name:`Aix`,type:1,loc:[1116,3393],rule:`Barcelona`,connect:[{name:`Arles`,type:0},{name:`Marseille`,type:0},{name:`Avignon`,type:1},{name:`Toulon`,type:0},{name:`Forcalquier`,type:1}]},
                {name:`Marseille`,type:0,loc:[1099,3486],rule:`Barcelona`,connect:[{name:`Aix`,type:0},{name:`Toulon`,type:0},{name:`Nice`,type:2}]},
                {name:`Toulon`,type:0,loc:[1327,3557],rule:`Barcelona`,connect:[{name:`Fréjus`,type:0},{name:`Draguignan`,type:1},{name:`Aix`,type:0},{name:`Marseille`,type:0}]},
            ],team:[
                {name:`League of Cities`,term:`league of cities3`,type:`Urban`,allies:[],quality:0.9,chance:0.5},
                {name:`Schwyz`,term:`schwyz`,type:`Rural`,allies:[`Valais`],quality:1.1,chance:0.5},
                {name:`Valais`,term:`valais`,type:`Rural`,allies:[`Schwyz`],quality:1,chance:0.5},
                {name:`Lillebonne`,term:`lillebonne`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Geneva`,term:`geneva`,type:`Urban`,allies:[`Thoire`],quality:1,chance:0.5},
                {name:`Thoire`,term:`genevois`,type:`Minor Nobility`,allies:[`Geneva`],quality:1,chance:0.5},
                {name:`Hohenzollern`,term:`hohenzollern`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Habsburg`,term:`junior habsburg`,type:`Minor Nobility`,allies:[`Zähringen`],quality:1,chance:0.5},
                {name:`Zähringen`,term:`zahringen`,type:`Minor Nobility`,allies:[`Habsburg`],quality:1,chance:1},
                {name:`Sabran`,term:`sabran`,type:`Minor Nobility`,allies:[],quality:1,chance:1},
                {name:`Arduinici`,term:`arduinici`,type:`Minor Nobility`,allies:[],quality:1,chance:1},
                {name:`Lorraine`,term:`lorraine`,type:`Middle Nobility`,allies:[],quality:1,chance:1},
                {name:`Albon`,term:`albon`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Andechs`,term:`andechs`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Ecclesiastical`,term:`ecclesiastical2`,type:`Major Nobility`,allies:[],quality:0.9,chance:1.5},
                {name:`Rouergue`,term:`rouergue`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Barcelona`,term:`barcelona`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Savoy`,term:`savoy`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
            ],
        },{
            name:[`Arelatisches Reich`],
            term:`arelat+`,
            stack:false,
            teamSet:3,
            constants:{spawn:{base:2500,spend:1000,regen:10,garrison:500}},
            city:[
                {name:`Koblenz`,type:0,loc:[1483,474],rule:`Ecclesiastical`,connect:[{name:`Cochem`,type:0},{name:`Simmern`,type:0}]},
                {name:`Cochem`,type:0,loc:[1312,570],rule:`Ecclesiastical`,connect:[{name:`Simmern`,type:1},{name:`Koblenz`,type:0},{name:`Trier`,type:1}]},
                {name:`Simmern`,type:0,loc:[1511,674],rule:`Wittelsbach`,connect:[{name:`Koblenz`,type:0},{name:`Cochem`,type:1},{name:`Alzey`,type:0}]},
                {name:`Alzey`,type:0,loc:[1689,778],rule:`Wittelsbach`,connect:[{name:`Simmern`,type:0},{name:`Kaiserslautern`,type:0},{name:`Heidelberg`,type:1}]},
                {name:`Trier`,type:1,loc:[1212,832],rule:`Ecclesiastical`,connect:[{name:`Cochem`,type:1},{name:`Kaiserslautern`,type:0},{name:`Metz`,type:0}]},
                {name:`Heidelberg`,type:0,loc:[1913,951],rule:`Wittelsbach`,connect:[{name:`Alzey`,type:1},{name:`Kaiserslautern`,type:1},{name:`Speyer`,type:0},{name:`Stuttgart`,type:0}]},
                {name:`Kaiserslautern`,type:0,loc:[1589,954],rule:`Wittelsbach`,connect:[{name:`Heidelberg`,type:1},{name:`Speyer`,type:0},{name:`Alzey`,type:0},{name:`Trier`,type:0},{name:`Saarbrücken`,type:0},{name:`Pirmasens`,type:0}]},
                {name:`Speyer`,type:0,loc:[1833,1002],rule:`Ecclesiastical`,connect:[{name:`Heidelberg`,type:0},{name:`Kaiserslautern`,type:0},{name:`Baden`,type:0}]},
                {name:`Saarbrücken`,type:0,loc:[1341,1097],rule:`Wittelsbach`,connect:[{name:`Kaiserslautern`,type:0},{name:`Pirmasens`,type:0},{name:`Saarburg`,type:0},{name:`Metz`,type:0}]},
                {name:`Pirmasens`,type:0,loc:[1561,1101],rule:`Isenberg`,connect:[{name:`Kaiserslautern`,type:0},{name:`Saarbrücken`,type:0},{name:`Straßburg`,type:0}]},
                {name:`Metz`,type:0,loc:[1077,1186],rule:`Ecclesiastical`,connect:[{name:`Saarbrücken`,type:0},{name:`Trier`,type:0},{name:`Nancy`,type:0},{name:`Verdun`,type:0},{name:`Toul`,type:1}]},
                {name:`Verdun`,type:2,loc:[795,1189],rule:`Ecclesiastical`,connect:[{name:`Metz`,type:0},{name:`Bar`,type:0}]},
                {name:`Stuttgart`,type:1,loc:[2118,1253],rule:`Württemberg`,connect:[{name:`Heidelberg`,type:0},{name:`Baden`,type:0},{name:`Freudenstadt`,type:0},{name:`Urach`,type:1}]},
                {name:`Baden`,type:0,loc:[1800,1313],rule:`Baden`,connect:[{name:`Speyer`,type:0},{name:`Stuttgart`,type:0},{name:`Freudenstadt`,type:0},{name:`Straßburg`,type:0}]},
                {name:`Saarburg`,type:0,loc:[1389,1371],rule:`Lorraine`,connect:[{name:`Straßburg`,type:0},{name:`Saarbrücken`,type:0},{name:`Nancy`,type:0},{name:`Épinal`,type:1}]},
                {name:`Urach`,type:0,loc:[2216,1405],rule:`Württemberg`,connect:[{name:`Stuttgart`,type:1},{name:`Sigmaringen`,type:0}]},
                {name:`Bar`,type:0,loc:[740,1407],rule:`Lillebonne`,connect:[{name:`Verdun`,type:0},{name:`Toul`,type:1}]},
                {name:`Nancy`,type:1,loc:[1100,1415],rule:`Lorraine`,connect:[{name:`Metz`,type:0},{name:`Toul`,type:0},{name:`Saarburg`,type:0},{name:`Épinal`,type:0}]},
                {name:`Straßburg`,type:0,loc:[1646,1417],rule:`League of Cities`,connect:[{name:`Baden`,type:0},{name:`Colmar`,type:0},{name:`Pirmasens`,type:0},{name:`Saarburg`,type:0}]},
                {name:`Toul`,type:0,loc:[1002,1439],rule:`Ecclesiastical`,connect:[{name:`Épinal`,type:0},{name:`Nancy`,type:0},{name:`Bar`,type:1},{name:`Metz`,type:1}]},
                {name:`Freudenstadt`,type:0,loc:[1923,1476],rule:`Württemberg`,connect:[{name:`Stuttgart`,type:0},{name:`Baden`,type:0},{name:`Freiburg`,type:0},{name:`Sigmaringen`,type:1}]},
                {name:`Sigmaringen`,type:0,loc:[2171,1626],rule:`Hohenzollern`,connect:[{name:`Urach`,type:0},{name:`Freudenstadt`,type:1},{name:`Konstanz`,type:2},{name:`Memmingen`,type:1},{name:`Schaffhausen`,type:0}]},
                {name:`Memmingen`,type:0,loc:[2524,1652],rule:`League of Cities`,connect:[{name:`Sigmaringen`,type:1},{name:`Bregenz`,type:0}]},
                {name:`Épinal`,type:0,loc:[1226,1691],rule:`Lorraine`,connect:[{name:`Toul`,type:0},{name:`Nancy`,type:0},{name:`Saarburg`,type:1},{name:`Colmar`,type:1},{name:`Vesoul`,type:0},{name:`Belfort`,type:0}]},
                {name:`Colmar`,type:0,loc:[1530,1702],rule:`League of Cities`,connect:[{name:`Straßburg`,type:0},{name:`Freiburg`,type:1},{name:`Épinal`,type:1},{name:`Belfort`,type:0}]},
                {name:`Freiburg`,type:0,loc:[1725,1740],rule:`Habsburg`,connect:[{name:`Basel`,type:0},{name:`Colmar`,type:1},{name:`Freudenstadt`,type:0},{name:`Schaffhausen`,type:0}]},
                {name:`Schaffhausen`,type:0,loc:[2005,1870],rule:`Kyburg`,connect:[{name:`Freiburg`,type:0},{name:`Aarau`,type:1},{name:`Sigmaringen`,type:0},{name:`Konstanz`,type:0}]},
                {name:`Konstanz`,type:2,loc:[2202,1870],rule:`Kyburg`,connect:[{name:`Bregenz`,type:2},{name:`Sigmaringen`,type:2},{name:`Schaffhausen`,type:0},{name:`Herisau`,type:0}]},
                {name:`Bregenz`,type:0,loc:[2422,1928],rule:`Habsburg`,connect:[{name:`Memmingen`,type:0},{name:`Konstanz`,type:2},{name:`Herisau`,type:1}]},
                {name:`Belfort`,type:0,loc:[1394,1947],rule:`Habsburg`,connect:[{name:`Épinal`,type:0},{name:`Colmar`,type:0},{name:`Basel`,type:0},{name:`Vesoul`,type:0}]},
                {name:`Basel`,type:0,loc:[1651,1991],rule:`Ecclesiastical`,connect:[{name:`Aarau`,type:0},{name:`Freiburg`,type:0},{name:`Belfort`,type:0},{name:`Bern`,type:0},{name:`Neuchâtel`,type:0}]},
                {name:`Vesoul`,type:0,loc:[1137,2004],rule:`Andechs`,connect:[{name:`Épinal`,type:0},{name:`Belfort`,type:0},{name:`Dole`,type:0},{name:`Besançon`,type:0}]},
                {name:`Herisau`,type:0,loc:[2263,2018],rule:`Toggenburg`,connect:[{name:`Konstanz`,type:0},{name:`Bregenz`,type:1},{name:`Chur`,type:0},{name:`Altdorf`,type:0}]},
                {name:`Aarau`,type:0,loc:[1823,2061],rule:`Habsburg`,connect:[{name:`Bern`,type:0},{name:`Basel`,type:0},{name:`Altdorf`,type:0},{name:`Schaffhausen`,type:1}]},
                {name:`Besançon`,type:1,loc:[1117,2218],rule:`Ecclesiastical`,connect:[{name:`Neuchâtel`,type:1},{name:`Lons`,type:0},{name:`Dole`,type:0},{name:`Vesoul`,type:0}]},
                {name:`Chur`,type:0,loc:[2382,2289],rule:`Two Leagues`,connect:[{name:`Altdorf`,type:0},{name:`Herisau`,type:0}]},
                {name:`Dole`,type:1,loc:[925,2306],rule:`Andechs`,connect:[{name:`Vesoul`,type:0},{name:`Lons`,type:0},{name:`Besançon`,type:0}]},
                {name:`Neuchâtel`,type:0,loc:[1442,2308],rule:`Hohenzollern`,connect:[{name:`Besançon`,type:1},{name:`Basel`,type:0},{name:`Lausanne`,type:0},{name:`Bern`,type:0}]},
                {name:`Altdorf`,type:0,loc:[2066,2312],rule:`Schwyz`,connect:[{name:`Herisau`,type:0},{name:`Chur`,type:0},{name:`Aarau`,type:0},{name:`Thun`,type:0}]},
                {name:`Bern`,type:0,loc:[1647,2327],rule:`Zähringen`,connect:[{name:`Basel`,type:0},{name:`Aarau`,type:0},{name:`Thun`,type:0},{name:`Neuchâtel`,type:0}]},
                {name:`Thun`,type:0,loc:[1707,2422],rule:`Zähringen`,connect:[{name:`Altdorf`,type:0},{name:`Bern`,type:0},{name:`Lausanne`,type:0},{name:`Sion`,type:0}]},
                {name:`Lons`,type:0,loc:[998,2538],rule:`Andechs`,connect:[{name:`Dole`,type:0},{name:`Besançon`,type:0},{name:`Lausanne`,type:0},{name:`Bourg`,type:0},{name:`Geneva`,type:0}]},
                {name:`Lausanne`,type:2,loc:[1362,2582],rule:`Savoy`,connect:[{name:`Lons`,type:0},{name:`Thun`,type:0},{name:`Neuchâtel`,type:0},{name:`Geneva`,type:0},{name:`Sion`,type:0}]},
                {name:`Sion`,type:0,loc:[1647,2717],rule:`Valais`,connect:[{name:`Thun`,type:0},{name:`Lausanne`,type:0},{name:`Geneva`,type:1},{name:`Moustier`,type:0}]},
                {name:`Bourg`,type:0,loc:[875,2762],rule:`Arduinici`,connect:[{name:`Lons`,type:0},{name:`Geneva`,type:1},{name:`Colombier`,type:1},{name:`Lyon`,type:0}]},
                {name:`Geneva`,type:3,loc:[1210,2785],rule:`Geneva`,connect:[{name:`Bourg`,type:1},{name:`Lons`,type:0},{name:`Lausanne`,type:0},{name:`Sion`,type:1},{name:`Chambéry`,type:0}]},
                {name:`Lyon`,type:0,loc:[759,3010],rule:`Ecclesiastical`,connect:[{name:`Feurs`,type:0},{name:`Vienne`,type:0},{name:`Colombier`,type:0},{name:`Bourg`,type:0}]},
                {name:`Colombier`,type:0,loc:[883,3054],rule:`Arduinici`,connect:[{name:`Bourg`,type:1},{name:`Lyon`,type:0},{name:`Chambéry`,type:0},{name:`Vienne`,type:0},{name:`Grenoble`,type:0}]},
                {name:`Feurs`,type:0,loc:[551,3066],rule:`Albon`,connect:[{name:`Lyon`,type:0},{name:`Vienne`,type:0}]},
                {name:`Chambéry`,type:0,loc:[1169,3080],rule:`Savoy`,connect:[{name:`Moustier`,type:1},{name:`Geneva`,type:0},{name:`Grenoble`,type:0},{name:`Colombier`,type:0}]},
                {name:`Moustier`,type:0,loc:[1381,3100],rule:`Ecclesiastical`,connect:[{name:`Sion`,type:0},{name:`Chambéry`,type:1},{name:`Briançon`,type:0}]},
                {name:`Vienne`,type:1,loc:[777,3147],rule:`Ecclesiastical`,connect:[{name:`Feurs`,type:0},{name:`Albon`,type:0},{name:`Lyon`,type:0},{name:`Colombier`,type:0}]},
                {name:`Grenoble`,type:0,loc:[1111,3266],rule:`Albon`,connect:[{name:`Colombier`,type:0},{name:`Chambéry`,type:0},{name:`Gap`,type:0},{name:`Die`,type:0},{name:`Albon`,type:1}]},
                {name:`Albon`,type:0,loc:[811,3314],rule:`Albon`,connect:[{name:`Vienne`,type:0},{name:`Grenoble`,type:1},{name:`Valence`,type:1}]},
                {name:`Briançon`,type:0,loc:[1465,3409],rule:`Savoy`,connect:[{name:`Moustier`,type:0},{name:`Gap`,type:0},{name:`Barcelonette`,type:0}]},
                {name:`Valence`,type:0,loc:[808,3446],rule:`Rouergue`,connect:[{name:`Viviers`,type:0},{name:`Die`,type:0},{name:`Albon`,type:1}]},
                {name:`Die`,type:0,loc:[1002,3521],rule:`Rouergue`,connect:[{name:`Grenoble`,type:0},{name:`Gap`,type:0},{name:`Nyons`,type:0},{name:`Valence`,type:0}]},
                {name:`Gap`,type:2,loc:[1287,3611],rule:`Sabran`,connect:[{name:`Briançon`,type:0},{name:`Barcelonette`,type:1},{name:`Forcalquier`,type:0},{name:`Die`,type:0},{name:`Grenoble`,type:0}]},
                {name:`Barcelonette`,type:0,loc:[1483,3668],rule:`Savoy`,connect:[{name:`Briançon`,type:0},{name:`Gap`,type:1},{name:`Draguignan`,type:0},{name:`Nice`,type:0}]},
                {name:`Viviers`,type:0,loc:[754,3695],rule:`Ecclesiastical`,connect:[{name:`Nyons`,type:0},{name:`Valence`,type:0},{name:`Avignon`,type:1}]},
                {name:`Nyons`,type:0,loc:[931,3755],rule:`Rouergue`,connect:[{name:`Die`,type:0},{name:`Viviers`,type:0},{name:`Avignon`,type:0},{name:`Forcalquier`,type:0}]},
                {name:`Forcalquier`,type:0,loc:[1212,3949],rule:`Sabran`,connect:[{name:`Gap`,type:0},{name:`Nyons`,type:0},{name:`Aix`,type:1},{name:`Draguignan`,type:1}]},
                {name:`Avignon`,type:0,loc:[842,3985],rule:`Rouergue`,connect:[{name:`Viviers`,type:1},{name:`Nyons`,type:0},{name:`Arles`,type:0},{name:`Aix`,type:1}]},
                {name:`Nice`,type:0,loc:[1794,4006],rule:`Savoy`,connect:[{name:`Fréjus`,type:0},{name:`Barcelonette`,type:0}]},
                {name:`Draguignan`,type:0,loc:[1504,4121],rule:`Barcelona`,connect:[{name:`Fréjus`,type:0},{name:`Toulon`,type:1},{name:`Barcelonette`,type:0},{name:`Forcalquier`,type:1}]},
                {name:`Arles`,type:4,loc:[796,4130],rule:`Ecclesiastical`,connect:[{name:`Avignon`,type:0},{name:`Aix`,type:0}]},
                {name:`Fréjus`,type:0,loc:[1611,4174],rule:`Barcelona`,connect:[{name:`Toulon`,type:0},{name:`Nice`,type:0},{name:`Draguignan`,type:0}]},
                {name:`Aix`,type:1,loc:[1116,4193],rule:`Barcelona`,connect:[{name:`Arles`,type:0},{name:`Avignon`,type:1},{name:`Toulon`,type:0},{name:`Forcalquier`,type:1}]},
                {name:`Toulon`,type:0,loc:[1327,4357],rule:`Barcelona`,connect:[{name:`Fréjus`,type:0},{name:`Draguignan`,type:1},{name:`Aix`,type:0}]},
            ],team:[
                {name:`Isenberg`,term:`isenberg`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Baden`,term:`baden`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Toggenburg`,term:`toggenburg`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Schwyz`,term:`schwyz`,type:`Rural`,allies:[`Valais`,`Two Leagues`],quality:1.1,chance:0.5},
                {name:`Valais`,term:`valais`,type:`Rural`,allies:[`Schwyz`,`Two Leagues`],quality:1,chance:0.5},
                {name:`Two Leagues`,term:`two leagues`,type:`Rural`,allies:[`Schwyz`,`Valais`],quality:1,chance:0.5},
                {name:`Lillebonne`,term:`lillebonne`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Geneva`,term:`geneva`,type:`Urban`,allies:[],quality:1,chance:0.5},
                {name:`Hohenzollern`,term:`hohenzollern`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Sabran`,term:`sabran`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Kyburg`,term:`kyburg`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Zähringen`,term:`zahringen`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`League of Cities`,term:`league of cities`,type:`Urban`,allies:[],quality:0.9,chance:1},
                {name:`Arduinici`,term:`arduinici`,type:`Minor Nobility`,allies:[],quality:1,chance:1},
                {name:`Albon`,term:`albon`,type:`Middle Nobility`,allies:[],quality:1,chance:1},
                {name:`Andechs`,term:`andechs`,type:`Major Nobility`,allies:[],quality:1,chance:1},
                {name:`Württemberg`,term:`wurttemberg`,type:`Middle Nobility`,allies:[],quality:1,chance:1},
                {name:`Ecclesiastical`,term:`ecclesiastical2`,type:`Major Nobility`,allies:[],quality:0.9,chance:1.5},
                {name:`Lorraine`,term:`lorraine`,type:`Middle Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Rouergue`,term:`rouergue`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Barcelona`,term:`barcelona`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Habsburg`,term:`junior habsburg`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Wittelsbach`,term:`elder wittelsbach`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Savoy`,term:`savoy`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
            ],
        },{
            name:[`Belgica`,`Base`],
            term:`belgica`,
            stack:false,
            teamSet:3,
            constants:{spawn:{base:2500,spend:1000,regen:12,garrison:500}},
            city:[
                {name:`Groningen`,type:0,loc:[1884,449],rule:`Friesland`,connect:[{name:`Stavoren`,type:0},{name:`Coeverden`,type:0}]},
                {name:`Stavoren`,type:0,loc:[1544,700],rule:`Friesland`,connect:[{name:`Groningen`,type:0},{name:`Zwolle`,type:0},{name:`Den Haag`,type:2},{name:`Amsterdam`,type:2},{name:`Alkmaar`,type:2}]},
                {name:`Coeverden`,type:0,loc:[1981,748],rule:`Habsburg`,connect:[{name:`Groningen`,type:0},{name:`Zwolle`,type:0},{name:`Oldenzaal`,type:0}]},
                {name:`Alkmaar`,type:0,loc:[1339,857],rule:`Avesnes`,connect:[{name:`Leiden`,type:0},{name:`Stavoren`,type:2},{name:`Amsterdam`,type:2}]},
                {name:`Zwolle`,type:0,loc:[1785,878],rule:`Habsburg`,connect:[{name:`Coeverden`,type:0},{name:`Arnhem`,type:0},{name:`Stavoren`,type:0},{name:`Oldenzaal`,type:0}]},
                {name:`Oldenzaal`,type:0,loc:[2046,938],rule:`Habsburg`,connect:[{name:`Coeverden`,type:0},{name:`Arnhem`,type:1},{name:`Zwolle`,type:0}]},
                {name:`Amsterdam`,type:0,loc:[1415,1007],rule:`Avesnes`,connect:[{name:`Leiden`,type:0},{name:`Utrecht`,type:0},{name:`Alkmaar`,type:2},{name:`Stavoren`,type:2}]},
                {name:`Leiden`,type:0,loc:[1286,1108],rule:`Avesnes`,connect:[{name:`Alkmaar`,type:0},{name:`Amsterdam`,type:0},{name:`Utrecht`,type:0},{name:`Den Haag`,type:1}]},
                {name:`Utrecht`,type:0,loc:[1495,1121],rule:`Ecclesiastical`,connect:[{name:`Amsterdam`,type:0},{name:`Leiden`,type:0},{name:`Arnhem`,type:0},{name:`Breda`,type:1}]},
                {name:`Arnhem`,type:0,loc:[1743,1146],rule:`Wassenberg`,connect:[{name:`Zwolle`,type:0},{name:`Oldenzaal`,type:1},{name:`Utrecht`,type:0},{name:`'s-Hertogenbosch`,type:1},{name:`Gelders`,type:1}]},
                {name:`Den Haag`,type:3,loc:[1216,1177],rule:`Avesnes`,connect:[{name:`Leiden`,type:1},{name:`Dordrecht`,type:1},{name:`Middelburg`,type:2},{name:`Stavoren`,type:2}]},
                {name:`Dordrecht`,type:0,loc:[1358,1281],rule:`Avesnes`,connect:[{name:`Breda`,type:1},{name:`Den Haag`,type:1},{name:`Middelburg`,type:2}]},
                {name:`'s-Hertogenbosch`,type:0,loc:[1598,1345],rule:`Leuven`,connect:[{name:`Arnhem`,type:1},{name:`Breda`,type:0},{name:`Eindhoven`,type:0}]},
                {name:`Gelders`,type:1,loc:[1918,1389],rule:`Wassenberg`,connect:[{name:`Roermond`,type:0},{name:`Arnhem`,type:1},{name:`Eindhoven`,type:1}]},
                {name:`Breda`,type:0,loc:[1417,1423],rule:`Leuven`,connect:[{name:`Dordrecht`,type:1},{name:`Antwerp`,type:0},{name:`Eindhoven`,type:0},{name:`Utrecht`,type:1},{name:`'s-Hertogenbosch`,type:0}]},
                {name:`Eindhoven`,type:0,loc:[1645,1464],rule:`Leuven`,connect:[{name:`'s-Hertogenbosch`,type:0},{name:`Breda`,type:0},{name:`Hasselt`,type:0},{name:`Roermond`,type:0},{name:`Gelders`,type:1}]},
                {name:`Middelburg`,type:0,loc:[1017,1501],rule:`Avesnes`,connect:[{name:`Den Haag`,type:2},{name:`Dordrecht`,type:2},{name:`Bruges`,type:2}]},
                {name:`Roermond`,type:0,loc:[1852,1543],rule:`Wassenberg`,connect:[{name:`Gelders`,type:0},{name:`Eindhoven`,type:0},{name:`Hasselt`,type:1}]},
                {name:`Antwerp`,type:0,loc:[1331,1613],rule:`League of Cities`,connect:[{name:`Breda`,type:0},{name:`Ghent`,type:0},{name:`Brussels`,type:0}]},
                {name:`Bruges`,type:1,loc:[938,1683],rule:`Dampierre`,connect:[{name:`Ghent`,type:0},{name:`Calais`,type:0},{name:`Middelburg`,type:2},{name:`Lille`,type:1}]},
                {name:`Hasselt`,type:0,loc:[1649,1701],rule:`Ecclesiastical`,connect:[{name:`Brussels`,type:0},{name:`Eindhoven`,type:0},{name:`Liège`,type:0},{name:`Roermond`,type:1},{name:`Maastricht`,type:0}]},
                {name:`Ghent`,type:0,loc:[1099,1723],rule:`Dampierre`,connect:[{name:`Bruges`,type:0},{name:`Lille`,type:0},{name:`Ath`,type:0},{name:`Brussels`,type:1},{name:`Antwerp`,type:0}]},
                {name:`Maastricht`,type:0,loc:[1783,1750],rule:`Leuven`,connect:[{name:`Hasselt`,type:0},{name:`Liège`,type:0}]},
                {name:`Brussels`,type:1,loc:[1344,1821],rule:`Leuven`,connect:[{name:`Ath`,type:0},{name:`Ghent`,type:1},{name:`Antwerp`,type:0},{name:`Namur`,type:0},{name:`Hasselt`,type:0}]},
                {name:`Calais`,type:0,loc:[494,1843],rule:`League of Cities`,connect:[{name:`St. Omer`,type:0},{name:`Boulogne`,type:0},{name:`Bruges`,type:0}]},
                {name:`Liège`,type:0,loc:[1737,1867],rule:`Ecclesiastical`,connect:[{name:`Maastricht`,type:0},{name:`Hasselt`,type:0},{name:`Namur`,type:0},{name:`Bastogne`,type:0}]},
                {name:`St. Omer`,type:0,loc:[640,1958],rule:`Dampierre`,connect:[{name:`Calais`,type:0},{name:`Boulogne`,type:0},{name:`Lille`,type:1},{name:`Arras`,type:1}]},
                {name:`Ath`,type:0,loc:[1128,1977],rule:`Avesnes`,connect:[{name:`Ghent`,type:0},{name:`Brussels`,type:0},{name:`Mons`,type:0},{name:`Lille`,type:1}]},
                {name:`Boulogne`,type:0,loc:[425,1984],rule:`Auvergne`,connect:[{name:`Calais`,type:0},{name:`Abbeville`,type:0},{name:`St. Omer`,type:0}]},
                {name:`Lille`,type:0,loc:[900,1991],rule:`Dampierre`,connect:[{name:`St. Omer`,type:1},{name:`Arras`,type:0},{name:`Bruges`,type:1},{name:`Ghent`,type:0},{name:`Ath`,type:1}]},
                {name:`Namur`,type:0,loc:[1535,2008],rule:`Dampierre`,connect:[{name:`Liège`,type:0},{name:`Dinant`,type:0},{name:`Mons`,type:0},{name:`Brussels`,type:0}]},
                {name:`Mons`,type:0,loc:[1228,2050],rule:`Avesnes`,connect:[{name:`Ath`,type:0},{name:`Cambrai`,type:0},{name:`Maubeuge`,type:0},{name:`Namur`,type:0}]},
                {name:`Dinant`,type:0,loc:[1572,2098],rule:`Ecclesiastical`,connect:[{name:`Namur`,type:0},{name:`Maubeuge`,type:0},{name:`Bastogne`,type:0},{name:`Sedan`,type:0}]},
                {name:`Arras`,type:0,loc:[833,2154],rule:`Dampierre`,connect:[{name:`Lille`,type:0},{name:`St. Omer`,type:1},{name:`Cambrai`,type:1},{name:`Péronne`,type:0},{name:`Amiens`,type:0}]},
                {name:`Bastogne`,type:0,loc:[1814,2184],rule:`Luxemburg`,connect:[{name:`Liège`,type:0},{name:`Dinant`,type:0},{name:`Luxemburg`,type:0},{name:`Vierton`,type:0}]},
                {name:`Maubeuge`,type:0,loc:[1280,2187],rule:`Avesnes`,connect:[{name:`St. Quentin`,type:0},{name:`Sedan`,type:0},{name:`Dinant`,type:0},{name:`Cambrai`,type:0},{name:`Mons`,type:0}]},
                {name:`Cambrai`,type:0,loc:[1016,2233],rule:`Ecclesiastical`,connect:[{name:`Péronne`,type:1},{name:`Arras`,type:1},{name:`Maubeuge`,type:0},{name:`Mons`,type:0}]},
                {name:`Abbeville`,type:0,loc:[480,2272],rule:`Harcourt`,connect:[{name:`Amiens`,type:0},{name:`Aumale`,type:0},{name:`Boulogne`,type:0}]},
                {name:`Péronne`,type:0,loc:[942,2349],rule:`Vermandois`,connect:[{name:`Arras`,type:0},{name:`Cambrai`,type:1},{name:`St. Quentin`,type:0},{name:`Noyon`,type:0},{name:`Amiens`,type:0}]},
                {name:`Amiens`,type:0,loc:[659,2380],rule:`Vermandois`,connect:[{name:`Péronne`,type:0},{name:`Arras`,type:0},{name:`Aumale`,type:0},{name:`Abbeville`,type:0}]},
                {name:`Luxemburg`,type:1,loc:[2016,2385],rule:`Luxemburg`,connect:[{name:`Bastogne`,type:0},{name:`Vierton`,type:0}]},
                {name:`St. Quentin`,type:0,loc:[1048,2399],rule:`Vermandois`,connect:[{name:`Péronne`,type:0},{name:`Maubeuge`,type:0},{name:`Noyon`,type:0},{name:`Laon`,type:1}]},
                {name:`Sedan`,type:0,loc:[1602,2400],rule:`Auvergne`,connect:[{name:`Maubeuge`,type:0},{name:`Dinant`,type:0},{name:`Rethel`,type:0},{name:`Verdun`,type:0},{name:`Vierton`,type:0}]},
                {name:`Vierton`,type:0,loc:[1777,2443],rule:`Luxemburg`,connect:[{name:`Bastogne`,type:0},{name:`Luxemburg`,type:0},{name:`Verdun`,type:0},{name:`Sedan`,type:0}]},
                {name:`Aumale`,type:0,loc:[490,2525],rule:`Harcourt`,connect:[{name:`Amiens`,type:0},{name:`Beauvais`,type:0},{name:`Abbeville`,type:0}]},
                {name:`Rethel`,type:0,loc:[1488,2545],rule:`Dampierre`,connect:[{name:`Sedan`,type:0},{name:`Verdun`,type:0},{name:`Reims`,type:0},{name:`Laon`,type:0}]},
                {name:`Laon`,type:0,loc:[1193,2571],rule:`Ecclesiastical`,connect:[{name:`Rethel`,type:0},{name:`Reims`,type:0},{name:`St. Quentin`,type:1},{name:`Noyon`,type:1}]},
                {name:`Noyon`,type:0,loc:[934,2581],rule:`Ecclesiastical`,connect:[{name:`Laon`,type:1},{name:`St. Quentin`,type:0},{name:`Péronne`,type:0},{name:`Beauvais`,type:0}]},
                {name:`Verdun`,type:0,loc:[1785,2671],rule:`League of Cities`,connect:[{name:`Vierton`,type:0},{name:`Sedan`,type:0},{name:`Rethel`,type:0},{name:`Châlons`,type:0}]},
                {name:`Beauvais`,type:0,loc:[639,2696],rule:`Ecclesiastical`,connect:[{name:`Aumale`,type:0},{name:`Noyon`,type:0}]},
                {name:`Reims`,type:1,loc:[1353,2730],rule:`Ecclesiastical`,connect:[{name:`Rethel`,type:0},{name:`Laon`,type:0},{name:`Châlons`,type:0}]},
                {name:`Châlons`,type:0,loc:[1497,2851],rule:`Ecclesiastical`,connect:[{name:`Reims`,type:0},{name:`Verdun`,type:0}]},
            ],team:[
                {name:`Auvergne`,term:`marck`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Harcourt`,term:`harcourt`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Friesland`,term:`friesland`,type:`Rural`,allies:[],quality:1,chance:1},
                {name:`Wassenberg`,term:`wassenberg`,type:`Middle Nobility`,allies:[],quality:1,chance:1},
                {name:`Vermandois`,term:`vermandois`,type:`Middle Nobility`,allies:[],quality:1,chance:1},
                {name:`Habsburg`,term:`elder habsburg`,type:`Middle Nobility`,allies:[],quality:1,chance:1},
                {name:`League of Cities`,term:`league of cities2`,type:`Urban`,allies:[],quality:0.9,chance:1},
                {name:`Luxemburg`,term:`luxemburg`,type:`Middle Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Leuven`,term:`leuven`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Avesnes`,term:`avesnes`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Dampierre`,term:`dampierre`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Ecclesiastical`,term:`ecclesiastical3`,type:`Major Nobility`,allies:[],quality:0.9,chance:1.5},
            ],
        },{
            name:[`Belgica`,`+ Jülich`],
            term:`belgica+`,
            stack:true,
            teamSet:3,
            constants:{spawn:{base:2500,spend:1000,regen:10,garrison:500}},
            city:[
                {name:`Groningen`,type:0,loc:[1884,449],rule:`Friesland`,connect:[{name:`Stavoren`,type:0},{name:`Coeverden`,type:0}]},
                {name:`Stavoren`,type:0,loc:[1544,700],rule:`Friesland`,connect:[{name:`Groningen`,type:0},{name:`Zwolle`,type:0},{name:`Den Haag`,type:2},{name:`Amsterdam`,type:2},{name:`Alkmaar`,type:2}]},
                {name:`Coeverden`,type:0,loc:[1981,748],rule:`Habsburg`,connect:[{name:`Groningen`,type:0},{name:`Zwolle`,type:0},{name:`Oldenzaal`,type:0}]},
                {name:`Alkmaar`,type:0,loc:[1339,857],rule:`Avesnes`,connect:[{name:`Leiden`,type:0},{name:`Stavoren`,type:2},{name:`Amsterdam`,type:2}]},
                {name:`Zwolle`,type:0,loc:[1785,878],rule:`Habsburg`,connect:[{name:`Coeverden`,type:0},{name:`Arnhem`,type:0},{name:`Stavoren`,type:0},{name:`Oldenzaal`,type:0}]},
                {name:`Oldenzaal`,type:0,loc:[2046,938],rule:`Habsburg`,connect:[{name:`Coeverden`,type:0},{name:`Arnhem`,type:1},{name:`Zwolle`,type:0}]},
                {name:`Amsterdam`,type:0,loc:[1415,1007],rule:`Avesnes`,connect:[{name:`Leiden`,type:0},{name:`Utrecht`,type:0},{name:`Alkmaar`,type:2},{name:`Stavoren`,type:2}]},
                {name:`Leiden`,type:0,loc:[1286,1108],rule:`Avesnes`,connect:[{name:`Alkmaar`,type:0},{name:`Amsterdam`,type:0},{name:`Utrecht`,type:0},{name:`Den Haag`,type:1}]},
                {name:`Utrecht`,type:0,loc:[1495,1121],rule:`Ecclesiastical`,connect:[{name:`Amsterdam`,type:0},{name:`Leiden`,type:0},{name:`Arnhem`,type:0},{name:`Breda`,type:1}]},
                {name:`Arnhem`,type:0,loc:[1743,1146],rule:`Wassenberg`,connect:[{name:`Zwolle`,type:0},{name:`Oldenzaal`,type:1},{name:`Utrecht`,type:0},{name:`'s-Hertogenbosch`,type:1},{name:`Cleves`,type:1}]},
                {name:`Den Haag`,type:3,loc:[1216,1177],rule:`Avesnes`,connect:[{name:`Leiden`,type:1},{name:`Dordrecht`,type:1},{name:`Middelburg`,type:2},{name:`Stavoren`,type:2}]},
                {name:`Cleves`,type:0,loc:[1874,1242],rule:`Hohenzollern`,connect:[{name:`'s-Hertogenbosch`,type:0},{name:`Arnhem`,type:1},{name:`Gelders`,type:0}]},
                {name:`Dordrecht`,type:0,loc:[1358,1281],rule:`Avesnes`,connect:[{name:`Breda`,type:1},{name:`Den Haag`,type:1},{name:`Middelburg`,type:2}]},
                {name:`'s-Hertogenbosch`,type:0,loc:[1598,1345],rule:`Leuven`,connect:[{name:`Arnhem`,type:1},{name:`Cleves`,type:0},{name:`Breda`,type:0},{name:`Eindhoven`,type:0}]},
                {name:`Gelders`,type:1,loc:[1918,1389],rule:`Wassenberg`,connect:[{name:`Roermond`,type:0},{name:`Cleves`,type:0},{name:`Eindhoven`,type:1},{name:`Neuss`,type:0}]},
                {name:`Breda`,type:0,loc:[1417,1423],rule:`Leuven`,connect:[{name:`Dordrecht`,type:1},{name:`Antwerp`,type:0},{name:`Eindhoven`,type:0},{name:`Utrecht`,type:1},{name:`'s-Hertogenbosch`,type:0}]},
                {name:`Eindhoven`,type:0,loc:[1645,1464],rule:`Leuven`,connect:[{name:`'s-Hertogenbosch`,type:0},{name:`Breda`,type:0},{name:`Hasselt`,type:0},{name:`Roermond`,type:0},{name:`Gelders`,type:1}]},
                {name:`Middelburg`,type:0,loc:[1017,1501],rule:`Avesnes`,connect:[{name:`Den Haag`,type:2},{name:`Dordrecht`,type:2},{name:`Bruges`,type:2}]},
                {name:`Neuss`,type:0,loc:[2088,1535],rule:`Ecclesiastical`,connect:[{name:`Gelders`,type:0},{name:`Köln`,type:0},{name:`Jülich`,type:0}]},
                {name:`Roermond`,type:0,loc:[1852,1543],rule:`Wassenberg`,connect:[{name:`Gelders`,type:0},{name:`Eindhoven`,type:0},{name:`Hasselt`,type:1},{name:`Jülich`,type:0}]},
                {name:`Antwerp`,type:0,loc:[1331,1613],rule:`League of Cities`,connect:[{name:`Breda`,type:0},{name:`Ghent`,type:0},{name:`Brussels`,type:0}]},
                {name:`Köln`,type:0,loc:[2199,1671],rule:`Ecclesiastical`,connect:[{name:`Neuss`,type:0},{name:`Jülich`,type:0},{name:`Zülpich`,type:0}]},
                {name:`Bruges`,type:1,loc:[938,1683],rule:`Dampierre`,connect:[{name:`Ghent`,type:0},{name:`Calais`,type:0},{name:`Middelburg`,type:2},{name:`Lille`,type:1}]},
                {name:`Jülich`,type:0,loc:[2015,1691],rule:`Wittelsbach`,connect:[{name:`Köln`,type:0},{name:`Zülpich`,type:0},{name:`Neuss`,type:0},{name:`Aachen`,type:0},{name:`Roermond`,type:0}]},
                {name:`Hasselt`,type:0,loc:[1649,1701],rule:`Ecclesiastical`,connect:[{name:`Brussels`,type:0},{name:`Eindhoven`,type:0},{name:`Liège`,type:0},{name:`Roermond`,type:1},{name:`Maastricht`,type:0}]},
                {name:`Ghent`,type:0,loc:[1099,1723],rule:`Dampierre`,connect:[{name:`Bruges`,type:0},{name:`Lille`,type:0},{name:`Ath`,type:0},{name:`Brussels`,type:1},{name:`Antwerp`,type:0}]},
                {name:`Maastricht`,type:0,loc:[1783,1750],rule:`Leuven`,connect:[{name:`Hasselt`,type:0},{name:`Liège`,type:0},{name:`Aachen`,type:0}]},
                {name:`Aachen`,type:0,loc:[1926,1786],rule:`League of Cities`,connect:[{name:`Jülich`,type:0},{name:`Arenberg`,type:0},{name:`Maastricht`,type:0}]},
                {name:`Zülpich`,type:0,loc:[2139,1819],rule:`Wittelsbach`,connect:[{name:`Arenberg`,type:0},{name:`Köln`,type:0},{name:`Jülich`,type:0}]},
                {name:`Brussels`,type:1,loc:[1344,1821],rule:`Leuven`,connect:[{name:`Ath`,type:0},{name:`Ghent`,type:1},{name:`Antwerp`,type:0},{name:`Namur`,type:0},{name:`Hasselt`,type:0}]},
                {name:`Calais`,type:0,loc:[494,1843],rule:`League of Cities`,connect:[{name:`St. Omer`,type:0},{name:`Boulogne`,type:0},{name:`Bruges`,type:0}]},
                {name:`Liège`,type:0,loc:[1737,1867],rule:`Ecclesiastical`,connect:[{name:`Maastricht`,type:0},{name:`Hasselt`,type:0},{name:`Namur`,type:0},{name:`Bastogne`,type:0}]},
                {name:`Arenberg`,type:0,loc:[2149,1943],rule:`Arenberg`,connect:[{name:`Aachen`,type:0},{name:`Prüm`,type:0},{name:`Zülpich`,type:0}]},
                {name:`St. Omer`,type:0,loc:[640,1958],rule:`Dampierre`,connect:[{name:`Calais`,type:0},{name:`Boulogne`,type:0},{name:`Lille`,type:1},{name:`Arras`,type:1}]},
                {name:`Ath`,type:0,loc:[1128,1977],rule:`Avesnes`,connect:[{name:`Ghent`,type:0},{name:`Brussels`,type:0},{name:`Mons`,type:0},{name:`Lille`,type:1}]},
                {name:`Boulogne`,type:0,loc:[425,1984],rule:`Auvergne`,connect:[{name:`Calais`,type:0},{name:`Abbeville`,type:0},{name:`St. Omer`,type:0}]},
                {name:`Lille`,type:0,loc:[900,1991],rule:`Dampierre`,connect:[{name:`St. Omer`,type:1},{name:`Arras`,type:0},{name:`Bruges`,type:1},{name:`Ghent`,type:0},{name:`Ath`,type:1}]},
                {name:`Namur`,type:0,loc:[1535,2008],rule:`Dampierre`,connect:[{name:`Liège`,type:0},{name:`Dinant`,type:0},{name:`Mons`,type:0},{name:`Brussels`,type:0}]},
                {name:`Mons`,type:0,loc:[1228,2050],rule:`Avesnes`,connect:[{name:`Ath`,type:0},{name:`Cambrai`,type:0},{name:`Maubeuge`,type:0},{name:`Namur`,type:0}]},
                {name:`Prüm`,type:0,loc:[2094,2078],rule:`Ecclesiastical`,connect:[{name:`Luxemburg`,type:0},{name:`Bastogne`,type:0},{name:`Arenberg`,type:0}]},
                {name:`Dinant`,type:0,loc:[1572,2098],rule:`Ecclesiastical`,connect:[{name:`Namur`,type:0},{name:`Maubeuge`,type:0},{name:`Bastogne`,type:0},{name:`Sedan`,type:0}]},
                {name:`Arras`,type:0,loc:[833,2154],rule:`Dampierre`,connect:[{name:`Lille`,type:0},{name:`St. Omer`,type:1},{name:`Cambrai`,type:1},{name:`Péronne`,type:0},{name:`Amiens`,type:0}]},
                {name:`Bastogne`,type:0,loc:[1814,2184],rule:`Luxemburg`,connect:[{name:`Liège`,type:0},{name:`Dinant`,type:0},{name:`Luxemburg`,type:0},{name:`Vierton`,type:0},{name:`Prüm`,type:0}]},
                {name:`Maubeuge`,type:0,loc:[1280,2187],rule:`Avesnes`,connect:[{name:`St. Quentin`,type:0},{name:`Sedan`,type:0},{name:`Dinant`,type:0},{name:`Cambrai`,type:0},{name:`Mons`,type:0}]},
                {name:`Cambrai`,type:0,loc:[1016,2233],rule:`Ecclesiastical`,connect:[{name:`Péronne`,type:1},{name:`Arras`,type:1},{name:`Maubeuge`,type:0},{name:`Mons`,type:0}]},
                {name:`Abbeville`,type:0,loc:[480,2272],rule:`Harcourt`,connect:[{name:`Amiens`,type:0},{name:`Aumale`,type:0},{name:`Boulogne`,type:0}]},
                {name:`Péronne`,type:0,loc:[942,2349],rule:`Vermandois`,connect:[{name:`Arras`,type:0},{name:`Cambrai`,type:1},{name:`St. Quentin`,type:0},{name:`Noyon`,type:0},{name:`Amiens`,type:0}]},
                {name:`Amiens`,type:0,loc:[659,2380],rule:`Vermandois`,connect:[{name:`Péronne`,type:0},{name:`Arras`,type:0},{name:`Aumale`,type:0},{name:`Abbeville`,type:0}]},
                {name:`Luxemburg`,type:1,loc:[2016,2385],rule:`Luxemburg`,connect:[{name:`Bastogne`,type:0},{name:`Vierton`,type:0},{name:`Prüm`,type:0}]},
                {name:`St. Quentin`,type:0,loc:[1048,2399],rule:`Vermandois`,connect:[{name:`Péronne`,type:0},{name:`Maubeuge`,type:0},{name:`Noyon`,type:0},{name:`Laon`,type:1}]},
                {name:`Sedan`,type:0,loc:[1602,2400],rule:`Auvergne`,connect:[{name:`Maubeuge`,type:0},{name:`Dinant`,type:0},{name:`Rethel`,type:0},{name:`Verdun`,type:0},{name:`Vierton`,type:0}]},
                {name:`Vierton`,type:0,loc:[1777,2443],rule:`Luxemburg`,connect:[{name:`Bastogne`,type:0},{name:`Luxemburg`,type:0},{name:`Verdun`,type:0},{name:`Sedan`,type:0}]},
                {name:`Aumale`,type:0,loc:[490,2525],rule:`Harcourt`,connect:[{name:`Amiens`,type:0},{name:`Beauvais`,type:0},{name:`Abbeville`,type:0}]},
                {name:`Rethel`,type:0,loc:[1488,2545],rule:`Dampierre`,connect:[{name:`Sedan`,type:0},{name:`Verdun`,type:0},{name:`Reims`,type:0},{name:`Laon`,type:0}]},
                {name:`Laon`,type:0,loc:[1193,2571],rule:`Ecclesiastical`,connect:[{name:`Rethel`,type:0},{name:`Reims`,type:0},{name:`St. Quentin`,type:1},{name:`Noyon`,type:1}]},
                {name:`Noyon`,type:0,loc:[934,2581],rule:`Ecclesiastical`,connect:[{name:`Laon`,type:1},{name:`St. Quentin`,type:0},{name:`Péronne`,type:0},{name:`Beauvais`,type:0}]},
                {name:`Verdun`,type:0,loc:[1785,2671],rule:`League of Cities`,connect:[{name:`Vierton`,type:0},{name:`Sedan`,type:0},{name:`Rethel`,type:0},{name:`Châlons`,type:0}]},
                {name:`Beauvais`,type:0,loc:[639,2696],rule:`Ecclesiastical`,connect:[{name:`Aumale`,type:0},{name:`Noyon`,type:0}]},
                {name:`Reims`,type:1,loc:[1353,2730],rule:`Ecclesiastical`,connect:[{name:`Rethel`,type:0},{name:`Laon`,type:0},{name:`Châlons`,type:0}]},
                {name:`Châlons`,type:0,loc:[1497,2851],rule:`Ecclesiastical`,connect:[{name:`Reims`,type:0},{name:`Verdun`,type:0}]},
            ],team:[
                {name:`Arenberg`,term:`arenberg`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Hohenzollern`,term:`hohenzollern`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Auvergne`,term:`marck`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Harcourt`,term:`harcourt`,type:`Minor Nobility`,allies:[],quality:1,chance:0.5},
                {name:`Friesland`,term:`friesland`,type:`Rural`,allies:[],quality:1,chance:1},
                {name:`Wassenberg`,term:`wassenberg`,type:`Middle Nobility`,allies:[],quality:1,chance:1},
                {name:`Vermandois`,term:`vermandois`,type:`Middle Nobility`,allies:[],quality:1,chance:1},
                {name:`Habsburg`,term:`elder habsburg`,type:`Middle Nobility`,allies:[],quality:1,chance:1},
                {name:`League of Cities`,term:`league of cities2`,type:`Urban`,allies:[],quality:0.9,chance:1},
                {name:`Wittelsbach`,term:`junior wittelsbach`,type:`Minor Nobility`,allies:[`Avesnes`],quality:1,chance:1},
                {name:`Luxemburg`,term:`luxemburg`,type:`Middle Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Leuven`,term:`leuven`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Avesnes`,term:`avesnes`,type:`Major Nobility`,allies:[`Wittelsbach`],quality:1,chance:1.5},
                {name:`Dampierre`,term:`dampierre`,type:`Major Nobility`,allies:[],quality:1,chance:1.5},
                {name:`Ecclesiastical`,term:`ecclesiastical3`,type:`Major Nobility`,allies:[],quality:0.9,chance:1.5},
            ],
        },
    ],
}
export var convert=[
    [`Wiemken`,`Isenberg`,`Avesnes`,`Nassau`,`Zähringen`,`Ascania`,`Schwyz`,`Two Leagues`,`Lillebonne`,`Württemberg`,`Arenberg`,`Niklot`,`Bibra`,`Hesse`,`Hohenzollern`,`Ecclesiastical`,`League of Cities`,`Lorraine`,`Welf`,`Wettin`,`Elder Habsburg`,`Junior Habsburg`,`Elder Wittelsbach`,`Junior Wittelsbach`],//old teams
    [`Tiny`,`HRE`,`HRE + Bohemia`,`Arelatisches Reich`],//old maps
]
export var dev={
    instant:false,training:false,speed:false,new:false,//training
    road:false,pause:false,close:false,//tool
    assemble:false,assemble2:false,//deprecated
}
export var training={}
export var options={strength:1,strengthEdit:false}
export var graphics={main:0,load:{map:[],city:[],team:[],unit:[]}}
export var constants={trig:[[],[]],spawn:{},init:false,threshold:100000}
export var inputs={mouse:{base:{x:0,y:0},rel:{x:0,y:0},previous:{base:{x:0,y:0},rel:{x:0,y:0}}}}