listing={
    city:[
        `cityPNG`,`electorPNG`,`circleCapitalPNG`,`majorCityPNG`
    ],team:[
        `albon`,`andechs`,`arduinici`,`arenberg`,`ascania`,`avesnes`,`baden`,`barcelona`,`bibra`,`ecclesiastical`,
        `ecclesiastical2`,`elder habsburg`,`elder wittelsbach`,`geneva`,`hesse`,`hohenzollern`,`isenberg`,`junior habsburg`,`junior wittelsbach`,`kyburg`,
        `league of cities`,`lillebonne`,`lorraine`,`nassau`,`niklot`,`premyslid`,`rouergue`,`sabran`,`savoy`,`schwyz`,
        `toggenburg`,`two leagues`,`valais`,`welf`,`wettin`,`wiemken`,`wurttemberg`,`zahringen`,
    ],unit:[
        `large`,`garrison`,`display`
    ]
}
types={
    city:[],
    team:[],
    cityType:[
        {name:`Base`,term:0,value:1},
        {name:`Electorate`,term:1,value:2},
        {name:`Circle Capital`,term:2,value:1.5},
        {name:`Administrative Capital`,term:3,value:1.25},
        {name:`Symbolic Capital`,term:3,value:1.25},
    ],map:[
        {
            name:`Tiny`,
            term:`minim`,
            teamSet:2,
            constants:{spawn:{base:2500,spend:1000,regen:30,garrison:500}},
            city:[
                {name:`Frankfurt`,type:2,loc:[1216,24],rule:'Isenberg',connect:[{name:`Würzburg`,type:1},{name:`Heidelberg`,type:0},{name:`Oppenheim`,type:1}]},
                {name:`Simmern`,type:0,loc:[887,83],rule:'Wittelsbach',connect:[{name:`Trier`,type:0},{name:`Oppenheim`,type:0}]},
                {name:`Oppenheim`,type:0,loc:[1099,152],rule:'Wittelsbach',connect:[{name:`Speyer`,type:0},{name:`Heidelberg`,type:1},{name:`Frankfurt`,type:1},{name:`Simmern`,type:0},{name:`Pirmasens`,type:0}]},
                {name:`Würzburg`,type:1,loc:[1580,191],rule:'Bibra',connect:[{name:`Hall`,type:0},{name:`Frankfurt`,type:1}]},
                {name:`Trier`,type:1,loc:[609,192],rule:'Ecclesiastical',connect:[{name:`Simmern`,type:0},{name:`Metz`,type:0},{name:`Luxemburg`,type:1}]},
                {name:`Luxemburg`,type:0,loc:[448,251],rule:'Habsburg',connect:[{name:`Trier`,type:1},{name:`Metz`,type:0}]},
                {name:`Heidelberg`,type:1,loc:[1202,378],rule:'Wittelsbach',connect:[{name:`Frankfurt`,type:0},{name:`Stuttgart`,type:0},{name:`Speyer`,type:0},{name:`Oppenheim`,type:1}]},
                {name:`Speyer`,type:0,loc:[1123,414],rule:'Zähringen',connect:[{name:`Pirmasens`,type:1},{name:`Heidelberg`,type:0},{name:`Oppenheim`,type:0},{name:`Stuttgart`,type:0},{name:`Straßburg`,type:0}]},
                {name:`Metz`,type:0,loc:[448,482],rule:'Lorraine',connect:[{name:`Trier`,type:0},{name:`Pirmasens`,type:0},{name:`Bar`,type:1},{name:`Nanzig`,type:0},{name:`Luxemburg`,type:0}]},
                {name:`Pirmasens`,type:0,loc:[825,489],rule:'League of Cities',connect:[{name:`Oppenheim`,type:0},{name:`Metz`,type:0},{name:`Speyer`,type:1},{name:`Straßburg`,type:0}]},
                {name:`Hall`,type:0,loc:[1510,522],rule:'League of Cities',connect:[{name:`Würzburg`,type:0},{name:`Stuttgart`,type:0},{name:`Ulm`,type:0}]},
                {name:`Bar`,type:0,loc:[129,640],rule:'Lillebonne',connect:[{name:`Metz`,type:1},{name:`Nanzig`,type:1}]},
                {name:`Stuttgart`,type:0,loc:[1336,683],rule:'Württemberg',connect:[{name:`Heidelberg`,type:0},{name:`Speyer`,type:0},{name:`Hall`,type:0},{name:`Ulm`,type:0}]},
                {name:`Nanzig`,type:2,loc:[441,688],rule:'Lorraine',connect:[{name:`Metz`,type:0},{name:`Bar`,type:1},{name:`Straßburg`,type:0}]},
                {name:`Straßburg`,type:0,loc:[916,764],rule:'League of Cities',connect:[{name:`Nanzig`,type:0},{name:`Pirmasens`,type:0},{name:`Speyer`,type:0}]},
                {name:`Ulm`,type:3,loc:[1586,865],rule:'League of Cities',connect:[{name:`Hall`,type:0},{name:`Stuttgart`,type:0}]},
            ],team:[
                {name:`Isenberg`,term:`isenberg`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Zähringen`,term:`baden`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Lillebonne`,term:`lillebonne`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Württemberg`,term:`wurttemberg`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Bibra`,term:`bibra`,allies:[],type:0,quality:1,chance:1},
                {name:`Ecclesiastical`,term:`ecclesiastical`,allies:[],type:0,quality:0.9,chance:1},
                {name:`Habsburg`,term:`elder habsburg`,allies:[],type:0,quality:1,chance:1},
                {name:`Lorraine`,term:`lorraine`,allies:[],type:0,quality:1,chance:1},
                {name:`League of Cities`,term:`league of cities`,allies:[],type:0,quality:0.9,chance:1.5},
                {name:`Wittelsbach`,term:`elder wittelsbach`,allies:[],type:0,quality:1,chance:1.5},
            ],
        },{
            name:`HRE`,
            term:`hre`,
            teamSet:3,
            constants:{spawn:{base:2500,spend:1000,regen:10,garrison:500}},
            city:[
                {name:`Rostock`,type:0,loc:[2399,437],rule:'Niklot',connect:[{name:`Schwerin`,type:0},{name:`Lübeck`,type:2},{name:`Waren`,type:0}]},
                {name:`Lübeck`,type:0,loc:[2024,539],rule:'Ascania',connect:[{name:`Schwerin`,type:0},{name:`Lüneburg`,type:1},{name:`Glückstadt`,type:0},{name:`Rostock`,type:2}]},
                {name:`Glückstadt`,type:2,loc:[1690,597],rule:'Hohenzollern',connect:[{name:`Lübeck`,type:0},{name:`Lüneburg`,type:1},{name:`Bremen`,type:0},{name:`Jever`,type:2}]},
                {name:`Schwerin`,type:1,loc:[2196,640],rule:'Niklot',connect:[{name:`Rostock`,type:0},{name:`Lübeck`,type:0},{name:`Lüneburg`,type:1},{name:`Waren`,type:0}]},
                {name:`Jever`,type:0,loc:[1251,675],rule:'Wiemken',connect:[{name:`Oldenburg`,type:0},{name:`Meppen`,type:0},{name:`Glückstadt`,type:2},{name:`Emden`,type:0}]},
                {name:`Waren`,type:0,loc:[2558,704],rule:'Niklot',connect:[{name:`Schwerin`,type:0},{name:`Rostock`,type:0}]},
                {name:`Emden`,type:0,loc:[1067,761],rule:'Arenberg',connect:[{name:`Oldenburg`,type:0},{name:`Jever`,type:0},{name:`Meppen`,type:0}]},
                {name:`Lüneburg`,type:0,loc:[1929,847],rule:'Welf',connect:[{name:`Lübeck`,type:1},{name:`Schwerin`,type:1},{name:`Bremen`,type:0},{name:`Celle`,type:0},{name:`Braunschweig`,type:1},{name:`Glückstadt`,type:1}]},
                {name:`Oldenburg`,type:0,loc:[1328,892],rule:'Arenberg',connect:[{name:`Jever`,type:0},{name:`Meppen`,type:0},{name:`Bremen`,type:0},{name:`Minden`,type:0},{name:`Emden`,type:0}]},
                {name:`Bremen`,type:0,loc:[1493,926],rule:'Ecclesiastical',connect:[{name:`Oldenburg`,type:0},{name:`Lüneburg`,type:0},{name:`Celle`,type:0},{name:`Glückstadt`,type:0}]},
                {name:`Meppen`,type:1,loc:[1067,1094],rule:'Arenberg',connect:[{name:`Oldenburg`,type:0},{name:`Jever`,type:0},{name:`Minden`,type:0},{name:`Emden`,type:0}]},
                {name:`Celle`,type:0,loc:[1837,1151],rule:'Welf',connect:[{name:`Bremen`,type:0},{name:`Minden`,type:0},{name:`Hannover`,type:0},{name:`Braunschweig`,type:0},{name:`Lüneburg`,type:0}]},
                {name:`Hannover`,type:0,loc:[1749,1279],rule:'Welf',connect:[{name:`Celle`,type:0},{name:`Braunschweig`,type:0},{name:`Goslar`,type:0},{name:`Minden`,type:0},{name:`Paderborn`,type:1}]},
                {name:`Minden`,type:0,loc:[1524,1304],rule:'Ecclesiastical',connect:[{name:`Meppen`,type:0},{name:`Oldenburg`,type:0},{name:`Hannover`,type:0},{name:`Paderborn`,type:0},{name:`Celle`,type:0}]},
                {name:`Braunschweig`,type:2,loc:[1972,1327],rule:'Welf',connect:[{name:`Lüneburg`,type:1},{name:`Hannover`,type:0},{name:`Goslar`,type:0},{name:`Celle`,type:0}]},
                {name:`Goslar`,type:0,loc:[1948,1491],rule:'Avesnes',connect:[{name:`Braunschweig`,type:0},{name:`Hannover`,type:0},{name:`Kassel`,type:1},{name:`Erfurt`,type:0}]},
                {name:`Paderborn`,type:2,loc:[1472,1579],rule:'Ecclesiastical',connect:[{name:`Minden`,type:0},{name:`Hannover`,type:1},{name:`Kassel`,type:0},{name:`Fredeburg`,type:1}]},
                {name:`Kassel`,type:0,loc:[1673,1771],rule:'Hesse',connect:[{name:`Goslar`,type:1},{name:`Paderborn`,type:0},{name:`Fredeburg`,type:0},{name:`Gießen`,type:0},{name:`Fulda`,type:0},{name:`Erfurt`,type:1}]},
                {name:`Düsseldorf`,type:0,loc:[911,1806],rule:'Junior Wittelsbach',connect:[{name:`Köln`,type:1},{name:`Altena`,type:0},{name:`Siegen`,type:0}]},
                {name:`Altena`,type:0,loc:[1166,1814],rule:'Hohenzollern',connect:[{name:`Fredeburg`,type:0},{name:`Düsseldorf`,type:0}]},
                {name:`Fredeburg`,type:0,loc:[1333,1850],rule:'Ecclesiastical',connect:[{name:`Kassel`,type:0},{name:`Paderborn`,type:1},{name:`Siegen`,type:0},{name:`Altena`,type:0}]},
                {name:`Erfurt`,type:2,loc:[2127,1950],rule:'Wettin',connect:[{name:`Goslar`,type:0},{name:`Kassel`,type:1},{name:`Fulda`,type:1},{name:`Coburg`,type:0},{name:`Gera`,type:0}]},
                {name:`Köln`,type:2,loc:[946,1952],rule:'Junior Wittelsbach',connect:[{name:`Koblenz`,type:0},{name:`Düsseldorf`,type:1},{name:`Lüttich`,type:1}]},
                {name:`Gera`,type:0,loc:[2431,1983],rule:'Wettin',connect:[{name:`Erfurt`,type:0},{name:`Plauen`,type:0},{name:`Coburg`,type:0}]},
                {name:`Siegen`,type:0,loc:[1267,1989],rule:'Nassau',connect:[{name:`Düsseldorf`,type:0},{name:`Fredeburg`,type:0},{name:`Gießen`,type:0},{name:`Koblenz`,type:0}]},
                {name:`Lüttich`,type:0,loc:[536,2083],rule:'Ecclesiastical',connect:[{name:`Köln`,type:0},{name:`Rochefort`,type:0},{name:`Luxemburg`,type:0}]},
                {name:`Gießen`,type:0,loc:[1445,2110],rule:'Hesse',connect:[{name:`Kassel`,type:0},{name:`Fulda`,type:0},{name:`Siegen`,type:0},{name:`Frankfurt`,type:0}]},
                {name:`Fulda`,type:0,loc:[1736,2148],rule:'Ecclesiastical',connect:[{name:`Kassel`,type:0},{name:`Erfurt`,type:1},{name:`Coburg`,type:1},{name:`Gießen`,type:0},{name:`Schweinfurt`,type:0}]},
                {name:`Plauen`,type:0,loc:[2445,2173],rule:'Hohenzollern',connect:[{name:`Bamberg`,type:0},{name:`Amberg`,type:0},{name:`Gera`,type:0},{name:`Nürnberg`,type:0}]},
                {name:`Koblenz`,type:0,loc:[1119,2239],rule:'Ecclesiastical',connect:[{name:`Köln`,type:0},{name:`Siegen`,type:0},{name:`Simmern`,type:0},{name:`Trier`,type:1},{name:`Frankfurt`,type:0}]},
                {name:`Rochefort`,type:0,loc:[461,2277],rule:'Avesnes',connect:[{name:`Luxemburg`,type:0},{name:`Lüttich`,type:0}]},
                {name:`Coburg`,type:0,loc:[2108,2294],rule:'Wettin',connect:[{name:`Erfurt`,type:0},{name:`Gera`,type:0},{name:`Fulda`,type:1},{name:`Bamberg`,type:0},{name:`Schweinfurt`,type:0}]},
                {name:`Frankfurt`,type:2,loc:[1448,2359],rule:'Isenberg',connect:[{name:`Gießen`,type:0},{name:`Würzburg`,type:1},{name:`Heidelberg`,type:0},{name:`Oppenheim`,type:1},{name:`Koblenz`,type:0}]},
                {name:`Schweinfurt`,type:0,loc:[1894,2396],rule:'Bibra',connect:[{name:`Bamberg`,type:0},{name:`Fulda`,type:0},{name:`Coburg`,type:0},{name:`Würzburg`,type:0}]},
                {name:`Simmern`,type:0,loc:[1119,2418],rule:'Elder Wittelsbach',connect:[{name:`Koblenz`,type:0},{name:`Trier`,type:0},{name:`Oppenheim`,type:0}]},
                {name:`Bamberg`,type:0,loc:[2077,2486],rule:'Bibra',connect:[{name:`Würzburg`,type:1},{name:`Schweinfurt`,type:0},{name:`Coburg`,type:0},{name:`Plauen`,type:0},{name:`Nürnberg`,type:0}]},
                {name:`Oppenheim`,type:0,loc:[1331,2487],rule:'Elder Wittelsbach',connect:[{name:`Speyer`,type:0},{name:`Heidelberg`,type:1},{name:`Frankfurt`,type:1},{name:`Simmern`,type:0},{name:`Pirmasens`,type:0}]},
                {name:`Würzburg`,type:1,loc:[1812,2526],rule:'Bibra',connect:[{name:`Bamberg`,type:1},{name:`Hall`,type:0},{name:`Frankfurt`,type:1},{name:`Nürnberg`,type:1},{name:`Schweinfurt`,type:0}]},
                {name:`Trier`,type:1,loc:[841,2527],rule:'Ecclesiastical',connect:[{name:`Koblenz`,type:1},{name:`Simmern`,type:0},{name:`Metz`,type:0},{name:`Luxemburg`,type:1}]},
                {name:`Luxemburg`,type:0,loc:[680,2586],rule:'Elder Habsburg',connect:[{name:`Trier`,type:1},{name:`Metz`,type:0},{name:`Rochefort`,type:0},{name:`Lüttich`,type:0}]},
                {name:`Nürnberg`,type:2,loc:[2149,2693],rule:'Hohenzollern',connect:[{name:`Ingolstadt`,type:0},{name:`Amberg`,type:0},{name:`Hall`,type:1},{name:`Würzburg`,type:1},{name:`Bamberg`,type:0},{name:`Plauen`,type:0}]},
                {name:`Amberg`,type:0,loc:[2396,2705],rule:'Elder Wittelsbach',connect:[{name:`Regensburg`,type:0},{name:`Ingolstadt`,type:0},{name:`Plauen`,type:0},{name:`Nürnberg`,type:0},{name:`Straubing`,type:0}]},
                {name:`Heidelberg`,type:1,loc:[1434,2713],rule:'Elder Wittelsbach',connect:[{name:`Frankfurt`,type:0},{name:`Stuttgart`,type:0},{name:`Speyer`,type:0},{name:`Oppenheim`,type:1}]},
                {name:`Speyer`,type:0,loc:[1355,2749],rule:'Zähringen',connect:[{name:`Pirmasens`,type:1},{name:`Heidelberg`,type:0},{name:`Oppenheim`,type:0},{name:`Stuttgart`,type:0},{name:`Freiburg`,type:0}]},
                {name:`Metz`,type:0,loc:[680,2817],rule:'Lorraine',connect:[{name:`Trier`,type:0},{name:`Pirmasens`,type:0},{name:`Bar`,type:1},{name:`Nanzig`,type:0},{name:`Luxemburg`,type:0}]},
                {name:`Pirmasens`,type:0,loc:[1057,2824],rule:'League of Cities',connect:[{name:`Oppenheim`,type:0},{name:`Metz`,type:0},{name:`Speyer`,type:1},{name:`Straßburg`,type:0}]},
                {name:`Hall`,type:0,loc:[1742,2857],rule:'League of Cities',connect:[{name:`Nürnberg`,type:1},{name:`Würzburg`,type:0},{name:`Stuttgart`,type:0},{name:`Ulm`,type:0}]},
                {name:`Regensburg`,type:1,loc:[2456,2894],rule:'Ecclesiastical',connect:[{name:`Amberg`,type:0},{name:`Ingolstadt`,type:0},{name:`Straubing`,type:0}]},
                {name:`Straubing`,type:0,loc:[2601,2956],rule:'Ecclesiastical',connect:[{name:`Amberg`,type:0},{name:`Regensburg`,type:0}]},
                {name:`Bar`,type:0,loc:[361,2975],rule:'Lillebonne',connect:[{name:`Metz`,type:1},{name:`Spinneln`,type:1}]},
                {name:`Stuttgart`,type:0,loc:[1568,3018],rule:'Württemberg',connect:[{name:`Heidelberg`,type:0},{name:`Speyer`,type:0},{name:`Hall`,type:0},{name:`Ulm`,type:0},{name:`Freiburg`,type:0}]},
                {name:`Nanzig`,type:2,loc:[673,3023],rule:'Lorraine',connect:[{name:`Metz`,type:0},{name:`Spinneln`,type:0},{name:`Straßburg`,type:0}]},
                {name:`Ingolstadt`,type:0,loc:[2246,3025],rule:'Junior Wittelsbach',connect:[{name:`Ulm`,type:0},{name:`Regensburg`,type:0},{name:`Amberg`,type:0},{name:`Nürnberg`,type:0}]},
                {name:`Straßburg`,type:0,loc:[1148,3099],rule:'League of Cities',connect:[{name:`Nanzig`,type:0},{name:`Pirmasens`,type:0},{name:`Freiburg`,type:1},{name:`Vesoul`,type:0},{name:`Spinneln`,type:1}]},
                {name:`Ulm`,type:3,loc:[1818,3200],rule:'League of Cities',connect:[{name:`Hall`,type:0},{name:`Stuttgart`,type:0},{name:`Ingolstadt`,type:0},{name:`Bregenz`,type:0}]},
                {name:`Spinneln`,type:0,loc:[750,3284],rule:'Lorraine',connect:[{name:`Vesoul`,type:0},{name:`Bar`,type:1},{name:`Straßburg`,type:1},{name:`Nanzig`,type:0}]},
                {name:`Freiburg`,type:0,loc:[1176,3389],rule:'Junior Habsburg',connect:[{name:`Speyer`,type:0},{name:`Straßburg`,type:1},{name:`Stuttgart`,type:0},{name:`Konstanz`,type:0},{name:`Solothurn`,type:1}]},
                {name:`Vesoul`,type:0,loc:[632,3550],rule:'Elder Habsburg',connect:[{name:`Spinneln`,type:0},{name:`Straßburg`,type:0},{name:`Bisanz`,type:0}]},
                {name:`Konstanz`,type:2,loc:[1562,3554],rule:'Junior Habsburg',connect:[{name:`Freiburg`,type:0},{name:`Bregenz`,type:0},{name:`Herisau`,type:0}]},
                {name:`Bregenz`,type:0,loc:[1756,3640],rule:'Junior Habsburg',connect:[{name:`Ulm`,type:0},{name:`Konstanz`,type:0},{name:`Herisau`,type:1},{name:`Davos`,type:0}]},
                {name:`Herisau`,type:0,loc:[1589,3710],rule:'Schwyz',connect:[{name:`Bregenz`,type:1},{name:`Konstanz`,type:0},{name:`Davos`,type:1},{name:`Solothurn`,type:1}]},
                {name:`Bisanz`,type:2,loc:[588,3728],rule:'Elder Habsburg',connect:[{name:`Vesoul`,type:0},{name:`Solothurn`,type:1}]},
                {name:`Solothurn`,type:0,loc:[1068,3774],rule:'Junior Habsburg',connect:[{name:`Bisanz`,type:1},{name:`Herisau`,type:1},{name:`Freiburg`,type:1}]},
                {name:`Davos`,type:0,loc:[1749,3978],rule:'Two Leagues',connect:[{name:`Bregenz`,type:0},{name:`Herisau`,type:1}]},
            ],team:[
                {name:`Wiemken`,term:`wiemken`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Isenberg`,term:`isenberg`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Nassau`,term:`nassau`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Zähringen`,term:`baden`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Ascania`,term:`ascania`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Schwyz`,term:`schwyz`,allies:[`Two Leagues`],type:0,quality:1.1,chance:0.5},
                {name:`Two Leagues`,term:`two leagues`,allies:[`Schwyz`],type:0,quality:1,chance:0.5},
                {name:`Lillebonne`,term:`lillebonne`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Württemberg`,term:`wurttemberg`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Avesnes`,term:`avesnes`,allies:[],type:0,quality:1,chance:1},
                {name:`Hesse`,term:`hesse`,allies:[],type:0,quality:1,chance:1},
                {name:`Arenberg`,term:`arenberg`,allies:[],type:0,quality:1,chance:1},
                {name:`Niklot`,term:`niklot`,allies:[],type:0,quality:1,chance:1},
                {name:`Bibra`,term:`bibra`,allies:[],type:0,quality:1,chance:1.5},
                {name:`Hohenzollern`,term:`hohenzollern`,allies:[],type:0,quality:1,chance:1.5},
                {name:`Ecclesiastical`,term:`ecclesiastical`,allies:[],type:0,quality:0.9,chance:1.5},
                {name:`League of Cities`,term:`league of cities`,allies:[],type:0,quality:0.9,chance:1.5},
                {name:`Lorraine`,term:`lorraine`,allies:[],type:0,quality:1,chance:1.5},
                {name:`Welf`,term:`welf`,allies:[],type:0,quality:1,chance:1.5},
                {name:`Wettin`,term:`wettin`,allies:[],type:0,quality:1,chance:1.5},
                {name:`Elder Habsburg`,term:`elder habsburg`,allies:[`Junior Habsburg`],type:0,quality:1,chance:1.5},
                {name:`Junior Habsburg`,term:`junior habsburg`,allies:[`Elder Habsburg`],type:0,quality:1,chance:1.5},
                {name:`Elder Wittelsbach`,term:`elder wittelsbach`,allies:[`Junior Wittelsbach`],type:0,quality:1,chance:1.5},
                {name:`Junior Wittelsbach`,term:`junior wittelsbach`,allies:[`Elder Wittelsbach`],type:0,quality:1,chance:1.5},
            ],
        },{
            name:`HRE + Bohemia`,
            term:`hre+bohemia`,
            teamSet:3,
            constants:{spawn:{base:2500,spend:1000,regen:10,garrison:500}},
            city:[
                {name:`Rostock`,type:0,loc:[2399,437],rule:'Niklot',connect:[{name:`Schwerin`,type:0},{name:`Lübeck`,type:2},{name:`Waren`,type:0}]},
                {name:`Lübeck`,type:0,loc:[2024,539],rule:'Ascania',connect:[{name:`Schwerin`,type:0},{name:`Lüneburg`,type:1},{name:`Glückstadt`,type:0},{name:`Rostock`,type:2}]},
                {name:`Glückstadt`,type:2,loc:[1690,597],rule:'Hohenzollern',connect:[{name:`Lübeck`,type:0},{name:`Lüneburg`,type:1},{name:`Bremen`,type:0},{name:`Jever`,type:2}]},
                {name:`Schwerin`,type:1,loc:[2196,640],rule:'Niklot',connect:[{name:`Rostock`,type:0},{name:`Lübeck`,type:0},{name:`Lüneburg`,type:1},{name:`Waren`,type:0}]},
                {name:`Jever`,type:0,loc:[1251,675],rule:'Wiemken',connect:[{name:`Oldenburg`,type:0},{name:`Meppen`,type:0},{name:`Glückstadt`,type:2},{name:`Emden`,type:0}]},
                {name:`Waren`,type:0,loc:[2558,704],rule:'Niklot',connect:[{name:`Schwerin`,type:0},{name:`Rostock`,type:0}]},
                {name:`Emden`,type:0,loc:[1067,761],rule:'Arenberg',connect:[{name:`Oldenburg`,type:0},{name:`Jever`,type:0},{name:`Meppen`,type:0}]},
                {name:`Lüneburg`,type:0,loc:[1929,847],rule:'Welf',connect:[{name:`Lübeck`,type:1},{name:`Schwerin`,type:1},{name:`Bremen`,type:0},{name:`Celle`,type:0},{name:`Braunschweig`,type:1},{name:`Glückstadt`,type:1}]},
                {name:`Oldenburg`,type:0,loc:[1328,892],rule:'Arenberg',connect:[{name:`Jever`,type:0},{name:`Meppen`,type:0},{name:`Bremen`,type:0},{name:`Minden`,type:0},{name:`Emden`,type:0}]},
                {name:`Bremen`,type:0,loc:[1493,926],rule:'Ecclesiastical',connect:[{name:`Oldenburg`,type:0},{name:`Lüneburg`,type:0},{name:`Celle`,type:0},{name:`Glückstadt`,type:0}]},
                {name:`Meppen`,type:1,loc:[1067,1094],rule:'Arenberg',connect:[{name:`Oldenburg`,type:0},{name:`Jever`,type:0},{name:`Minden`,type:0},{name:`Emden`,type:0}]},
                {name:`Celle`,type:0,loc:[1837,1151],rule:'Welf',connect:[{name:`Bremen`,type:0},{name:`Minden`,type:0},{name:`Hannover`,type:0},{name:`Braunschweig`,type:0},{name:`Lüneburg`,type:0}]},
                {name:`Hannover`,type:0,loc:[1749,1279],rule:'Welf',connect:[{name:`Celle`,type:0},{name:`Braunschweig`,type:0},{name:`Goslar`,type:0},{name:`Minden`,type:0},{name:`Paderborn`,type:1}]},
                {name:`Minden`,type:0,loc:[1524,1304],rule:'Ecclesiastical',connect:[{name:`Meppen`,type:0},{name:`Oldenburg`,type:0},{name:`Hannover`,type:0},{name:`Paderborn`,type:0},{name:`Celle`,type:0}]},
                {name:`Braunschweig`,type:2,loc:[1972,1327],rule:'Welf',connect:[{name:`Lüneburg`,type:1},{name:`Hannover`,type:0},{name:`Goslar`,type:0},{name:`Celle`,type:0}]},
                {name:`Goslar`,type:0,loc:[1948,1491],rule:'Avesnes',connect:[{name:`Braunschweig`,type:0},{name:`Hannover`,type:0},{name:`Kassel`,type:1},{name:`Erfurt`,type:0}]},
                {name:`Paderborn`,type:2,loc:[1472,1579],rule:'Ecclesiastical',connect:[{name:`Minden`,type:0},{name:`Hannover`,type:1},{name:`Kassel`,type:0},{name:`Fredeburg`,type:1}]},
                {name:`Kassel`,type:0,loc:[1673,1771],rule:'Hesse',connect:[{name:`Goslar`,type:1},{name:`Paderborn`,type:0},{name:`Fredeburg`,type:0},{name:`Gießen`,type:0},{name:`Fulda`,type:0},{name:`Erfurt`,type:1}]},
                {name:`Düsseldorf`,type:0,loc:[911,1806],rule:'Junior Wittelsbach',connect:[{name:`Köln`,type:1},{name:`Altena`,type:0},{name:`Siegen`,type:0}]},
                {name:`Altena`,type:0,loc:[1166,1814],rule:'Hohenzollern',connect:[{name:`Fredeburg`,type:0},{name:`Düsseldorf`,type:0}]},
                {name:`Fredeburg`,type:0,loc:[1333,1850],rule:'Ecclesiastical',connect:[{name:`Kassel`,type:0},{name:`Paderborn`,type:1},{name:`Siegen`,type:0},{name:`Altena`,type:0}]},
                {name:`Erfurt`,type:2,loc:[2127,1950],rule:'Wettin',connect:[{name:`Goslar`,type:0},{name:`Kassel`,type:1},{name:`Fulda`,type:1},{name:`Coburg`,type:0},{name:`Gera`,type:0}]},
                {name:`Köln`,type:2,loc:[946,1952],rule:'Junior Wittelsbach',connect:[{name:`Koblenz`,type:0},{name:`Düsseldorf`,type:1},{name:`Lüttich`,type:1}]},
                {name:`Gera`,type:0,loc:[2431,1983],rule:'Wettin',connect:[{name:`Erfurt`,type:0},{name:`Plauen`,type:0},{name:`Coburg`,type:0}]},
                {name:`Siegen`,type:0,loc:[1267,1989],rule:'Nassau',connect:[{name:`Düsseldorf`,type:0},{name:`Fredeburg`,type:0},{name:`Gießen`,type:0},{name:`Koblenz`,type:0}]},
                {name:`Lüttich`,type:0,loc:[536,2083],rule:'Ecclesiastical',connect:[{name:`Köln`,type:0},{name:`Rochefort`,type:0},{name:`Luxemburg`,type:0}]},
                {name:`Gießen`,type:0,loc:[1445,2110],rule:'Hesse',connect:[{name:`Kassel`,type:0},{name:`Fulda`,type:0},{name:`Siegen`,type:0},{name:`Frankfurt`,type:0}]},
                {name:`Fulda`,type:0,loc:[1736,2148],rule:'Ecclesiastical',connect:[{name:`Kassel`,type:0},{name:`Erfurt`,type:1},{name:`Coburg`,type:1},{name:`Gießen`,type:0},{name:`Schweinfurt`,type:0}]},
                {name:`Plauen`,type:0,loc:[2445,2173],rule:'Hohenzollern',connect:[{name:`Bamberg`,type:0},{name:`Amberg`,type:0},{name:`Gera`,type:0},{name:`Nürnberg`,type:0},{name:`Eger`,type:0}]},
                {name:`Koblenz`,type:0,loc:[1119,2239],rule:'Ecclesiastical',connect:[{name:`Köln`,type:0},{name:`Siegen`,type:0},{name:`Simmern`,type:0},{name:`Trier`,type:1},{name:`Frankfurt`,type:0}]},
                {name:`Rochefort`,type:0,loc:[461,2277],rule:'Avesnes',connect:[{name:`Luxemburg`,type:0},{name:`Lüttich`,type:0}]},
                {name:`Coburg`,type:0,loc:[2108,2294],rule:'Wettin',connect:[{name:`Erfurt`,type:0},{name:`Gera`,type:0},{name:`Fulda`,type:1},{name:`Bamberg`,type:0},{name:`Schweinfurt`,type:0}]},
                {name:`Frankfurt`,type:2,loc:[1448,2359],rule:'Isenberg',connect:[{name:`Gießen`,type:0},{name:`Würzburg`,type:1},{name:`Heidelberg`,type:0},{name:`Oppenheim`,type:1},{name:`Koblenz`,type:0}]},
                {name:`Schweinfurt`,type:0,loc:[1894,2396],rule:'Bibra',connect:[{name:`Bamberg`,type:0},{name:`Fulda`,type:0},{name:`Coburg`,type:0},{name:`Würzburg`,type:0}]},
                {name:`Simmern`,type:0,loc:[1119,2418],rule:'Elder Wittelsbach',connect:[{name:`Koblenz`,type:0},{name:`Trier`,type:0},{name:`Oppenheim`,type:0}]},
                {name:`Bamberg`,type:0,loc:[2077,2486],rule:'Bibra',connect:[{name:`Würzburg`,type:1},{name:`Schweinfurt`,type:0},{name:`Coburg`,type:0},{name:`Plauen`,type:0},{name:`Nürnberg`,type:0}]},
                {name:`Oppenheim`,type:0,loc:[1331,2487],rule:'Elder Wittelsbach',connect:[{name:`Speyer`,type:0},{name:`Heidelberg`,type:1},{name:`Frankfurt`,type:1},{name:`Simmern`,type:0},{name:`Pirmasens`,type:0}]},
                {name:`Würzburg`,type:1,loc:[1812,2526],rule:'Bibra',connect:[{name:`Bamberg`,type:1},{name:`Hall`,type:0},{name:`Frankfurt`,type:1},{name:`Nürnberg`,type:1},{name:`Schweinfurt`,type:0}]},
                {name:`Trier`,type:1,loc:[841,2527],rule:'Ecclesiastical',connect:[{name:`Koblenz`,type:1},{name:`Simmern`,type:0},{name:`Metz`,type:0},{name:`Luxemburg`,type:1}]},
                {name:`Luxemburg`,type:0,loc:[680,2586],rule:'Elder Habsburg',connect:[{name:`Trier`,type:1},{name:`Metz`,type:0},{name:`Rochefort`,type:0},{name:`Lüttich`,type:0}]},
                {name:`Nürnberg`,type:2,loc:[2149,2693],rule:'Hohenzollern',connect:[{name:`Ingolstadt`,type:0},{name:`Amberg`,type:0},{name:`Hall`,type:1},{name:`Würzburg`,type:1},{name:`Bamberg`,type:0},{name:`Plauen`,type:0}]},
                {name:`Amberg`,type:0,loc:[2396,2705],rule:'Elder Wittelsbach',connect:[{name:`Regensburg`,type:0},{name:`Ingolstadt`,type:0},{name:`Plauen`,type:0},{name:`Nürnberg`,type:0},{name:`Straubing`,type:0},{name:`Eger`,type:0}]},
                {name:`Heidelberg`,type:1,loc:[1434,2713],rule:'Elder Wittelsbach',connect:[{name:`Frankfurt`,type:0},{name:`Stuttgart`,type:0},{name:`Speyer`,type:0},{name:`Oppenheim`,type:1}]},
                {name:`Speyer`,type:0,loc:[1355,2749],rule:'Zähringen',connect:[{name:`Pirmasens`,type:1},{name:`Heidelberg`,type:0},{name:`Oppenheim`,type:0},{name:`Stuttgart`,type:0},{name:`Freiburg`,type:0}]},
                {name:`Metz`,type:0,loc:[680,2817],rule:'Lorraine',connect:[{name:`Trier`,type:0},{name:`Pirmasens`,type:0},{name:`Bar`,type:1},{name:`Nanzig`,type:0},{name:`Luxemburg`,type:0}]},
                {name:`Pirmasens`,type:0,loc:[1057,2824],rule:'League of Cities',connect:[{name:`Oppenheim`,type:0},{name:`Metz`,type:0},{name:`Speyer`,type:1},{name:`Straßburg`,type:0}]},
                {name:`Hall`,type:0,loc:[1742,2857],rule:'League of Cities',connect:[{name:`Nürnberg`,type:1},{name:`Würzburg`,type:0},{name:`Stuttgart`,type:0},{name:`Ulm`,type:0}]},
                {name:`Regensburg`,type:1,loc:[2456,2894],rule:'Ecclesiastical',connect:[{name:`Amberg`,type:0},{name:`Ingolstadt`,type:0},{name:`Straubing`,type:0}]},
                {name:`Straubing`,type:0,loc:[2601,2956],rule:'Ecclesiastical',connect:[{name:`Amberg`,type:0},{name:`Regensburg`,type:0},{name:`Klattau`,type:1}]},
                {name:`Bar`,type:0,loc:[361,2975],rule:'Lillebonne',connect:[{name:`Metz`,type:1},{name:`Spinneln`,type:1}]},
                {name:`Stuttgart`,type:0,loc:[1568,3018],rule:'Württemberg',connect:[{name:`Heidelberg`,type:0},{name:`Speyer`,type:0},{name:`Hall`,type:0},{name:`Ulm`,type:0},{name:`Freiburg`,type:0}]},
                {name:`Nanzig`,type:2,loc:[673,3023],rule:'Lorraine',connect:[{name:`Metz`,type:0},{name:`Spinneln`,type:0},{name:`Straßburg`,type:0}]},
                {name:`Ingolstadt`,type:0,loc:[2246,3025],rule:'Junior Wittelsbach',connect:[{name:`Ulm`,type:0},{name:`Regensburg`,type:0},{name:`Amberg`,type:0},{name:`Nürnberg`,type:0}]},
                {name:`Straßburg`,type:0,loc:[1148,3099],rule:'League of Cities',connect:[{name:`Nanzig`,type:0},{name:`Pirmasens`,type:0},{name:`Freiburg`,type:1},{name:`Vesoul`,type:0},{name:`Spinneln`,type:1}]},
                {name:`Ulm`,type:3,loc:[1818,3200],rule:'League of Cities',connect:[{name:`Hall`,type:0},{name:`Stuttgart`,type:0},{name:`Ingolstadt`,type:0},{name:`Bregenz`,type:0}]},
                {name:`Spinneln`,type:0,loc:[750,3284],rule:'Lorraine',connect:[{name:`Vesoul`,type:0},{name:`Bar`,type:1},{name:`Straßburg`,type:1},{name:`Nanzig`,type:0}]},
                {name:`Freiburg`,type:0,loc:[1176,3389],rule:'Junior Habsburg',connect:[{name:`Speyer`,type:0},{name:`Straßburg`,type:1},{name:`Stuttgart`,type:0},{name:`Konstanz`,type:0},{name:`Solothurn`,type:1}]},
                {name:`Vesoul`,type:0,loc:[632,3550],rule:'Elder Habsburg',connect:[{name:`Spinneln`,type:0},{name:`Straßburg`,type:0},{name:`Bisanz`,type:0}]},
                {name:`Konstanz`,type:2,loc:[1562,3554],rule:'Junior Habsburg',connect:[{name:`Freiburg`,type:0},{name:`Bregenz`,type:0},{name:`Herisau`,type:0}]},
                {name:`Bregenz`,type:0,loc:[1756,3640],rule:'Junior Habsburg',connect:[{name:`Ulm`,type:0},{name:`Konstanz`,type:0},{name:`Herisau`,type:1},{name:`Davos`,type:0}]},
                {name:`Herisau`,type:0,loc:[1589,3710],rule:'Schwyz',connect:[{name:`Bregenz`,type:1},{name:`Konstanz`,type:0},{name:`Davos`,type:1},{name:`Solothurn`,type:1}]},
                {name:`Bisanz`,type:2,loc:[588,3728],rule:'Elder Habsburg',connect:[{name:`Vesoul`,type:0},{name:`Solothurn`,type:1}]},
                {name:`Solothurn`,type:0,loc:[1068,3774],rule:'Junior Habsburg',connect:[{name:`Bisanz`,type:1},{name:`Herisau`,type:1},{name:`Freiburg`,type:1}]},
                {name:`Davos`,type:0,loc:[1749,3978],rule:'Two Leagues',connect:[{name:`Bregenz`,type:0},{name:`Herisau`,type:1}]},
                {name:`Reichenberg`,type:0,loc:[3290,2024],rule:'Přemyslid',connect:[{name:`Leitmeritz`,type:0},{name:`Jitschin`,type:0},{name:`Prag`,type:1}]},
                {name:`Leitmeritz`,type:0,loc:[3014,2151],rule:'Přemyslid',connect:[{name:`Prag`,type:0},{name:`Reichenberg`,type:0},{name:`Saaz`,type:0}]},
                {name:`Jitschin`,type:0,loc:[3392,2178],rule:'Přemyslid',connect:[{name:`Kuttenberg`,type:1},{name:`Reichenberg`,type:0},{name:`Königgrätz`,type:0}]},
                {name:`Saaz`,type:0,loc:[2868,2255],rule:'Přemyslid',connect:[{name:`Pilsen`,type:0},{name:`Eger`,type:0},{name:`Leitmeritz`,type:0}]},
                {name:`Königgrätz`,type:0,loc:[3542,2276],rule:'Přemyslid',connect:[{name:`Jitschin`,type:0},{name:`Kuttenberg`,type:0}]},
                {name:`Prag`,type:1,loc:[3134,2370],rule:'Přemyslid',connect:[{name:`Leitmeritz`,type:0},{name:`Reichenberg`,type:1},{name:`Kuttenberg`,type:0},{name:`Tabor`,type:0},{name:`Pilsen`,type:1}]},
                {name:`Eger`,type:0,loc:[2522,2380],rule:'Přemyslid',connect:[{name:`Saaz`,type:0},{name:`Pilsen`,type:0},{name:`Amberg`,type:0},{name:`Plauen`,type:0}]},
                {name:`Kuttenberg`,type:0,loc:[3381,2412],rule:'Přemyslid',connect:[{name:`Königgrätz`,type:0},{name:`Tabor`,type:0},{name:`Prag`,type:0},{name:`Jitschin`,type:1}]},
                {name:`Pilsen`,type:0,loc:[2820,2528],rule:'Přemyslid',connect:[{name:`Saaz`,type:0},{name:`Eger`,type:0},{name:`Klattau`,type:1},{name:`Prag`,type:1}]},
                {name:`Tabor`,type:2,loc:[3225,2675],rule:'Přemyslid',connect:[{name:`Kuttenberg`,type:0},{name:`Prag`,type:0},{name:`Budweis`,type:0}]},
                {name:`Klattau`,type:0,loc:[2813,2708],rule:'Přemyslid',connect:[{name:`Pilsen`,type:1},{name:`Budweis`,type:0},{name:`Straubing`,type:0}]},
                {name:`Budweis`,type:0,loc:[3181,2891],rule:'Přemyslid',connect:[{name:`Tabor`,type:0},{name:`Klattau`,type:0}]},
            ],team:[
                {name:`Wiemken`,term:`wiemken`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Isenberg`,term:`isenberg`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Nassau`,term:`nassau`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Zähringen`,term:`baden`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Ascania`,term:`ascania`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Schwyz`,term:`schwyz`,allies:[`Two Leagues`],type:0,quality:1.1,chance:0.5},
                {name:`Two Leagues`,term:`two leagues`,allies:[`Schwyz`],type:0,quality:1,chance:0.5},
                {name:`Lillebonne`,term:`lillebonne`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Württemberg`,term:`wurttemberg`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Avesnes`,term:`avesnes`,allies:[],type:0,quality:1,chance:1},
                {name:`Hesse`,term:`hesse`,allies:[],type:0,quality:1,chance:1},
                {name:`Arenberg`,term:`arenberg`,allies:[],type:0,quality:1,chance:1},
                {name:`Niklot`,term:`niklot`,allies:[],type:0,quality:1,chance:1},
                {name:`Bibra`,term:`bibra`,allies:[],type:0,quality:1,chance:1.5},
                {name:`Hohenzollern`,term:`hohenzollern`,allies:[],type:0,quality:1,chance:1.5},
                {name:`Ecclesiastical`,term:`ecclesiastical`,allies:[],type:0,quality:0.9,chance:1.5},
                {name:`League of Cities`,term:`league of cities`,allies:[],type:0,quality:0.9,chance:1.5},
                {name:`Lorraine`,term:`lorraine`,allies:[],type:0,quality:1,chance:1.5},
                {name:`Welf`,term:`welf`,allies:[],type:0,quality:1,chance:1.5},
                {name:`Wettin`,term:`wettin`,allies:[],type:0,quality:1,chance:1.5},
                {name:`Elder Habsburg`,term:`elder habsburg`,allies:[`Junior Habsburg`],type:0,quality:1,chance:1.5},
                {name:`Junior Habsburg`,term:`junior habsburg`,allies:[`Elder Habsburg`],type:0,quality:1,chance:1.5},
                {name:`Elder Wittelsbach`,term:`elder wittelsbach`,allies:[`Junior Wittelsbach`],type:0,quality:1,chance:1.5},
                {name:`Junior Wittelsbach`,term:`junior wittelsbach`,allies:[`Elder Wittelsbach`],type:0,quality:1,chance:1.5},
                {name:`Přemyslid`,term:`premyslid`,allies:[],type:1,quality:1,chance:5},
            ],
        },{
            name:`Arelatisches Reich`,
            term:`arelat`,
            teamSet:3,
            constants:{spawn:{base:2500,spend:1000,regen:10,garrison:500}},
            city:[
                {name:`Koblenz`,type:0,loc:[1483,474],rule:'Ecclesiastical',connect:[{name:`Cochem`,type:0},{name:`Simmern`,type:0}]},
                {name:`Cochem`,type:0,loc:[1312,570],rule:'Ecclesiastical',connect:[{name:`Simmern`,type:1},{name:`Koblenz`,type:0},{name:`Trier`,type:1}]},
                {name:`Simmern`,type:0,loc:[1511,674],rule:'Wittelsbach',connect:[{name:`Koblenz`,type:0},{name:`Cochem`,type:1},{name:`Alzey`,type:0}]},
                {name:`Alzey`,type:0,loc:[1689,778],rule:'Wittelsbach',connect:[{name:`Simmern`,type:0},{name:`Kaiserslautern`,type:0},{name:`Heidelberg`,type:1}]},
                {name:`Trier`,type:1,loc:[1212,832],rule:'Ecclesiastical',connect:[{name:`Cochem`,type:1},{name:`Kaiserslautern`,type:0},{name:`Metz`,type:0}]},
                {name:`Heidelberg`,type:0,loc:[1913,951],rule:'Wittelsbach',connect:[{name:`Alzey`,type:1},{name:`Kaiserslautern`,type:1},{name:`Speyer`,type:0},{name:`Stuttgart`,type:0}]},
                {name:`Kaiserslautern`,type:0,loc:[1589,954],rule:'Wittelsbach',connect:[{name:`Heidelberg`,type:1},{name:`Speyer`,type:0},{name:`Alzey`,type:0},{name:`Trier`,type:0},{name:`Saarbrücken`,type:0},{name:`Pirmasens`,type:0}]},
                {name:`Speyer`,type:2,loc:[1833,1002],rule:'Ecclesiastical',connect:[{name:`Heidelberg`,type:0},{name:`Kaiserslautern`,type:0},{name:`Baden`,type:0}]},
                {name:`Saarbrücken`,type:0,loc:[1341,1097],rule:'Wittelsbach',connect:[{name:`Kaiserslautern`,type:0},{name:`Pirmasens`,type:0},{name:`Saarburg`,type:0},{name:`Metz`,type:0}]},
                {name:`Pirmasens`,type:0,loc:[1561,1101],rule:'Isenberg',connect:[{name:`Kaiserslautern`,type:0},{name:`Saarbrücken`,type:0},{name:`Straßburg`,type:0}]},
                {name:`Metz`,type:0,loc:[1077,1186],rule:'Ecclesiastical',connect:[{name:`Saarbrücken`,type:0},{name:`Trier`,type:0},{name:`Nancy`,type:0},{name:`Verdun`,type:0},{name:`Toul`,type:1}]},
                {name:`Verdun`,type:0,loc:[795,1189],rule:'Ecclesiastical',connect:[{name:`Metz`,type:0},{name:`Bar`,type:0}]},
                {name:`Stuttgart`,type:1,loc:[2118,1253],rule:'Württemberg',connect:[{name:`Heidelberg`,type:0},{name:`Baden`,type:0},{name:`Freudenstadt`,type:0},{name:`Urach`,type:1}]},
                {name:`Baden`,type:0,loc:[1800,1313],rule:'Baden',connect:[{name:`Speyer`,type:0},{name:`Stuttgart`,type:0},{name:`Freudenstadt`,type:0},{name:`Straßburg`,type:0}]},
                {name:`Saarburg`,type:0,loc:[1389,1371],rule:'Lorraine',connect:[{name:`Straßburg`,type:0},{name:`Saarbrücken`,type:0},{name:`Nancy`,type:0},{name:`Épinal`,type:1}]},
                {name:`Urach`,type:0,loc:[2216,1405],rule:'Württemberg',connect:[{name:`Stuttgart`,type:1},{name:`Sigmaringen`,type:0}]},
                {name:`Bar`,type:0,loc:[740,1407],rule:'Lillebonne',connect:[{name:`Verdun`,type:0},{name:`Toul`,type:1}]},
                {name:`Nancy`,type:1,loc:[1100,1415],rule:'Lorraine',connect:[{name:`Metz`,type:0},{name:`Toul`,type:0},{name:`Saarburg`,type:0},{name:`Épinal`,type:0}]},
                {name:`Straßburg`,type:0,loc:[1646,1417],rule:'League of Cities',connect:[{name:`Baden`,type:0},{name:`Colmar`,type:0},{name:`Pirmasens`,type:0},{name:`Saarburg`,type:0}]},
                {name:`Toul`,type:0,loc:[1002,1439],rule:'Ecclesiastical',connect:[{name:`Épinal`,type:0},{name:`Nancy`,type:0},{name:`Bar`,type:1},{name:`Metz`,type:1}]},
                {name:`Freudenstadt`,type:0,loc:[1923,1476],rule:'Württemberg',connect:[{name:`Stuttgart`,type:0},{name:`Baden`,type:0},{name:`Freiburg`,type:0},{name:`Sigmaringen`,type:1}]},
                {name:`Sigmaringen`,type:0,loc:[2171,1626],rule:'Hohenzollern',connect:[{name:`Urach`,type:0},{name:`Freudenstadt`,type:1},{name:`Konstanz`,type:2},{name:`Memmingen`,type:1}]},
                {name:`Memmingen`,type:0,loc:[2524,1652],rule:'League of Cities',connect:[{name:`Sigmaringen`,type:1},{name:`Bregenz`,type:0}]},
                {name:`Épinal`,type:0,loc:[1226,1691],rule:'Lorraine',connect:[{name:`Toul`,type:0},{name:`Nancy`,type:0},{name:`Saarburg`,type:0},{name:`Colmar`,type:1},{name:`Vesoul`,type:0},{name:`Belfort`,type:0}]},
                {name:`Colmar`,type:0,loc:[1530,1702],rule:'League of Cities',connect:[{name:`Straßburg`,type:0},{name:`Freiburg`,type:1},{name:`Épinal`,type:0},{name:`Belfort`,type:0}]},
                {name:`Freiburg`,type:0,loc:[1725,1740],rule:'Habsburg',connect:[{name:`Basel`,type:0},{name:`Colmar`,type:1},{name:`Freudenstadt`,type:0},{name:`Schaffhausen`,type:0}]},
                {name:`Schaffhausen`,type:0,loc:[2005,1870],rule:'Kyburg',connect:[{name:`Freiburg`,type:0},{name:`Aarau`,type:1},{name:`Sigmaringen`,type:0},{name:`Konstanz`,type:0}]},
                {name:`Konstanz`,type:2,loc:[2202,1870],rule:'Kyburg',connect:[{name:`Bregenz`,type:2},{name:`Sigmaringen`,type:2},{name:`Schaffhausen`,type:0},{name:`Herisau`,type:0}]},
                {name:`Bregenz`,type:0,loc:[2422,1928],rule:'Habsburg',connect:[{name:`Memmingen`,type:0},{name:`Konstanz`,type:2},{name:`Herisau`,type:1}]},
                {name:`Belfort`,type:0,loc:[1394,1947],rule:'Habsburg',connect:[{name:`Épinal`,type:0},{name:`Colmar`,type:0},{name:`Basel`,type:0},{name:`Vesoul`,type:0}]},
                {name:`Basel`,type:0,loc:[1651,1991],rule:'Habsburg',connect:[{name:`Aarau`,type:0},{name:`Freiburg`,type:0},{name:`Belfort`,type:0},{name:`Bern`,type:0},{name:`Neuchâtel`,type:0}]},
                {name:`Vesoul`,type:0,loc:[1137,2004],rule:'Andechs',connect:[{name:`Épinal`,type:0},{name:`Belfort`,type:0},{name:`Dole`,type:0},{name:`Besançon`,type:0}]},
                {name:`Herisau`,type:0,loc:[2263,2018],rule:'Toggenburg',connect:[{name:`Konstanz`,type:0},{name:`Bregenz`,type:1},{name:`Chur`,type:0},{name:`Altdorf`,type:0}]},
                {name:`Aarau`,type:0,loc:[1823,2061],rule:'Habsburg',connect:[{name:`Bern`,type:0},{name:`Basel`,type:0},{name:`Altdorf`,type:0},{name:`Schaffhausen`,type:1}]},
                {name:`Besançon`,type:1,loc:[1117,2218],rule:'Ecclesiastical',connect:[{name:`Neuchâtel`,type:0},{name:`Lons`,type:0},{name:`Dole`,type:0},{name:`Vesoul`,type:0}]},
                {name:`Chur`,type:0,loc:[2382,2289],rule:'Two Leagues',connect:[{name:`Altdorf`,type:0},{name:`Herisau`,type:0}]},
                {name:`Dole`,type:1,loc:[925,2306],rule:'Andechs',connect:[{name:`Vesoul`,type:0},{name:`Lons`,type:0},{name:`Besançon`,type:0}]},
                {name:`Neuchâtel`,type:0,loc:[1442,2308],rule:'Hohenzollern',connect:[{name:`Besançon`,type:0},{name:`Basel`,type:0},{name:`Lausanne`,type:0},{name:`Bern`,type:0}]},
                {name:`Altdorf`,type:0,loc:[2066,2312],rule:'Schwyz',connect:[{name:`Herisau`,type:0},{name:`Chur`,type:0},{name:`Aarau`,type:0},{name:`Thun`,type:0}]},
                {name:`Bern`,type:0,loc:[1647,2327],rule:'Zähringen',connect:[{name:`Basel`,type:0},{name:`Aarau`,type:0},{name:`Thun`,type:0},{name:`Neuchâtel`,type:0}]},
                {name:`Thun`,type:0,loc:[1707,2422],rule:'Zähringen',connect:[{name:`Altdorf`,type:0},{name:`Bern`,type:0},{name:`Lausanne`,type:0},{name:`Sion`,type:0}]},
                {name:`Lons`,type:0,loc:[998,2538],rule:'Andechs',connect:[{name:`Dole`,type:0},{name:`Besançon`,type:0},{name:`Lausanne`,type:0},{name:`Bourg`,type:0},{name:`Geneva`,type:0}]},
                {name:`Lausanne`,type:2,loc:[1362,2582],rule:'Savoy',connect:[{name:`Lons`,type:0},{name:`Thun`,type:0},{name:`Neuchâtel`,type:0},{name:`Geneva`,type:0},{name:`Sion`,type:0}]},
                {name:`Sion`,type:0,loc:[1647,2717],rule:'Valais',connect:[{name:`Thun`,type:0},{name:`Lausanne`,type:0},{name:`Geneva`,type:1},{name:`Moustier`,type:0}]},
                {name:`Bourg`,type:0,loc:[875,2762],rule:'Arduinici',connect:[{name:`Lons`,type:0},{name:`Geneva`,type:1},{name:`Colombier`,type:1},{name:`Lyon`,type:0}]},
                {name:`Geneva`,type:3,loc:[1210,2785],rule:'Geneva',connect:[{name:`Bourg`,type:1},{name:`Lons`,type:0},{name:`Lausanne`,type:0},{name:`Sion`,type:1},{name:`Chambéry`,type:0}]},
                {name:`Lyon`,type:0,loc:[759,3010],rule:'Ecclesiastical',connect:[{name:`Feurs`,type:0},{name:`Vienne`,type:0},{name:`Colombier`,type:0},{name:`Bourg`,type:0}]},
                {name:`Colombier`,type:0,loc:[883,3054],rule:'Arduinici',connect:[{name:`Bourg`,type:1},{name:`Lyon`,type:0},{name:`Chambéry`,type:0},{name:`Vienne`,type:0},{name:`Grenoble`,type:0}]},
                {name:`Feurs`,type:0,loc:[551,3066],rule:'Albon',connect:[{name:`Lyon`,type:0},{name:`Vienne`,type:0}]},
                {name:`Chambéry`,type:0,loc:[1169,3080],rule:'Savoy',connect:[{name:`Moustier`,type:1},{name:`Geneva`,type:0},{name:`Grenoble`,type:0},{name:`Colombier`,type:0}]},
                {name:`Moustier`,type:0,loc:[1381,3100],rule:'Ecclesiastical',connect:[{name:`Sion`,type:0},{name:`Chambéry`,type:1},{name:`Briançon`,type:0}]},
                {name:`Vienne`,type:0,loc:[777,3147],rule:'Ecclesiastical',connect:[{name:`Feurs`,type:0},{name:`Albon`,type:0},{name:`Lyon`,type:0},{name:`Colombier`,type:0}]},
                {name:`Grenoble`,type:0,loc:[1111,3266],rule:'Albon',connect:[{name:`Colombier`,type:0},{name:`Chambéry`,type:0},{name:`Gap`,type:0},{name:`Die`,type:0},{name:`Albon`,type:1}]},
                {name:`Albon`,type:0,loc:[811,3314],rule:'Albon',connect:[{name:`Vienne`,type:0},{name:`Grenoble`,type:1},{name:`Valence`,type:1}]},
                {name:`Briançon`,type:0,loc:[1465,3409],rule:'Savoy',connect:[{name:`Moustier`,type:0},{name:`Gap`,type:0},{name:`Barcelonette`,type:0}]},
                {name:`Valence`,type:0,loc:[808,3446],rule:'Rouergue',connect:[{name:`Viviers`,type:0},{name:`Die`,type:0},{name:`Albon`,type:1}]},
                {name:`Die`,type:0,loc:[1002,3521],rule:'Rouergue',connect:[{name:`Grenoble`,type:0},{name:`Gap`,type:0},{name:`Nyons`,type:0},{name:`Valence`,type:0}]},
                {name:`Gap`,type:2,loc:[1287,3611],rule:'Sabran',connect:[{name:`Briançon`,type:0},{name:`Barcelonette`,type:1},{name:`Forcalquier`,type:0},{name:`Die`,type:0},{name:`Grenoble`,type:0}]},
                {name:`Barcelonette`,type:0,loc:[1483,3668],rule:'Savoy',connect:[{name:`Briançon`,type:0},{name:`Gap`,type:1},{name:`Draguignan`,type:0},{name:`Nice`,type:0}]},
                {name:`Viviers`,type:0,loc:[754,3695],rule:'Ecclesiastical',connect:[{name:`Nyons`,type:0},{name:`Valence`,type:0},{name:`Avignon`,type:1}]},
                {name:`Nyons`,type:0,loc:[931,3755],rule:'Rouergue',connect:[{name:`Die`,type:0},{name:`Viviers`,type:0},{name:`Avignon`,type:0},{name:`Forcalquier`,type:0}]},
                {name:`Forcalquier`,type:0,loc:[1212,3949],rule:'Sabran',connect:[{name:`Gap`,type:0},{name:`Nyons`,type:0},{name:`Aix`,type:1},{name:`Draguignan`,type:1}]},
                {name:`Avignon`,type:0,loc:[842,3985],rule:'Rouergue',connect:[{name:`Viviers`,type:1},{name:`Nyons`,type:0},{name:`Arles`,type:0},{name:`Aix`,type:1}]},
                {name:`Nice`,type:0,loc:[1794,4006],rule:'Savoy',connect:[{name:`Fréjus`,type:0},{name:`Barcelonette`,type:0}]},
                {name:`Draguignan`,type:0,loc:[1504,4121],rule:'Barcelona',connect:[{name:`Fréjus`,type:0},{name:`Toulon`,type:1},{name:`Barcelonette`,type:0},{name:`Forcalquier`,type:1}]},
                {name:`Arles`,type:4,loc:[796,4130],rule:'Ecclesiastical',connect:[{name:`Avignon`,type:0},{name:`Aix`,type:0}]},
                {name:`Fréjus`,type:0,loc:[1611,4174],rule:'Barcelona',connect:[{name:`Toulon`,type:0},{name:`Nice`,type:0},{name:`Draguignan`,type:0}]},
                {name:`Aix`,type:1,loc:[1116,4193],rule:'Barcelona',connect:[{name:`Arles`,type:0},{name:`Avignon`,type:1},{name:`Toulon`,type:0},{name:`Forcalquier`,type:1}]},
                {name:`Toulon`,type:0,loc:[1327,4357],rule:'Barcelona',connect:[{name:`Fréjus`,type:0},{name:`Draguignan`,type:1},{name:`Aix`,type:0}]},
            ],team:[
                {name:`Isenberg`,term:`isenberg`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Baden`,term:`baden`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Sabran`,term:`sabran`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Toggenburg`,term:`toggenburg`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Schwyz`,term:`schwyz`,allies:[`Valais`,`Two Leagues`],type:0,quality:1.1,chance:0.5},
                {name:`Valais`,term:`valais`,allies:[`Schwyz`,`Two Leagues`],type:0,quality:1,chance:0.5},
                {name:`Two Leagues`,term:`two leagues`,allies:[`Schwyz`,`Valais`],type:0,quality:1,chance:0.5},
                {name:`Lillebonne`,term:`lillebonne`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Geneva`,term:`geneva`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Hohenzollern`,term:`hohenzollern`,allies:[],type:0,quality:1,chance:0.5},
                {name:`Kyburg`,term:`kyburg`,allies:[],type:0,quality:1,chance:1},
                {name:`Zähringen`,term:`zahringen`,allies:[],type:0,quality:1,chance:1},
                {name:`Albon`,term:`albon`,allies:[],type:0,quality:1,chance:1},
                {name:`Arduinici`,term:`arduinici`,allies:[],type:0,quality:1,chance:1},
                {name:`Andechs`,term:`andechs`,allies:[],type:0,quality:1,chance:1},
                {name:`Württemberg`,term:`wurttemberg`,allies:[],type:0,quality:1,chance:1},
                {name:`League of Cities`,term:`league of cities`,allies:[],type:0,quality:0.9,chance:1},
                {name:`Ecclesiastical`,term:`ecclesiastical2`,allies:[],type:0,quality:0.9,chance:1.5},
                {name:`Lorraine`,term:`lorraine`,allies:[],type:0,quality:1,chance:1.5},
                {name:`Rouergue`,term:`rouergue`,allies:[],type:0,quality:1,chance:1.5},
                {name:`Barcelona`,term:`barcelona`,allies:[],type:0,quality:1,chance:1.5},
                {name:`Habsburg`,term:`junior habsburg`,allies:[],type:0,quality:1,chance:1.5},
                {name:`Wittelsbach`,term:`elder wittelsbach`,allies:[],type:0,quality:1,chance:1.5},
                {name:`Savoy`,term:`savoy`,allies:[],type:0,quality:1,chance:1.5},
            ],
        },
    ],
}
convert=[
    [`Wiemken`,`Isenberg`,`Avesnes`,`Nassau`,`Zähringen`,`Ascania`,`Schwyz`,`Two Leagues`,`Lillebonne`,`Württemberg`,`Arenberg`,`Niklot`,`Bibra`,`Hesse`,`Hohenzollern`,`Ecclesiastical`,`League of Cities`,`Lorraine`,`Welf`,`Wettin`,`Elder Habsburg`,`Junior Habsburg`,`Elder Wittelsbach`,`Junior Wittelsbach`],//old teams
]
dev={road:false,instant:false,assemble:false,assemble2:false,pause:false,new:false,speed:false,close:false}
graphics={main:0,load:{map:[],city:[],team:[],unit:[]}}
constants={trig:[[],[]],spawn:{},init:false,threshold:100000}
inputs={mouse:{base:{x:0,y:0},rel:{x:0,y:0},previous:{base:{x:0,y:0},rel:{x:0,y:0}}}}