types={
    city:[],
    team:[],
    cityType:[
        {name:`Base`,term:`cityPNG`,value:1},
        {name:`Electorate`,term:`electorPNG`,value:2},
        {name:`Circle Capital`,term:`circleCapitalPNG`,value:1.5},
    ],
    teamListing:[
        `arenberg`,`ascania`,`avesnes`,`bibra`,`ecclesiastical`,`elder habsburg`,`elder wittelsbach`,`hesse`,`hohenzollern`,`isenberg`,
        `junior habsburg`,`junior wittelsbach`,`league of cities`,`lillebonne`,`lorraine`,`nassau`,`niklot`,`premyslid`,`schwyz`,`two leagues`,
        `welf`,`wettin`,`wiemken`,`wurttemberg`,`zahringen`,
    ],
    map:[
        {
            name:`Tiny`,
            term:`minim`,
            teamSet:2,
            constants:{spawn:{base:2500,spend:1000,regen:30,garrison:500}},
            city:[
                {name:`Frankfurt`,type:2,loc:[1216,24],rule:'Isenberg',connect:[{name:`Würzburg`,type:1},{name:`Heidelberg`,type:0},{name:`Oppenheim`,type:1}]},
                {name:`Simmern`,type:0,loc:[887,83],rule:'Wittelsbach',connect:[{name:`Trier`,type:0},{name:`Oppenheim`,type:0}]},
                {name:`Oppenheim`,type:0,loc:[1099,152],rule:'Wittelsbach',connect:[{name:`Speyer`,type:0},{name:`Heidelberg`,type:1},{name:`Frankfurt`,type:1},{name:`Simmern`,type:0},{name:`Pirmasens`,type:0}]},
                {name:`Würzburg`,type:1,loc:[1580,191],rule:'Bibra',connect:[{name:`Hall`,type:0},{name:`Frankfurt`,type:1}]},
                {name:`Trier`,type:1,loc:[609,192],rule:'Ecclesiastical',connect:[{name:`Simmern`,type:0},{name:`Metz`,type:0},{name:`Luxemburg`,type:1}]},
                {name:`Luxemburg`,type:0,loc:[448,251],rule:'Habsburg',connect:[{name:`Trier`,type:1},{name:`Metz`,type:0}]},
                {name:`Heidelberg`,type:1,loc:[1202,378],rule:'Wittelsbach',connect:[{name:`Frankfurt`,type:0},{name:`Stuttgart`,type:0},{name:`Speyer`,type:0},{name:`Oppenheim`,type:1}]},
                {name:`Speyer`,type:0,loc:[1123,414],rule:'Zähringen',connect:[{name:`Pirmasens`,type:1},{name:`Heidelberg`,type:0},{name:`Oppenheim`,type:0},{name:`Stuttgart`,type:0},{name:`Straßburg`,type:0}]},
                {name:`Metz`,type:0,loc:[448,482],rule:'Lorraine',connect:[{name:`Trier`,type:0},{name:`Pirmasens`,type:0},{name:`Bar`,type:1},{name:`Nanzig`,type:0},{name:`Luxemburg`,type:0}]},
                {name:`Pirmasens`,type:0,loc:[825,489],rule:'League of Cities',connect:[{name:`Oppenheim`,type:0},{name:`Metz`,type:0},{name:`Speyer`,type:1},{name:`Straßburg`,type:0}]},
                {name:`Hall`,type:0,loc:[1510,522],rule:'League of Cities',connect:[{name:`Würzburg`,type:0},{name:`Stuttgart`,type:0},{name:`Ulm`,type:0}]},
                {name:`Bar`,type:0,loc:[129,640],rule:'Lillebonne',connect:[{name:`Metz`,type:1},{name:`Nanzig`,type:1}]},
                {name:`Stuttgart`,type:0,loc:[1336,683],rule:'Württemberg',connect:[{name:`Heidelberg`,type:0},{name:`Speyer`,type:0},{name:`Hall`,type:0},{name:`Ulm`,type:0}]},
                {name:`Nanzig`,type:2,loc:[441,688],rule:'Lorraine',connect:[{name:`Metz`,type:0},{name:`Bar`,type:1},{name:`Straßburg`,type:0}]},
                {name:`Straßburg`,type:0,loc:[916,764],rule:'League of Cities',connect:[{name:`Nanzig`,type:0},{name:`Pirmasens`,type:0},{name:`Speyer`,type:0}]},
                {name:`Ulm`,type:0,loc:[1586,865],rule:'League of Cities',connect:[{name:`Hall`,type:0},{name:`Stuttgart`,type:0}]},
            ],team:[
                {name:`Isenberg`,term:`isenberg`,allies:[],quality:1,chance:0.5},
                {name:`Zähringen`,term:`zahringen`,allies:[],quality:1,chance:0.5},
                {name:`Lillebonne`,term:`lillebonne`,allies:[],quality:1,chance:0.5},
                {name:`Württemberg`,term:`wurttemberg`,allies:[],quality:1,chance:0.5},
                {name:`Bibra`,term:`bibra`,allies:[],quality:1,chance:1},
                {name:`Ecclesiastical`,term:`ecclesiastical`,allies:[],quality:0.9,chance:1},
                {name:`Lorraine`,term:`lorraine`,allies:[],quality:1,chance:1},
                {name:`Habsburg`,term:`elder habsburg`,allies:[],quality:1,chance:1},
                {name:`League of Cities`,term:`league of cities`,allies:[],quality:0.9,chance:1.5},
                {name:`Wittelsbach`,term:`elder wittelsbach`,allies:[],quality:1,chance:1.5},
            ],
        },{
            name:`HRE`,
            term:`hre`,
            teamSet:3,
            constants:{spawn:{base:2500,spend:1000,regen:10,garrison:500}},
            city:[
                {name:`Rostock`,type:0,loc:[2399,437],rule:'Niklot',connect:[{name:`Schwerin`,type:0},{name:`Lübeck`,type:2},{name:`Waren`,type:0}]},
                {name:`Lübeck`,type:0,loc:[2024,539],rule:'Ascania',connect:[{name:`Schwerin`,type:0},{name:`Lüneburg`,type:1},{name:`Glückstadt`,type:0},{name:`Rostock`,type:2}]},
                {name:`Glückstadt`,type:2,loc:[1690,597],rule:'Hohenzollern',connect:[{name:`Lübeck`,type:0},{name:`Lüneburg`,type:1},{name:`Bremen`,type:0},{name:`Jever`,type:2}]},
                {name:`Schwerin`,type:1,loc:[2196,640],rule:'Niklot',connect:[{name:`Rostock`,type:0},{name:`Lübeck`,type:0},{name:`Lüneburg`,type:1},{name:`Waren`,type:0}]},
                {name:`Jever`,type:0,loc:[1251,675],rule:'Wiemken',connect:[{name:`Oldenburg`,type:0},{name:`Meppen`,type:0},{name:`Glückstadt`,type:2},{name:`Emden`,type:0}]},
                {name:`Waren`,type:0,loc:[2558,704],rule:'Niklot',connect:[{name:`Schwerin`,type:0},{name:`Rostock`,type:0}]},
                {name:`Emden`,type:0,loc:[1067,761],rule:'Arenberg',connect:[{name:`Oldenburg`,type:0},{name:`Jever`,type:0},{name:`Meppen`,type:0}]},
                {name:`Lüneburg`,type:0,loc:[1929,847],rule:'Welf',connect:[{name:`Lübeck`,type:1},{name:`Schwerin`,type:1},{name:`Bremen`,type:0},{name:`Celle`,type:0},{name:`Braunschweig`,type:1},{name:`Glückstadt`,type:1}]},
                {name:`Oldenburg`,type:0,loc:[1328,892],rule:'Arenberg',connect:[{name:`Jever`,type:0},{name:`Meppen`,type:0},{name:`Bremen`,type:0},{name:`Minden`,type:0},{name:`Emden`,type:0}]},
                {name:`Bremen`,type:0,loc:[1493,926],rule:'Ecclesiastical',connect:[{name:`Oldenburg`,type:0},{name:`Lüneburg`,type:0},{name:`Celle`,type:0},{name:`Glückstadt`,type:0}]},
                {name:`Meppen`,type:1,loc:[1067,1094],rule:'Arenberg',connect:[{name:`Oldenburg`,type:0},{name:`Jever`,type:0},{name:`Minden`,type:0},{name:`Emden`,type:0}]},
                {name:`Celle`,type:0,loc:[1837,1151],rule:'Welf',connect:[{name:`Bremen`,type:0},{name:`Minden`,type:0},{name:`Hannover`,type:0},{name:`Braunschweig`,type:0},{name:`Lüneburg`,type:0}]},
                {name:`Hannover`,type:0,loc:[1749,1279],rule:'Welf',connect:[{name:`Celle`,type:0},{name:`Braunschweig`,type:0},{name:`Goslar`,type:0},{name:`Minden`,type:0},{name:`Paderborn`,type:1}]},
                {name:`Minden`,type:0,loc:[1524,1304],rule:'Ecclesiastical',connect:[{name:`Meppen`,type:0},{name:`Oldenburg`,type:0},{name:`Hannover`,type:0},{name:`Paderborn`,type:0},{name:`Celle`,type:0}]},
                {name:`Braunschweig`,type:2,loc:[1972,1327],rule:'Welf',connect:[{name:`Lüneburg`,type:1},{name:`Hannover`,type:0},{name:`Goslar`,type:0},{name:`Celle`,type:0}]},
                {name:`Goslar`,type:0,loc:[1948,1491],rule:'Avesnes',connect:[{name:`Braunschweig`,type:0},{name:`Hannover`,type:0},{name:`Kassel`,type:1},{name:`Erfurt`,type:0}]},
                {name:`Paderborn`,type:2,loc:[1472,1579],rule:'Ecclesiastical',connect:[{name:`Minden`,type:0},{name:`Hannover`,type:1},{name:`Kassel`,type:0},{name:`Fredeburg`,type:1}]},
                {name:`Kassel`,type:0,loc:[1673,1771],rule:'Hesse',connect:[{name:`Goslar`,type:1},{name:`Paderborn`,type:0},{name:`Fredeburg`,type:0},{name:`Gießen`,type:0},{name:`Fulda`,type:0},{name:`Erfurt`,type:1}]},
                {name:`Düsseldorf`,type:0,loc:[911,1806],rule:'Junior Wittelsbach',connect:[{name:`Köln`,type:1},{name:`Altena`,type:0},{name:`Siegen`,type:0}]},
                {name:`Altena`,type:0,loc:[1166,1814],rule:'Hohenzollern',connect:[{name:`Fredeburg`,type:0},{name:`Düsseldorf`,type:0}]},
                {name:`Fredeburg`,type:0,loc:[1333,1850],rule:'Ecclesiastical',connect:[{name:`Kassel`,type:0},{name:`Paderborn`,type:1},{name:`Siegen`,type:0},{name:`Altena`,type:0}]},
                {name:`Erfurt`,type:2,loc:[2127,1950],rule:'Wettin',connect:[{name:`Goslar`,type:0},{name:`Kassel`,type:1},{name:`Fulda`,type:1},{name:`Coburg`,type:0},{name:`Gera`,type:0}]},
                {name:`Köln`,type:2,loc:[946,1952],rule:'Junior Wittelsbach',connect:[{name:`Koblenz`,type:0},{name:`Düsseldorf`,type:1},{name:`Lüttich`,type:1}]},
                {name:`Gera`,type:0,loc:[2431,1983],rule:'Wettin',connect:[{name:`Erfurt`,type:0},{name:`Plauen`,type:0},{name:`Coburg`,type:0}]},
                {name:`Siegen`,type:0,loc:[1267,1989],rule:'Nassau',connect:[{name:`Düsseldorf`,type:0},{name:`Fredeburg`,type:0},{name:`Gießen`,type:0},{name:`Koblenz`,type:0}]},
                {name:`Lüttich`,type:0,loc:[536,2083],rule:'Ecclesiastical',connect:[{name:`Köln`,type:0},{name:`Rochefort`,type:0},{name:`Luxemburg`,type:0}]},
                {name:`Gießen`,type:0,loc:[1445,2110],rule:'Hesse',connect:[{name:`Kassel`,type:0},{name:`Fulda`,type:0},{name:`Siegen`,type:0},{name:`Frankfurt`,type:0}]},
                {name:`Fulda`,type:0,loc:[1736,2148],rule:'Ecclesiastical',connect:[{name:`Kassel`,type:0},{name:`Erfurt`,type:1},{name:`Coburg`,type:1},{name:`Gießen`,type:0},{name:`Schweinfurt`,type:0}]},
                {name:`Plauen`,type:0,loc:[2445,2173],rule:'Hohenzollern',connect:[{name:`Bamberg`,type:0},{name:`Amberg`,type:0},{name:`Gera`,type:0},{name:`Nürnberg`,type:0}]},
                {name:`Koblenz`,type:0,loc:[1119,2239],rule:'Ecclesiastical',connect:[{name:`Köln`,type:0},{name:`Siegen`,type:0},{name:`Simmern`,type:0},{name:`Trier`,type:1},{name:`Frankfurt`,type:0}]},
                {name:`Rochefort`,type:0,loc:[461,2277],rule:'Avesnes',connect:[{name:`Köln`,type:0},{name:`Rochefort`,type:0},{name:`Luxemburg`,type:0},{name:`Lüttich`,type:0}]},
                {name:`Coburg`,type:0,loc:[2108,2294],rule:'Wettin',connect:[{name:`Erfurt`,type:0},{name:`Gera`,type:0},{name:`Fulda`,type:1},{name:`Bamberg`,type:0},{name:`Schweinfurt`,type:0}]},
                {name:`Frankfurt`,type:2,loc:[1448,2359],rule:'Isenberg',connect:[{name:`Gießen`,type:0},{name:`Würzburg`,type:1},{name:`Heidelberg`,type:0},{name:`Oppenheim`,type:1},{name:`Koblenz`,type:0}]},
                {name:`Schweinfurt`,type:0,loc:[1894,2396],rule:'Bibra',connect:[{name:`Bamberg`,type:0},{name:`Fulda`,type:0},{name:`Coburg`,type:0},{name:`Würzburg`,type:0}]},
                {name:`Simmern`,type:0,loc:[1119,2418],rule:'Elder Wittelsbach',connect:[{name:`Koblenz`,type:0},{name:`Trier`,type:0},{name:`Oppenheim`,type:0}]},
                {name:`Bamberg`,type:0,loc:[2077,2486],rule:'Bibra',connect:[{name:`Würzburg`,type:1},{name:`Schweinfurt`,type:0},{name:`Coburg`,type:0},{name:`Plauen`,type:0},{name:`Nürnberg`,type:0}]},
                {name:`Oppenheim`,type:0,loc:[1331,2487],rule:'Elder Wittelsbach',connect:[{name:`Speyer`,type:0},{name:`Heidelberg`,type:1},{name:`Frankfurt`,type:1},{name:`Simmern`,type:0},{name:`Pirmasens`,type:0}]},
                {name:`Würzburg`,type:1,loc:[1812,2526],rule:'Bibra',connect:[{name:`Bamberg`,type:1},{name:`Hall`,type:0},{name:`Frankfurt`,type:1},{name:`Nürnberg`,type:1},{name:`Schweinfurt`,type:0}]},
                {name:`Trier`,type:1,loc:[841,2527],rule:'Ecclesiastical',connect:[{name:`Koblenz`,type:1},{name:`Simmern`,type:0},{name:`Metz`,type:0},{name:`Luxemburg`,type:1}]},
                {name:`Luxemburg`,type:0,loc:[680,2586],rule:'Elder Habsburg',connect:[{name:`Trier`,type:1},{name:`Metz`,type:0},{name:`Rochefort`,type:0},{name:`Lüttich`,type:0}]},
                {name:`Nürnberg`,type:2,loc:[2149,2693],rule:'Hohenzollern',connect:[{name:`Ingolstadt`,type:0},{name:`Amberg`,type:0},{name:`Hall`,type:1},{name:`Würzburg`,type:1},{name:`Bamberg`,type:0},{name:`Plauen`,type:0}]},
                {name:`Amberg`,type:0,loc:[2396,2705],rule:'Elder Wittelsbach',connect:[{name:`Regensburg`,type:0},{name:`Ingolstadt`,type:0},{name:`Plauen`,type:0},{name:`Nürnberg`,type:0},{name:`Straubing`,type:0}]},
                {name:`Heidelberg`,type:1,loc:[1434,2713],rule:'Elder Wittelsbach',connect:[{name:`Frankfurt`,type:0},{name:`Stuttgart`,type:0},{name:`Speyer`,type:0},{name:`Oppenheim`,type:1}]},
                {name:`Speyer`,type:0,loc:[1355,2749],rule:'Zähringen',connect:[{name:`Pirmasens`,type:1},{name:`Heidelberg`,type:0},{name:`Oppenheim`,type:0},{name:`Stuttgart`,type:0},{name:`Freiburg`,type:0}]},
                {name:`Metz`,type:0,loc:[680,2817],rule:'Lorraine',connect:[{name:`Trier`,type:0},{name:`Pirmasens`,type:0},{name:`Bar`,type:1},{name:`Nanzig`,type:0},{name:`Luxemburg`,type:0}]},
                {name:`Pirmasens`,type:0,loc:[1057,2824],rule:'League of Cities',connect:[{name:`Oppenheim`,type:0},{name:`Metz`,type:0},{name:`Speyer`,type:1},{name:`Straßburg`,type:0}]},
                {name:`Hall`,type:0,loc:[1742,2857],rule:'League of Cities',connect:[{name:`Nürnberg`,type:1},{name:`Würzburg`,type:0},{name:`Stuttgart`,type:0},{name:`Ulm`,type:0}]},
                {name:`Regensburg`,type:1,loc:[2456,2894],rule:'Ecclesiastical',connect:[{name:`Amberg`,type:0},{name:`Ingolstadt`,type:0},{name:`Straubing`,type:0}]},
                {name:`Straubing`,type:0,loc:[2601,2956],rule:'Ecclesiastical',connect:[{name:`Amberg`,type:0},{name:`Regensburg`,type:0}]},
                {name:`Bar`,type:0,loc:[361,2975],rule:'Lillebonne',connect:[{name:`Metz`,type:1},{name:`Spinneln`,type:1}]},
                {name:`Stuttgart`,type:0,loc:[1568,3018],rule:'Württemberg',connect:[{name:`Heidelberg`,type:0},{name:`Speyer`,type:0},{name:`Hall`,type:0},{name:`Ulm`,type:0},{name:`Freiburg`,type:0}]},
                {name:`Nanzig`,type:2,loc:[673,3023],rule:'Lorraine',connect:[{name:`Metz`,type:0},{name:`Spinneln`,type:0},{name:`Straßburg`,type:0}]},
                {name:`Ingolstadt`,type:0,loc:[2246,3025],rule:'Junior Wittelsbach',connect:[{name:`Ulm`,type:0},{name:`Regensburg`,type:0},{name:`Amberg`,type:0},{name:`Nürnberg`,type:0}]},
                {name:`Straßburg`,type:0,loc:[1148,3099],rule:'League of Cities',connect:[{name:`Nanzig`,type:0},{name:`Pirmasens`,type:0},{name:`Freiburg`,type:1},{name:`Vesoul`,type:0},{name:`Spinneln`,type:1}]},
                {name:`Ulm`,type:0,loc:[1818,3200],rule:'League of Cities',connect:[{name:`Hall`,type:0},{name:`Stuttgart`,type:0},{name:`Ingolstadt`,type:0},{name:`Bregenz`,type:0}]},
                {name:`Spinneln`,type:0,loc:[750,3284],rule:'Lorraine',connect:[{name:`Vesoul`,type:0},{name:`Bar`,type:1},{name:`Straßburg`,type:1},{name:`Nanzig`,type:0}]},
                {name:`Freiburg`,type:0,loc:[1176,3389],rule:'Junior Habsburg',connect:[{name:`Speyer`,type:0},{name:`Straßburg`,type:1},{name:`Stuttgart`,type:0},{name:`Konstanz`,type:0},{name:`Solothurn`,type:1}]},
                {name:`Vesoul`,type:0,loc:[632,3550],rule:'Elder Habsburg',connect:[{name:`Spinneln`,type:0},{name:`Straßburg`,type:0},{name:`Bisanz`,type:0}]},
                {name:`Konstanz`,type:2,loc:[1562,3554],rule:'Junior Habsburg',connect:[{name:`Freiburg`,type:0},{name:`Bregenz`,type:0},{name:`Herisau`,type:0}]},
                {name:`Bregenz`,type:0,loc:[1756,3640],rule:'Junior Habsburg',connect:[{name:`Ulm`,type:0},{name:`Konstanz`,type:0},{name:`Herisau`,type:1},{name:`Davos`,type:0}]},
                {name:`Herisau`,type:0,loc:[1589,3710],rule:'Schwyz',connect:[{name:`Bregenz`,type:1},{name:`Konstanz`,type:0},{name:`Davos`,type:1},{name:`Solothurn`,type:1}]},
                {name:`Bisanz`,type:2,loc:[588,3728],rule:'Elder Habsburg',connect:[{name:`Vesoul`,type:0},{name:`Solothurn`,type:1}]},
                {name:`Solothurn`,type:0,loc:[1068,3774],rule:'Junior Habsburg',connect:[{name:`Bisanz`,type:1},{name:`Herisau`,type:1},{name:`Freiburg`,type:1}]},
                {name:`Davos`,type:0,loc:[1749,3978],rule:'Two Leagues',connect:[{name:`Bregenz`,type:0},{name:`Herisau`,type:1}]},
            ],team:[
                {name:`Wiemken`,term:`wiemken`,allies:[],quality:1,chance:0.5},
                {name:`Isenberg`,term:`isenberg`,allies:[],quality:1,chance:0.5},
                {name:`Nassau`,term:`nassau`,allies:[],quality:1,chance:0.5},
                {name:`Zähringen`,term:`zahringen`,allies:[],quality:1,chance:0.5},
                {name:`Ascania`,term:`ascania`,allies:[],quality:1,chance:0.5},
                {name:`Schwyz`,term:`schwyz`,allies:[`Two Leagues`],quality:1.1,chance:0.5},
                {name:`Two Leagues`,term:`two leagues`,allies:[`Schwyz`],quality:1,chance:0.5},
                {name:`Lillebonne`,term:`lillebonne`,allies:[],quality:1,chance:0.5},
                {name:`Württemberg`,term:`wurttemberg`,allies:[],quality:1,chance:0.5},
                {name:`Avesnes`,term:`avesnes`,allies:[],quality:1,chance:1},
                {name:`Hesse`,term:`hesse`,allies:[],quality:1,chance:1},
                {name:`Arenberg`,term:`arenberg`,allies:[],quality:1,chance:1},
                {name:`Niklot`,term:`niklot`,allies:[],quality:1,chance:1},
                {name:`Bibra`,term:`bibra`,allies:[],quality:1,chance:1.5},
                {name:`Hohenzollern`,term:`hohenzollern`,allies:[],quality:1,chance:1.5},
                {name:`Ecclesiastical`,term:`ecclesiastical`,allies:[],quality:0.9,chance:1.5},
                {name:`League of Cities`,term:`league of cities`,allies:[],quality:0.9,chance:1.5},
                {name:`Lorraine`,term:`lorraine`,allies:[],quality:1,chance:1.5},
                {name:`Welf`,term:`welf`,allies:[],quality:1,chance:1.5},
                {name:`Wettin`,term:`wettin`,allies:[],quality:1,chance:1.5},
                {name:`Elder Habsburg`,term:`elder habsburg`,allies:[`Junior Habsburg`],quality:1,chance:1.5},
                {name:`Junior Habsburg`,term:`junior habsburg`,allies:[`Elder Habsburg`],quality:1,chance:1.5},
                {name:`Elder Wittelsbach`,term:`elder wittelsbach`,allies:[`Junior Wittelsbach`],quality:1,chance:1.5},
                {name:`Junior Wittelsbach`,term:`junior wittelsbach`,allies:[`Elder Wittelsbach`],quality:1,chance:1.5},
            ],
        },{
            name:`HRE + Bohemia`,
            term:`hre+bohemia`,
            teamSet:3,
            constants:{spawn:{base:2500,spend:1000,regen:10,garrison:500}},
            city:[
                {name:`Rostock`,type:0,loc:[2399,437],rule:'Niklot',connect:[{name:`Schwerin`,type:0},{name:`Lübeck`,type:2},{name:`Waren`,type:0}]},
                {name:`Lübeck`,type:0,loc:[2024,539],rule:'Ascania',connect:[{name:`Schwerin`,type:0},{name:`Lüneburg`,type:1},{name:`Glückstadt`,type:0},{name:`Rostock`,type:2}]},
                {name:`Glückstadt`,type:2,loc:[1690,597],rule:'Hohenzollern',connect:[{name:`Lübeck`,type:0},{name:`Lüneburg`,type:1},{name:`Bremen`,type:0},{name:`Jever`,type:2}]},
                {name:`Schwerin`,type:1,loc:[2196,640],rule:'Niklot',connect:[{name:`Rostock`,type:0},{name:`Lübeck`,type:0},{name:`Lüneburg`,type:1},{name:`Waren`,type:0}]},
                {name:`Jever`,type:0,loc:[1251,675],rule:'Wiemken',connect:[{name:`Oldenburg`,type:0},{name:`Meppen`,type:0},{name:`Glückstadt`,type:2},{name:`Emden`,type:0}]},
                {name:`Waren`,type:0,loc:[2558,704],rule:'Niklot',connect:[{name:`Schwerin`,type:0},{name:`Rostock`,type:0}]},
                {name:`Emden`,type:0,loc:[1067,761],rule:'Arenberg',connect:[{name:`Oldenburg`,type:0},{name:`Jever`,type:0},{name:`Meppen`,type:0}]},
                {name:`Lüneburg`,type:0,loc:[1929,847],rule:'Welf',connect:[{name:`Lübeck`,type:1},{name:`Schwerin`,type:1},{name:`Bremen`,type:0},{name:`Celle`,type:0},{name:`Braunschweig`,type:1},{name:`Glückstadt`,type:1}]},
                {name:`Oldenburg`,type:0,loc:[1328,892],rule:'Arenberg',connect:[{name:`Jever`,type:0},{name:`Meppen`,type:0},{name:`Bremen`,type:0},{name:`Minden`,type:0},{name:`Emden`,type:0}]},
                {name:`Bremen`,type:0,loc:[1493,926],rule:'Ecclesiastical',connect:[{name:`Oldenburg`,type:0},{name:`Lüneburg`,type:0},{name:`Celle`,type:0},{name:`Glückstadt`,type:0}]},
                {name:`Meppen`,type:1,loc:[1067,1094],rule:'Arenberg',connect:[{name:`Oldenburg`,type:0},{name:`Jever`,type:0},{name:`Minden`,type:0},{name:`Emden`,type:0}]},
                {name:`Celle`,type:0,loc:[1837,1151],rule:'Welf',connect:[{name:`Bremen`,type:0},{name:`Minden`,type:0},{name:`Hannover`,type:0},{name:`Braunschweig`,type:0},{name:`Lüneburg`,type:0}]},
                {name:`Hannover`,type:0,loc:[1749,1279],rule:'Welf',connect:[{name:`Celle`,type:0},{name:`Braunschweig`,type:0},{name:`Goslar`,type:0},{name:`Minden`,type:0},{name:`Paderborn`,type:1}]},
                {name:`Minden`,type:0,loc:[1524,1304],rule:'Ecclesiastical',connect:[{name:`Meppen`,type:0},{name:`Oldenburg`,type:0},{name:`Hannover`,type:0},{name:`Paderborn`,type:0},{name:`Celle`,type:0}]},
                {name:`Braunschweig`,type:2,loc:[1972,1327],rule:'Welf',connect:[{name:`Lüneburg`,type:1},{name:`Hannover`,type:0},{name:`Goslar`,type:0},{name:`Celle`,type:0}]},
                {name:`Goslar`,type:0,loc:[1948,1491],rule:'Avesnes',connect:[{name:`Braunschweig`,type:0},{name:`Hannover`,type:0},{name:`Kassel`,type:1},{name:`Erfurt`,type:0}]},
                {name:`Paderborn`,type:2,loc:[1472,1579],rule:'Ecclesiastical',connect:[{name:`Minden`,type:0},{name:`Hannover`,type:1},{name:`Kassel`,type:0},{name:`Fredeburg`,type:1}]},
                {name:`Kassel`,type:0,loc:[1673,1771],rule:'Hesse',connect:[{name:`Goslar`,type:1},{name:`Paderborn`,type:0},{name:`Fredeburg`,type:0},{name:`Gießen`,type:0},{name:`Fulda`,type:0},{name:`Erfurt`,type:1}]},
                {name:`Düsseldorf`,type:0,loc:[911,1806],rule:'Junior Wittelsbach',connect:[{name:`Köln`,type:1},{name:`Altena`,type:0},{name:`Siegen`,type:0}]},
                {name:`Altena`,type:0,loc:[1166,1814],rule:'Hohenzollern',connect:[{name:`Fredeburg`,type:0},{name:`Düsseldorf`,type:0}]},
                {name:`Fredeburg`,type:0,loc:[1333,1850],rule:'Ecclesiastical',connect:[{name:`Kassel`,type:0},{name:`Paderborn`,type:1},{name:`Siegen`,type:0},{name:`Altena`,type:0}]},
                {name:`Erfurt`,type:2,loc:[2127,1950],rule:'Wettin',connect:[{name:`Goslar`,type:0},{name:`Kassel`,type:1},{name:`Fulda`,type:1},{name:`Coburg`,type:0},{name:`Gera`,type:0}]},
                {name:`Köln`,type:2,loc:[946,1952],rule:'Junior Wittelsbach',connect:[{name:`Koblenz`,type:0},{name:`Düsseldorf`,type:1},{name:`Lüttich`,type:1}]},
                {name:`Gera`,type:0,loc:[2431,1983],rule:'Wettin',connect:[{name:`Erfurt`,type:0},{name:`Plauen`,type:0},{name:`Coburg`,type:0}]},
                {name:`Siegen`,type:0,loc:[1267,1989],rule:'Nassau',connect:[{name:`Düsseldorf`,type:0},{name:`Fredeburg`,type:0},{name:`Gießen`,type:0},{name:`Koblenz`,type:0}]},
                {name:`Lüttich`,type:0,loc:[536,2083],rule:'Ecclesiastical',connect:[{name:`Köln`,type:0},{name:`Rochefort`,type:0},{name:`Luxemburg`,type:0}]},
                {name:`Gießen`,type:0,loc:[1445,2110],rule:'Hesse',connect:[{name:`Kassel`,type:0},{name:`Fulda`,type:0},{name:`Siegen`,type:0},{name:`Frankfurt`,type:0}]},
                {name:`Fulda`,type:0,loc:[1736,2148],rule:'Ecclesiastical',connect:[{name:`Kassel`,type:0},{name:`Erfurt`,type:1},{name:`Coburg`,type:1},{name:`Gießen`,type:0},{name:`Schweinfurt`,type:0}]},
                {name:`Plauen`,type:0,loc:[2445,2173],rule:'Hohenzollern',connect:[{name:`Bamberg`,type:0},{name:`Amberg`,type:0},{name:`Gera`,type:0},{name:`Nürnberg`,type:0},{name:`Eger`,type:0}]},
                {name:`Koblenz`,type:0,loc:[1119,2239],rule:'Ecclesiastical',connect:[{name:`Köln`,type:0},{name:`Siegen`,type:0},{name:`Simmern`,type:0},{name:`Trier`,type:1},{name:`Frankfurt`,type:0}]},
                {name:`Rochefort`,type:0,loc:[461,2277],rule:'Avesnes',connect:[{name:`Köln`,type:0},{name:`Rochefort`,type:0},{name:`Luxemburg`,type:0},{name:`Lüttich`,type:0}]},
                {name:`Coburg`,type:0,loc:[2108,2294],rule:'Wettin',connect:[{name:`Erfurt`,type:0},{name:`Gera`,type:0},{name:`Fulda`,type:1},{name:`Bamberg`,type:0},{name:`Schweinfurt`,type:0}]},
                {name:`Frankfurt`,type:2,loc:[1448,2359],rule:'Isenberg',connect:[{name:`Gießen`,type:0},{name:`Würzburg`,type:1},{name:`Heidelberg`,type:0},{name:`Oppenheim`,type:1},{name:`Koblenz`,type:0}]},
                {name:`Schweinfurt`,type:0,loc:[1894,2396],rule:'Bibra',connect:[{name:`Bamberg`,type:0},{name:`Fulda`,type:0},{name:`Coburg`,type:0},{name:`Würzburg`,type:0}]},
                {name:`Simmern`,type:0,loc:[1119,2418],rule:'Elder Wittelsbach',connect:[{name:`Koblenz`,type:0},{name:`Trier`,type:0},{name:`Oppenheim`,type:0}]},
                {name:`Bamberg`,type:0,loc:[2077,2486],rule:'Bibra',connect:[{name:`Würzburg`,type:1},{name:`Schweinfurt`,type:0},{name:`Coburg`,type:0},{name:`Plauen`,type:0},{name:`Nürnberg`,type:0}]},
                {name:`Oppenheim`,type:0,loc:[1331,2487],rule:'Elder Wittelsbach',connect:[{name:`Speyer`,type:0},{name:`Heidelberg`,type:1},{name:`Frankfurt`,type:1},{name:`Simmern`,type:0},{name:`Pirmasens`,type:0}]},
                {name:`Würzburg`,type:1,loc:[1812,2526],rule:'Bibra',connect:[{name:`Bamberg`,type:1},{name:`Hall`,type:0},{name:`Frankfurt`,type:1},{name:`Nürnberg`,type:1},{name:`Schweinfurt`,type:0}]},
                {name:`Trier`,type:1,loc:[841,2527],rule:'Ecclesiastical',connect:[{name:`Koblenz`,type:1},{name:`Simmern`,type:0},{name:`Metz`,type:0},{name:`Luxemburg`,type:1}]},
                {name:`Luxemburg`,type:0,loc:[680,2586],rule:'Elder Habsburg',connect:[{name:`Trier`,type:1},{name:`Metz`,type:0},{name:`Rochefort`,type:0},{name:`Lüttich`,type:0}]},
                {name:`Nürnberg`,type:2,loc:[2149,2693],rule:'Hohenzollern',connect:[{name:`Ingolstadt`,type:0},{name:`Amberg`,type:0},{name:`Hall`,type:1},{name:`Würzburg`,type:1},{name:`Bamberg`,type:0},{name:`Plauen`,type:0}]},
                {name:`Amberg`,type:0,loc:[2396,2705],rule:'Elder Wittelsbach',connect:[{name:`Regensburg`,type:0},{name:`Ingolstadt`,type:0},{name:`Plauen`,type:0},{name:`Nürnberg`,type:0},{name:`Straubing`,type:0},{name:`Eger`,type:0}]},
                {name:`Heidelberg`,type:1,loc:[1434,2713],rule:'Elder Wittelsbach',connect:[{name:`Frankfurt`,type:0},{name:`Stuttgart`,type:0},{name:`Speyer`,type:0},{name:`Oppenheim`,type:1}]},
                {name:`Speyer`,type:0,loc:[1355,2749],rule:'Zähringen',connect:[{name:`Pirmasens`,type:1},{name:`Heidelberg`,type:0},{name:`Oppenheim`,type:0},{name:`Stuttgart`,type:0},{name:`Freiburg`,type:0}]},
                {name:`Metz`,type:0,loc:[680,2817],rule:'Lorraine',connect:[{name:`Trier`,type:0},{name:`Pirmasens`,type:0},{name:`Bar`,type:1},{name:`Nanzig`,type:0},{name:`Luxemburg`,type:0}]},
                {name:`Pirmasens`,type:0,loc:[1057,2824],rule:'League of Cities',connect:[{name:`Oppenheim`,type:0},{name:`Metz`,type:0},{name:`Speyer`,type:1},{name:`Straßburg`,type:0}]},
                {name:`Hall`,type:0,loc:[1742,2857],rule:'League of Cities',connect:[{name:`Nürnberg`,type:1},{name:`Würzburg`,type:0},{name:`Stuttgart`,type:0},{name:`Ulm`,type:0}]},
                {name:`Regensburg`,type:1,loc:[2456,2894],rule:'Ecclesiastical',connect:[{name:`Amberg`,type:0},{name:`Ingolstadt`,type:0},{name:`Straubing`,type:0}]},
                {name:`Straubing`,type:0,loc:[2601,2956],rule:'Ecclesiastical',connect:[{name:`Amberg`,type:0},{name:`Regensburg`,type:0},{name:`Klattau`,type:1}]},
                {name:`Bar`,type:0,loc:[361,2975],rule:'Lillebonne',connect:[{name:`Metz`,type:1},{name:`Spinneln`,type:1}]},
                {name:`Stuttgart`,type:0,loc:[1568,3018],rule:'Württemberg',connect:[{name:`Heidelberg`,type:0},{name:`Speyer`,type:0},{name:`Hall`,type:0},{name:`Ulm`,type:0},{name:`Freiburg`,type:0}]},
                {name:`Nanzig`,type:2,loc:[673,3023],rule:'Lorraine',connect:[{name:`Metz`,type:0},{name:`Spinneln`,type:0},{name:`Straßburg`,type:0}]},
                {name:`Ingolstadt`,type:0,loc:[2246,3025],rule:'Junior Wittelsbach',connect:[{name:`Ulm`,type:0},{name:`Regensburg`,type:0},{name:`Amberg`,type:0},{name:`Nürnberg`,type:0}]},
                {name:`Straßburg`,type:0,loc:[1148,3099],rule:'League of Cities',connect:[{name:`Nanzig`,type:0},{name:`Pirmasens`,type:0},{name:`Freiburg`,type:1},{name:`Vesoul`,type:0},{name:`Spinneln`,type:1}]},
                {name:`Ulm`,type:0,loc:[1818,3200],rule:'League of Cities',connect:[{name:`Hall`,type:0},{name:`Stuttgart`,type:0},{name:`Ingolstadt`,type:0},{name:`Bregenz`,type:0}]},
                {name:`Spinneln`,type:0,loc:[750,3284],rule:'Lorraine',connect:[{name:`Vesoul`,type:0},{name:`Bar`,type:1},{name:`Straßburg`,type:1},{name:`Nanzig`,type:0}]},
                {name:`Freiburg`,type:0,loc:[1176,3389],rule:'Junior Habsburg',connect:[{name:`Speyer`,type:0},{name:`Straßburg`,type:1},{name:`Stuttgart`,type:0},{name:`Konstanz`,type:0},{name:`Solothurn`,type:1}]},
                {name:`Vesoul`,type:0,loc:[632,3550],rule:'Elder Habsburg',connect:[{name:`Spinneln`,type:0},{name:`Straßburg`,type:0},{name:`Bisanz`,type:0}]},
                {name:`Konstanz`,type:2,loc:[1562,3554],rule:'Junior Habsburg',connect:[{name:`Freiburg`,type:0},{name:`Bregenz`,type:0},{name:`Herisau`,type:0}]},
                {name:`Bregenz`,type:0,loc:[1756,3640],rule:'Junior Habsburg',connect:[{name:`Ulm`,type:0},{name:`Konstanz`,type:0},{name:`Herisau`,type:1},{name:`Davos`,type:0}]},
                {name:`Herisau`,type:0,loc:[1589,3710],rule:'Schwyz',connect:[{name:`Bregenz`,type:1},{name:`Konstanz`,type:0},{name:`Davos`,type:1},{name:`Solothurn`,type:1}]},
                {name:`Bisanz`,type:2,loc:[588,3728],rule:'Elder Habsburg',connect:[{name:`Vesoul`,type:0},{name:`Solothurn`,type:1}]},
                {name:`Solothurn`,type:0,loc:[1068,3774],rule:'Junior Habsburg',connect:[{name:`Bisanz`,type:1},{name:`Herisau`,type:1},{name:`Freiburg`,type:1}]},
                {name:`Davos`,type:0,loc:[1749,3978],rule:'Two Leagues',connect:[{name:`Bregenz`,type:0},{name:`Herisau`,type:1}]},
                {name:`Reichenberg`,type:0,loc:[3290,2024],rule:'Přemyslid',connect:[{name:`Leitmeritz`,type:0},{name:`Jitschin`,type:0},{name:`Prag`,type:1}]},
                {name:`Leitmeritz`,type:0,loc:[3014,2151],rule:'Přemyslid',connect:[{name:`Prag`,type:0},{name:`Reichenberg`,type:0},{name:`Saaz`,type:0}]},
                {name:`Jitschin`,type:0,loc:[3392,2178],rule:'Přemyslid',connect:[{name:`Kuttenberg`,type:1},{name:`Reichenberg`,type:0},{name:`Königgrätz`,type:0}]},
                {name:`Saaz`,type:0,loc:[2868,2255],rule:'Přemyslid',connect:[{name:`Pilsen`,type:0},{name:`Eger`,type:0},{name:`Leitmeritz`,type:0}]},
                {name:`Königgrätz`,type:0,loc:[3542,2276],rule:'Přemyslid',connect:[{name:`Jitschin`,type:0},{name:`Kuttenberg`,type:0}]},
                {name:`Prag`,type:1,loc:[3134,2370],rule:'Přemyslid',connect:[{name:`Leitmeritz`,type:0},{name:`Reichenberg`,type:1},{name:`Kuttenberg`,type:0},{name:`Tabor`,type:0},{name:`Pilsen`,type:1}]},
                {name:`Eger`,type:0,loc:[2522,2380],rule:'Přemyslid',connect:[{name:`Saaz`,type:0},{name:`Pilsen`,type:0},{name:`Amberg`,type:0},{name:`Plauen`,type:0}]},
                {name:`Kuttenberg`,type:0,loc:[3381,2412],rule:'Přemyslid',connect:[{name:`Königgrätz`,type:0},{name:`Tabor`,type:0},{name:`Prag`,type:0},{name:`Jitschin`,type:1}]},
                {name:`Pilsen`,type:0,loc:[2820,2528],rule:'Přemyslid',connect:[{name:`Saaz`,type:0},{name:`Eger`,type:0},{name:`Klattau`,type:1},{name:`Prag`,type:1}]},
                {name:`Tabor`,type:2,loc:[3225,2675],rule:'Přemyslid',connect:[{name:`Kuttenberg`,type:0},{name:`Prag`,type:0},{name:`Budweis`,type:0}]},
                {name:`Klattau`,type:0,loc:[2813,2708],rule:'Přemyslid',connect:[{name:`Pilsen`,type:1},{name:`Budweis`,type:0},{name:`Straubing`,type:0}]},
                {name:`Budweis`,type:0,loc:[3181,2891],rule:'Přemyslid',connect:[{name:`Tabor`,type:0},{name:`Klattau`,type:0}]},
            ],team:[
                {name:`Wiemken`,term:`wiemken`,allies:[],quality:1,chance:0.5},
                {name:`Isenberg`,term:`isenberg`,allies:[],quality:1,chance:0.5},
                {name:`Nassau`,term:`nassau`,allies:[],quality:1,chance:0.5},
                {name:`Zähringen`,term:`zahringen`,allies:[],quality:1,chance:0.5},
                {name:`Ascania`,term:`ascania`,allies:[],quality:1,chance:0.5},
                {name:`Schwyz`,term:`schwyz`,allies:[`Two Leagues`],quality:1.1,chance:0.5},
                {name:`Two Leagues`,term:`two leagues`,allies:[`Schwyz`],quality:1,chance:0.5},
                {name:`Lillebonne`,term:`lillebonne`,allies:[],quality:1,chance:0.5},
                {name:`Württemberg`,term:`wurttemberg`,allies:[],quality:1,chance:0.5},
                {name:`Avesnes`,term:`avesnes`,allies:[],quality:1,chance:1},
                {name:`Hesse`,term:`hesse`,allies:[],quality:1,chance:1},
                {name:`Arenberg`,term:`arenberg`,allies:[],quality:1,chance:1},
                {name:`Niklot`,term:`niklot`,allies:[],quality:1,chance:1},
                {name:`Bibra`,term:`bibra`,allies:[],quality:1,chance:1.5},
                {name:`Hohenzollern`,term:`hohenzollern`,allies:[],quality:1,chance:1.5},
                {name:`Ecclesiastical`,term:`ecclesiastical`,allies:[],quality:0.9,chance:1.5},
                {name:`League of Cities`,term:`league of cities`,allies:[],quality:0.9,chance:1.5},
                {name:`Lorraine`,term:`lorraine`,allies:[],quality:1,chance:1.5},
                {name:`Welf`,term:`welf`,allies:[],quality:1,chance:1.5},
                {name:`Wettin`,term:`wettin`,allies:[],quality:1,chance:1.5},
                {name:`Elder Habsburg`,term:`elder habsburg`,allies:[`Junior Habsburg`],quality:1,chance:1.5},
                {name:`Junior Habsburg`,term:`junior habsburg`,allies:[`Elder Habsburg`],quality:1,chance:1.5},
                {name:`Elder Wittelsbach`,term:`elder wittelsbach`,allies:[`Junior Wittelsbach`],quality:1,chance:1.5},
                {name:`Junior Wittelsbach`,term:`junior wittelsbach`,allies:[`Elder Wittelsbach`],quality:1,chance:1.5},
                {name:`Přemyslid`,term:`premyslid`,allies:[],quality:1,chance:5},
            ],
        },
    ],
}
convert=[
    [`Wiemken`,`Isenberg`,`Avesnes`,`Nassau`,`Zähringen`,`Ascania`,`Schwyz`,`Two Leagues`,`Lillebonne`,`Württemberg`,`Arenberg`,`Niklot`,`Bibra`,`Hesse`,`Hohenzollern`,`Ecclesiastical`,`League of Cities`,`Lorraine`,`Welf`,`Wettin`,`Elder Habsburg`,`Junior Habsburg`,`Elder Wittelsbach`,`Junior Wittelsbach`],//old teams
]
dev={road:false,instant:false,assemble:false,pause:false,new:false,speed:false,close:false}
graphics={main:0,load:{map:[],city:[],unit:[]}}
constants={trig:[[],[]],spawn:{},init:false}
inputs={mouse:{base:{x:0,y:0},rel:{x:0,y:0},previous:{base:{x:0,y:0},rel:{x:0,y:0}}}}