types.district=[
    {
        name:`Léman`,
        region:`Léman`,
        area:162385,
    },{
        name:`Franche-Comté`,
        region:`Transjurania`,
        area:838455,
    },{
        name:`Helvetie`,
        region:`Transjurania`,
        area:497888,
    },{
        name:`Romandie`,
        region:`Transjurania`,
        area:730712,
    },{
        name:`Bresse`,
        region:`Cisjurania`,
        area:317515,
    },{
        name:`Alpes`,
        region:`Cisjurania`,
        area:396714,
    },{
        name:`Dauphiné`,
        region:`Cisjurania`,
        area:792094,
    },{
        name:`Drôme`,
        region:`Provence`,
        area:652365,
    },{
        name:`Cottia`,
        region:`Provence`,
        area:522459,
    },{
        name:`Provence`,
        region:`Provence`,
        area:785672,
    },
]