import {types,graphics,options} from './variables.mjs'
import {distPos,smoothAnim,moveTowardVec,inBoxBox} from './functions.mjs'
export class unit{
    constructor(operation,player,x,y,team,type,value){
        this.operation=operation
        this.player=player
        this.position={x:x,y:y}
        this.team=team
        this.type=type
        this.value=value
        this.goal={position:{x:x,y:y},city:-1,time:0}
        this.retreat={speed:1}
        this.remove=false
        this.fade={main:0,trigger:true}
        this.speed={activation:0,max:[0,3,2.5,2,1.5][type],water:0,stun:0}
        this.time=0
        this.img=[graphics.load.team[types.team[this.team].loadIndex],graphics.load.unit[this.type]]
        this.width=0
        this.height=0
        this.fortified={trigger:false,city:0}
    }
    save(){
        let composite={
            player:this.player,
            team:this.team,
            type:this.type,
            value:this.value,
            position:this.position,
            goal:this.goal,
            retreat:this.retreat,
            remove:this.remove,
            speed:this.speed,
            time:this.time,
        }
        return composite
    }
    load(composite){
        this.player=composite.player
        this.team=composite.team
        this.type=composite.type
        this.value=composite.value
        this.position=composite.position
        this.goal=composite.goal
        this.retreat=composite.retreat
        this.remove=composite.remove
        this.speed=composite.speed
        this.time=composite.time
    }
    display(layer,scene){
        switch(scene){
            case `main`:
                if(this.fade.main>0){
                    this.width=this.img[1].width*options.unitSize*0.5
                    this.height=this.img[1].height*options.unitSize*0.5
                    layer.push()
                    layer.translate(this.position.x,this.position.y)
                    layer.image(this.img[0],0,0,(this.width-0.5)*this.fade.main,(this.height-0.5)*this.fade.main)
                    layer.image(this.img[1],0,0,this.width*this.fade.main,this.height*this.fade.main)
                    layer.noStroke()
                    layer.fill(0,this.fade.main)
                    layer.textSize(15)
                    layer.text(this.value,0,[20,26,29,32,35][this.type]*options.unitSize+3)
                    layer.pop()
                }
            break
        }
    }
    displayInfo(layer,scene){
        switch(scene){
            case `main`:
                if(this.fade.main>0){
                    layer.push()
                    layer.translate(this.position.x,this.position.y)
                    layer.fill(255,this.fade.main)
                    layer.stroke(0,this.fade.main)
                    layer.strokeWeight(2)
                    layer.textSize(15)
                    layer.text(this.value,0,[20,26,29,32,35][this.type]*options.unitSize+3)
                    layer.pop()
                }
            break
        }
    }
    update(){
        this.fade.main=smoothAnim(this.fade.main,this.fade.trigger,0,1,30)
    }
    operate(){
        if(!this.player&&this.speed.stun<=0&&inBoxBox(this,this.operation.units[0])){
            this.operation.halt()
            this.operation.ui.moveTab(1)
            this.operation.ui.battle.enemy=this
            return
        }
        this.time++
        if(this.fade.main<=0&&!this.fade.trigger){
            this.remove=true
        }
        let distGoal=distPos(this,this.goal)
        if(this.speed.max>0){
            if(distGoal>1){
                this.speed.activation=smoothAnim(this.speed.activation,true,0,1,15)
                let mult=1
                if(!this.operation.cities.some(cit=>distPos(cit,this)<50)&&graphics.load.map[this.operation.map][1].get(this.position.x/this.operation.scale,this.position.y/this.operation.scale)[3]>0.5){
                    this.speed.water++
                    mult*=min(0.6,0.1+this.speed.water*5/300)
                }else{
                    this.speed.water=0
                }
                this.position=moveTowardVec(this,this.goal,this.speed.activation*this.speed.max*this.retreat.speed*mult)
                if(this.player){
                    this.operation.time.active=true
                }
            }else{
                this.speed.activation=smoothAnim(this.speed.activation,false,0,1,15)
                if(this.player){
                    this.operation.time.active=this.operation.time.pass>0?true:false
                }
            }
        }
        if(this.retreat.speed>1){
            this.retreat.speed-=0.01
        }
        if(this.speed.stun>0){
            this.speed.stun--
        }else if(this.player){
            this.operation.zoom.position.x=this.position.x
            this.operation.zoom.position.y=this.position.y
            this.speed.max=16-log(this.value)*1.2
        }else{
            if(inBoxBox(this,this.operation.units[0])){
                this.operation.halt()
                this.operation.ui.moveTab(1)
                this.operation.ui.battle.enemy=this
                return
            }
            switch(this.type){
                case 1:
                    if(distPos(this,this.operation.units[0])<150&&this.operation.teams[this.team].spawn.aggress>0){
                        switch(this.operation.teams[this.team].spawn.aggress){
                            case 1:
                                if(this.value<=this.operation.units[0].value*1.5){
                                    this.goal.position.x=this.position.x*2-this.operation.units[0].position.x
                                    this.goal.position.y=this.position.y*2-this.operation.units[0].position.y
                                }else{
                                    this.goal.position.x=this.operation.units[0].position.x
                                    this.goal.position.y=this.operation.units[0].position.y
                                }
                            break
                            case 2:
                                this.goal.position.x=this.operation.units[0].position.x
                                this.goal.position.y=this.operation.units[0].position.y
                            break
                        }
                        if(distPos(this,this.operation.units[0])>200){
                            this.goal.city=-1
                        }
                    }else{
                        if(distGoal<=1){
                            this.goal.time++
                        }
                        if(this.goal.city==-1||this.goal.time>=30){
                            this.goal.time=0
                            this.goal.city=this.goal.nodes[this.goal.tick]
                            this.goal.tick=1-this.goal.tick
                            this.goal.position.x=this.goal.city.position.x
                            this.goal.position.y=this.goal.city.position.y+60
                        }
                    }
                break
            }
        }
    }
}